google/osv.dev

- docker/importer/importer.py
- docker/importer/importer_test.py
- lib/osv/types.py
- Start plumbing for detecting user changes and kicking off analysis tasks.
- Don't make empty commits when importing new OSS-Fuzz entries.
Part of #44.
> Plumbing in preparation for processing user changes.

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/worker/worker.py
- docker/worker/worker_test.py
- lib/osv/sources.py
If the hash changed, bail and let a later task perform the update.
> Check for hash change when processing updates.

- docker/importer/importer.py
Checkout to /work/sources/<repo> rather than /work/<repo> which could
clash.
> Fix importer source checkout path.

- docker/worker/testdata/BLAH-127.yaml
- docker/worker/testdata/expected_127.diff
- docker/worker/worker.py
- docker/worker/worker_test.py
- lib/osv/impact.py
Assume all commits prior to the fix are vulnerable.
> Allow empty introduced commit fields.

- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/vulns/vulns.go
- Handle versionStartExcluding and versionEndIncluding by using
the list of actual package versions to derive "introduced" and "fixed".
- Extract versions from description as a last resort.
> Improve CVE version extraction.

- vulnfeeds/README.md
- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/vulns/vulns.go
Convert previous warnings into an of notes which are accumulated.
These are then written alongside the .yaml to indicate that human eyes
are required.
Also implement a false positives input file to allow users to ignore
such cases in the future.
Document the workflow as well for human triagers.
> vulnfeeds: Write a .notes file when human intervention is needed.

- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/cves/cve.go
- vulnfeeds/cves/versions.go
- vulnfeeds/pypi/README.md
- vulnfeeds/pypi/pypi.go
- vulnfeeds/pypi/pypi_links.sql
- vulnfeeds/vulns/vulns.go
- Add a new heuristic to extract "vendor/product" from GitHub links
and cross reference that against CPEs.
- Also fix a bug with PyPI link parsing.
> vulnfeeds: Improve Python vuln matching.

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/worker/oss_fuzz.py
- docker/worker/worker_test.py
- gcp/appengine/frontend_handlers.py
- gcp/appengine/index.yaml
- lib/osv/types.py
Rather than only storing GIT ranges, we generalize the Datastore
properties to better reflect the actual vulnerability schema.
This is in preparation for storing ECOSYSTEM and SEMVER ranges.
> Generalize affected ranges in Datastore.

- docker/importer/importer_test.py
- docker/worker/oss_fuzz.py
- docker/worker/worker_test.py
- gcp/appengine/frontend_handlers.py
- gcp/appengine/index.yaml
- lib/osv/types.py
- Remove Bug.reference_urls. This was replaced with reference_url_types.
- Remove unneeded index.
> Cleanup from previous migrations.

- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/pypi/pypi.go
Per https://www.python.org/dev/peps/pep-0503/#normalized-names there are
multiple ways to refer to the same python package.
> Normalize Python package names for vulnfeeds.

- vulnfeeds/README.md
- vulnfeeds/cmd/ids/main.go
- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/vulns/vulns.go
Intended for use by community based vulnerability repos, where reports can can come from manual contributions from pull requests (where an ID may never have been assigned). 
This tool picks up any vulnerabilities with the ID format of `PREFIX-0000-` and assigns a real ID based on the previous maximum allocated ID in the repo. 
This can later be run as part of a GitHub action.
> Implement an ID allocator for vulnerability repos.

- vulnfeeds/README.md
- vulnfeeds/cmd/ids/main.go
- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/pypi/pypi.go
- vulnfeeds/triage/falsepositives.go
- Change false_positives file format to YAML.
- Fix ID allocation off-by-one.
- Filter out invalid PyPI versions.
- Add list of valid versions to notes for easier triaging.
> vulnfeeds: various improvements.

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/worker/testdata/PYSEC-123.yaml
- docker/worker/testdata/expected_pypi.diff
- docker/worker/worker.py
- docker/worker/worker_test.py
- lib/osv/models.py
- lib/osv/repos.py
This allows us to ignore certain files in source repositories (e.g.
unallocated IDs) when importing vulnerabilities.
Vulnerabilities with well defined ECOSYSTEM/SEMVER ranges should also
not have git ranges expanded, as they do not necessarily match the
package manager versions and just add confusion. We may revisit
this in the future.
> Add settings to ignore source repo files and ignore git ranges.

- docker/worker/worker.py
- docker/worker/worker_test.py
- gcp/appengine/frontend/src/components/List.vue
- gcp/appengine/frontend/src/components/Package.vue
- gcp/appengine/frontend/src/components/Vulnerability.vue
- gcp/appengine/frontend_handlers.py
- lib/osv/sources.py
- Fix UI to show the correct IDs for non-OSV IDs.
- Fix UI to show non-git ranges.
- Use the Vulnerability JSON for rendering on the frontend, rather than
building a custom JSON.
- Set Bug entities created from SourceRepositories to public by default.
> Various fixes in preparation for loading additional sources.

- lib/osv/semver_index.py
- lib/osv/semver_index_test.py
This will be used to normalize semver into something that can be
lexically compared and indexed.
This index will be used to efficiently serve OSV queries for ecosystems
that enforce SEMVER (e.g. Go, Rust), without having to pre-compute all
released versions.
For ecosystems like Go, this is also necessary as versions are often
specified as a "pseudo-version" which isn't a real release e.g.
"v0.0.0-20180523231146-b3f5c0f6e5f1" and having Go-specific logic to
pre-compute every single one to serve queries is not ideal.
> Add a semver_index library.

- docker/worker/worker.py
- docker/worker/worker_test.py
- gcp/appengine/frontend/src/components/Home.vue
- gcp/appengine/frontend/src/components/Package.vue
- gcp/appengine/frontend_handlers.py
- gcp/appengine/handlers.py
- gcp/appengine/index.yaml
- lib/osv/models.py
"affected" can be quite large, so we should only index it once rather
than 4x previously.
Also fix package_info task to not rely on these indexes, and generalize
it to not require a Repo URL.
> Remove some indexes.

- vulnfeeds/cmd/pypi/main.go
This flag will skip over any matched vulnerabilities with notes
associated. This can be used by automation to automatically import new
vulnerabilities with zero human intervention.
> vulnfeeds: Add a -without_notes flag.

- vulnfeeds/cves/versions.go
Add a note if we extract a version from the description that isn't
valid.
> Fix bug in vulnfeeds.

- docker/worker/worker.py
- docker/worker/worker_test.py
- lib/osv/impact.py
- lib/osv/models.py
This controls whether or not we populate the "versions" field from
input git ranges.
> Add SourceRepository.versions_from_repo

- docker/build.sh
- docker/exporter/Dockerfile
- docker/exporter/build.sh
- docker/exporter/exporter.py
This regularly exports all OSV known vulnerabilities to a bucket with a
consistent structure:
- `gs://osv-vulnerabilities/<ecosystem>/<ID>.json`
- `gs://osv-vulnerabilities/<ecosystem>/all.zip`
> Add an exporter.

- docker/worker/oss_fuzz.py
- docker/worker/worker_test.py
- lib/osv/impact.py
- Simplify range handling logic to use the first commit in a regression
range, and the last commit in a fix range.
- Don't show ranges in the actual resulting Vulnerabiltiy JSON. Show
them in `database_specific` instead.
Fixes #172.
> Simplify OSS-Fuzz range handling.

- docker/worker/oss_fuzz.py
- docker/worker/testdata/expected_127.diff
- docker/worker/worker_test.py
- lib/osv/impact.py
- lib/setup.py
- Simplify impacted tag calculation, by finding them as we
walk through commit ranges. This also fixes false positives with
assuming all tags are affected when no "introduced" commit is available.
- Don't compute cherrypicks when the input ranges are incomplete (i.e.
either no "introduced" or no "fixed"). This leads to inaccurate
results and potential false positives.
- Throttle AffectedCommit writes to 20000/5 seconds per worker.
> Many commit impact calculation fixes.

- vulnfeeds/pypi/pypi.go
Improves matching on urls for pypi packages.  Strips `.git` from the end of source control url's and extracts package names from some common variations of pypi urls
closes #186
> Improve matching on links

- vulnfeeds/pypi/pypi.go
I realised I should have used `TrimSuffix` instead of `TrimRight` when trimming `.git` from the end of reference urls.  I also added several more very generic but often encountered links to the blocklist.
> fixes for reference link matching

- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/pypi/README.md
- vulnfeeds/pypi/pypi.go
- Allow matching of multiple packages for a single CVE. Fixes #185.
- Work with normalized package names internally in pypi package.
- Always append note with all valid versions if there are any version
matching notes.
- Add documentation about continuously updated JSONs.
> Vulnfeeds fixes.

- docker/importer/importer_test.py
- docker/worker/worker.py
- docker/worker/worker_test.py
- gcp/api/integration_tests.py
- gcp/appengine/handlers.py
- lib/osv/models.py
- vulnfeeds/pypi/pypi.go
Some DBs don't allocate their own IDs. Store such `Bug`s with
Datastore IDs of the form `"source:ID"`.
If they do allocate their IDs, the Datastore ID is kept as is if the
prefix is what we expect.
Fixes #174.
> Allow shared IDs between DBs.

- gcp/api/integration_tests.py
- gcp/api/server.py
- gcp/appengine/index.yaml
- lib/osv/semver_index.py
Previously semver queries were only done if the ecosystem was specified
and was marked as semver.
Simplify this by doing the semver query anyway if the ecosystem isn't
specified.
> Simplify semver queries.

- docker/worker/oss_fuzz.py
- docker/worker/testdata/expected_127.diff
- docker/worker/worker_test.py
- lib/osv/impact.py
Change things such that we analyze with all known introduced/fixed
commits at the same time, rather than independently.
Analyzing git ranges independently results in false positives when we do
cherry pick analysis, which is why we disabled this previously.
Fixes #203.
> Re-enable branch/cherry pick analysis for incomplete ranges.

- vulnfeeds/vulns/vulns.go
Git ranges should always have an "introduced": "0" entry.
> vulnfeeds: Fix git range population.

- lib/osv/sources.py
This is to conform to the schema requirements and to to pass the
validator (https://github.com/ossf/osv-schema/pull/5) in all cases.
> Always output "versions" field even if it's empty.

- lib/osv/models.py
Just skip this for now, since 0.7 support will be removed very soon.
> Handle outputing 0.7 schema fields for unsupported ecosystems.

- vulnfeeds/pypi/pypi.go
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
> vulnfeeds: deduplicate pypi package matches when normalizing names

- gcp/appengine/.gcloudignore
- gcp/appengine/app.yaml
- Route /v2/ to the Python server.
- Add frontend3 to gcloudignore to avoid deploying a large number of
unnecessary files.
> Fix osv.dev deployment.

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
This PR introduces an initial pass at the package info UI on the v2 vulnerability page.
While `@material/mwc-tab-bar` and `@material/tab-bar` were considered, they were ultimately discarded:
- Close adherence to Material Design, which this design heavily diverges from, makes design adjustments more trouble than it's worth (e.g. compared to the search textbox implemented in #280).
- Lack of tab panel switching functionality means we would still need to DIY some JavaScript to switch panels anyway.
This PR proposes the tab UI is implemented by adopting [spicy-sections](https://github.com/tabvengers/spicy-sections), an *experimental* creation of the Open UI community group (hosted by the W3C [but run](https://www.w3.org/community/open-ui/) by the community), that is *not published on npm*. …
> Initial v2 package info UI

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
This PR introduces an initial "infinite load" (as opposed to "infinite scroll") implementation on the vulnerability table, replacing the previous placeholder pagination.
It does not attempt to fix other known issues with the table e.g. columns aren't complete, width goes out of bounds, etc.
This implementation adds no additional custom JS by taking advantage of `<turbo-frame>`, **part of the pre-existing dependency on Turbo**, which replaces only itself—and not the full page—with an updated version upon request load.
For example, the HTML in `/list?page=1` looks like the following:
```html
<turbo-frame id="vulnerability-page-1">
vuln 1
vuln 2
..
vuln n
<turbo-frame id="vulnerability-page-2">
<a href="/list?page=2">Load more</a>
</turbo-frame>
</turbo-frame>
```
Similarly, the HTML in …
> Initial v2 infinite load implementation

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
This PR gives functionality to the previously non-working search box, as well as adds a list of ecosystems underneath the searchbox that can be used to filter the results by ecosystem.
It also adds a blur effect when searches and filters are loading (if a full page load is not being performed).
It does not fix the known issue where a version not being set, which is common in many ecosystems including crates.io, NuGet, Go, etc., will cause the page to 500. This will be fixed in an upcoming PR.
Alas, with today's PR, the Dream of No Custom JS (apart from the code to init `@material/data-table`) has crumbled into pieces.
There are two things we add custom JS to address:
- Creating a new custom element to **wrap the `<mwc-textfield>` custom element**, and behave exactly the same, except to …
> Initial v2 search and ecosystem filtering UI

- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/home.html
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
This PR makes some visual tweaks to the home and list pages. (Preliminary work on homepage. Vulnerability list table has received border restyling. Last modified column has been added.)
This PR also makes some fixes to the list page. (Package names are now properly listed albeit with no character limit. Versions will display "See details" like v1 instead of 500ing the page if there are none available.)
> Tweaks for v2 home and list UI

- docker/worker/worker.py
- gcp/api/integration_tests.py
- gcp/functions/pypi/main.py
- gcp/functions/pypi/main_test.py
- gcp/functions/pypi/testdata/test_vuln.json
- lib/osv/models.py
- Set "withdrawn" vulnerabilities to invalid to prevent them from
surfacing in API results and UI.
- Handle sending "withdrawn" vulnerabilities to PyPI. Also improve
version aggregation while we're here.
Fixes #290.
> Properly support "withdrawn".

- docker/worker/worker.py
Otherwise we could have a race condition where we include versions that
may include the fix.
> Clear existing versions when adding OSS-Fuzz fix.

- vulnfeeds/pypi/pypi.go
They were incorrected encoded as pkg:pypi:PKG instead of pkg:pypi/PKG.
> vulnfeeds: Fix Python PURL generation.

- docker/worker/worker.py
- docker/worker/worker_test.py
Use the repo URL to key on if a fix commit needs to be added to a git
range.
> Make OSS-Fuzz FixResult setting more accurate.

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
This PR begins work on resolving the ultra-long width vulnerability table with various fixes, and includes some improvements:
- Packages are listed vertically instead of as one continuous string
- Affected versions are displayed in a two-column grid and limited to up-to-8 versions
- Last modified is now displayed as a relative date using GitHub's [`time-elements`](https://github.com/github/time-elements) web components
- "Fix available"/"No fix available" is now displayed
Screenshot:
> More tweaks for v2 list UI

- gcp/api/server.py
- gcp/appengine/index.yaml
Redefine composite indexes to rely on [zig zag merge](https://cloud.google.com/datastore/docs/concepts/optimize-indexes#index_merge_performance) for queries.
This results in `O(version + package)` indexes instead of
`O(version x package)` indexes per vulnerability.
Also fix a bug with querying by package+version on rare vulnerabilities
with multiple different packages.
Previously we were incorrectly returning matches if a query matches any
listed package and any listed version. Now we filter to make sure the
version actually matches the package.
Fixes #315.
> Reduce Datastore index fanout.

- lib/osv/ecosystems.py
- lib/osv/ecosystems_test.py
- lib/osv/impact.py
Only if the package no longer exists (and re-trying would not fix it).
Fixes #318.
> Allow vulnerabilities to have failed version expansions.

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
This PR performs some restyling and structural changes to the list page including resolving the >100% width table, adds vulnerability count display to the ecosystem buttons as well as fixing styling issues with them, and also restyles and changes the text on tabs in the vulnerability page.
**Known issues introduced:**
Clicking tabs in the vulnerability tab is now broken and requires clicking in the padding area, not the text. A potential cause has been identified, however creating and contributing a patch upstream to [spicy-sections](https://github.com/tabvengers/spicy-sections) may unfortunately be limited by https://opensource.google/documentation/reference/patching#forbidden.
**Screenshots:**
> Various v2 list and vulnerability page UI improvements

- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/templates/list.html
This happens when we start at a different page (e.g. the home page)
and navigate to the vulnerability list page.
This seems to be because the place where we were instantiating the
MDCDataTable (index.js) can be run in a context where the actual element
hasn't been loaded in if we're not on the right page. 
This causes the `mwc-textfield-with-enter` element to not be defined properly,
leading to the missing search box.
> Fix missing search box on vulnerability list.

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/package.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/home.html
- gcp/appengine/frontend_handlers.py
Adding the ecosystem coverage, code snippets, API link placeholder. Looks pretty broken for now, but let's land this and have a followup PR to clean it up.
Code snippet copy button is working, thanks to GitHub's `<clipboard-copy>` custom element. Adds 5KB to vendors.js.
> Initial v2 homepage primary components

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/home.html
- gcp/appengine/frontend_handlers.py
- gcp/appengine/main.py
- Implement ecosystems sizes. Use log scale for the circle sizes.
- Center text.
- Update some text.
Known issue: Making the page too wide will misalign some things on the ecosystem sizes list.
> v2 Home page improvements.

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
- Various wrapping fixes to make this render better on mobile.
- Make tab bar collapse on mobile, and when the package list is too
long.
- Render events properly.
- Add links to schema documentation.
- Work around spicy-sections bug.
> V2: Vulnerability details page fixes.

- gcp/appengine/frontend3/src/styles.scss
Addressing comment from https://github.com/google/osv/pull/378.
> v2: Use display: flex for .cta sections.

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
- Implement grouped versions (fixes #395).
- Set max width of vulnerability description to 1000px to
avoid overly wide text on wide screens.
- Align affected versions.
- Fix font for vulnerability package section headings
- Increase spacing between vulnerability details items.
Before: 
After:
> Improvements to vulnerability page.

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/home.html
You need to have a small enough screen width for the ecosystems to overflow, which is more likely on touch devices where the scrollbar isn't visually jarring and it's more obvious that cut-off items can be scrolled.
Also updated styling to more closely match mocks.
Fixes #387
> Allow ecosystem bubbles on homepage to overflow horizontally

- tools/osv-scanner/internal/osv/osv.go
Remove unused "log" package, as go run, etc. throws 'internal/osv/osv.go:6:2: imported and not used: "log"' error.
> Remove unused "log" package from osv.go

- gcp/appengine/frontend_handlers.py
- gcp/appengine/frontend_handlers_test.py
- Don't double-count for Debian.
- Don't include invalid entries in the count.
Fixes #471.
> Fix ecosystem counts.

- Pipfile
- Pipfile.lock
- docker/worker/Dockerfile
- gcp/api/Dockerfile
- gcp/api/deploy_backend
- gcp/appengine/deploy.sh
API: Use pipenv to install dependnecies rather than generating
requirements.
App Engine: Exclude the '-e ' dependency from the generated
requirements.txt
Also,
- Update the API server to use Python 3.8 to be consistent with other
environments.
- Unpin pygit2 in the root Pipfile.
> Fix App Engine and API deployment.

- docs/README.md
* mention missing dependency on `clang` when running `go install`
* add `@latest` which is required by `go install` to work correctly
> Update prerequisites based on my experiences

- docs/build.py
- docs/osv_service_v1.swagger.json
- osv/models.py
- osv/vulnerability.proto
- osv/vulnerability_pb2.py
Remove the previously deprecated top level `package` field from the
Vulnerability proto.
Fixes #542
> Update documentation and OpenAPI spec.

- gcp/appengine/frontend3/package-lock.json
- gcp/appengine/frontend3/src/index.js
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
- Remove ability to go to pages directly after refresh, as it causes confusing scenario
- Removes load more button if there are no more results.
- Add message indicating there are no results
- Add indicator of how many pages left if there are less than 3 pages left. (Probably can refactor that number to a config file or something)
Fixes: #468
> Fix issues with pages on vulnerability list page

- gcp/api/integration_tests.py
Tests are failing due to some test queries returning one new vulnerability. 
Update the relevant tests to account for that.
> Update integration tests.

- CONTRIBUTING.md
- Makefile
- gcp/api/test_server.py
Also:
- Add instructions to CONTRIBUTING.md for how to invoke the targets.
- Make the API test_server.py a bit more robust by killing existing
ESPv2 instances prior to starting.
- Rename the ESPv2 docker containers to something less generic to avoid potential
collisions.
> Add instructions for running UI and API servers locally.

- gcp/api/integration_tests.py
Don't compare the actual modified timestamp value, but ensure that it
still exists.
> Make integration tests for batch queries more resilient to changes.

- docs/architecture.md
* Link out to various GCP technologies to make it easier for the
unfamiliar to school themselves
* Consistently use and place reference-style links for better readability
> Enhance architecture documentation with additional links

- gcp/appengine/deploy.sh
Fix how the deploy script generates the requirements.txt file.
There's also another problem where pipenv is not actually specified as a devDependency in appengine, causing the script to fail if pipenv hasn't been installed inside this appengine environment specifically.
Because that will actually change the Pipfile.lock, I will put that #616 alongside other dependency changes
> Fix deploy script using deprecated method to generate requirement

- osv/ecosystems.py
- osv/ecosystems_test.py
Stop enumerating Debian end of life advisories, as they are quite rare (as of writing only 7 EOL advisory entries, and around 3 packages affected). If enumerated it is likely to cause false positives, since the EOL generally only affects the specific Debian release, not following releases.
> Stop enumerating debian end of life advisories

- cloudbuild.yaml
- osv/ecosystems.py
Cloud build testing should now exit and error on any tests failing. 
Also fix the issue breaking tests.
> Logging fixes 2

- gcp/appengine/frontend3/src/templates/about.html
"an" should only preceed words starting with a vowel.
> Fix grammatical error I noticed

- deployment/staging.yaml
- docker/ci/Dockerfile
- docker/deployment/Dockerfile
- gcp/api/run_tests.sh
- gcp/appengine/deploy-staging.sh
- gcp/appengine/deploy.sh
This will be triggered on every commit to master, after passing all tests.
Also:
- Update gcp/api/run_tests.sh to use `pipenv requirements` instead as `pipenv lock -r` is deprecated/removed.
- Add explicit Java dependency in CI image as latest gcloud datastore emulators seem to require (but not install)
this.
- Add `npm install` to App Engine deployment scripts.
- Add a new Docker image for deployment as the existing CI ones are too old. We need newer npm/nodejs for 
deployment.
> Add cloudbuild.yaml for deploying to staging. 

- docker/indexer/stages/processing/processing.go
- docker/indexer/storage/storage.go
We need the hashes themselves to be indexed so we can quickly guess by making submitting a subset of hashes.
Don't do this for file paths yet, as it's not clear if those are required, and it could cause issues with index sizes.
> indexer: Move noindex annotation.

- docker/indexer/storage/storage.go
This makes the encoding consistent with Python's ndb.StructuredProperty.
See https://pkg.go.dev/cloud.google.com/go/datastore#hdr-Structured_Properties.
> indexer: Flatten FileResults

- osv/packagist_version.py
- osv/testdata/packagist_test_cases.txt
Potentially fixes #701. Source code for stripping the v can be found here, 
https://github.com/composer/semver/blob/main/src/VersionParser.php#L137
it seems like they try to coerce the tag version into a semver version, which is different to how php's `version_compare` function is implemented. Both achieve the same results (mostly, except for edge cases like having a v to start the tag)
> Strip v from versions when enumerating

- osv/packagist_version.py
the `disable-next` directive seems to have changed its behaviour between pylint 2.15.0 and 2.15.2
> Really silence the linter for these long lines.

- osv/models.py
This should be a BlobProperty, not BlobKeyProperty.
Since this is in the Python model where writing isn't done, we don't have to migrate
any existing entities.
> RepoIndexResult: Fix type of hash.

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
Update the output to make it clearer to someone less familiar with GCP what is going on.
See #749
I think there's probably a little more needed, as nothing seems to be produced if there's no input successfully synced down (which there won't be with a new empty bucket).
> Make it easier for someone to override the GCS bucket used

- vulnfeeds/vulns/vulns.go
The NVD CVE output isn't going to have any package or version information, so these fields are unncessary noise in the output.
> Omit more empty fields from the Affected struct when exporting as JSON

- vulnfeeds/cves/cve.go
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
The lovely folks at the NVD are already giving us hints, so only resort to URL shape-based guesswork if we don't have a more explicit signal.
> Use the tags as the first port of call to infer the type of the link

- docker/importer/importer.py
- osv/repos.py
A shallow clone that only clones commits up to the previous synced date. This avoids having to clone the entire repository history when unneeded. A pull/fetch will only fetch future commits, without needing to fill up the entire history. 
A potential issue is if default branch changes to a completely different branch (not just renamed), this will mean potentially needing more history than what is available since the last sync time. This is very rare and I am not aware of any reason for doing this.
Fixes #576
> Git clone shallow to improve new importer instance performance

- docker/importer/importer.py
- docker/importer/importer_test.py
- osv/repos.py
pygit2 does not support shallow clones at the moment, causing an error when attempting to walk shallow clones. 
Also adds some minor logging improvements to provide better visibility of what is happening. 
This does also revert a bunch of helpful typing and documentation options. For now it might be better to leave them reverted, as it will make it much easier to reapply the shallow clone changes once support is added in pygit2.
> Revert git shallow clone

- docker/exporter/exporter.py
Fun finds:
* Local runtime environment (where I had manually tested efc3876) uses Python 3.10, whereas the GKE container is based of Ubuntu 20.04 and uses Python 3.8
* Python 3.8 dislikes `list[str]` as a type hint, but 3.10 does not.
* So everything is peachy with local testing, not so much in production
Moral of this story? Don't test locally :-/
> Forward-fix type hint issue

- deployment/staging.yaml
- gcp/appengine/.gcloudignore
When running tests it will pull down alpine repository into testdata folder, massively inflating file count beyond the 10000 file limit. This is not needed for appengine, so should be ignored.
> Fixes appengine releases by ignoring testdata

- docker/worker-base/Dockerfile
- docker/worker-base/build.sh
- docker/worker/Dockerfile
Update how gke docker images are arranged so that python compile, docker, and gvisor installs (which use a pinned version) are done in a base docker image that can be cached.
> Python, docker, gvisor, build caching

- osv/ecosystems.py
Since version history is tracked by git, it is really hard to correct for errors in a package's history, so if a version is not valid, it will likely still keep showing up when enumerating history for a package. Because of this, we will ignore all invalid versions when enumerating versions.
> Fix alpine enumeration

- tools/osv-scanner/README.md
- tools/osv-scanner/cmd/osv-scanner/main.go
As mentioned [here](https://github.com/google/osv.dev/pull/815#issuecomment-1311245059), I've made the default to be checking only the files in the target directories, as I think that is the better UX: generally easier to manage inclusion in userland (i.e. loops, globs, `tree`, etc) than exclusion (case and point, right now there is no way to exclude anything from the scanner).
I suspect it is probably going to be best to replace `filepath.Walk` with a recursive loop, at least if `recursive` is not passed because otherwise I believe you load the whole file tree into memory every time.
I have started writing some tests for this, but will do a seperate PR for that since it requires more unrelated work.
> feat: implement `--recursive` flag

- gcp/api/Dockerfile
- gcp/api/Pipfile
- gcp/api/Pipfile.lock
- gcp/api/run_tests.sh
- gcp/appengine/frontend3/package-lock.json
Revert package updates to avoid protobuf version mismatches.
The root cause was grpcio-tools, but this is a dev dependency so move it there instead to avoid issues with our production image build.
So, we move this package into the dev-packages section.
> Fix API dependency issues.

- docker/importer/importer.py
- docker/importer/importer_test.py
The supported way to handle making entries as invalid is to mark them as "withdrawn" and
leave the entry intact.
This also guards against availability issues from source feeds, such as when a bug in their
system causes their entries to be deleted (e.g. https://github.com/github/advisory-database/commit/06071dd8e490ed354657f8ee158880433cf04997)
> Don't mark deleted git entries as invalid.

- osv/ecosystems.py
Fix an occasional exception that's showing up when enumerating alpine versions because calling `.split()` on None
> Fix alpine enumeration bug

- gcp/api/integration_tests.py
- gcp/api/server.py
This didn't work properly if there are multiple packages/ranges in the relevant vulnerability, and the matching range
is not the last one.
This implementation now matches the OSV schema pseudocode at https://ossf.github.io/osv-schema/#evaluation.
Fixes #834.
> Fix bug with SemVer range evaluation in API.

- vulnfeeds/vulns/vulns.go
ecosystem-specific version ranges are only meaningful in conjuction with package information, so only add them to the resulting vulnerability record if package information is present.
Break out the Package to its own struct so it doesn't get emitted when there is no package information.
Adjust AddPkgInfo accordingly
> Only add an ecosystem version range if there's package information

- vulnfeeds/cves/versions.go
Storing the CPEs in an intermediate map was redundant and destroyed the ordering of them.
> Make CPEs() deterministic

- vulnfeeds/cmd/cperepos/main.go
Rather than have the first seen repository win and others get ignored, leave it to the consumer of the resulting data to decide what they want to do.
e.g.
```
jq . | to_entries | map(select(.value | length > 1)) | from_entries
jq . | to_entries | map(select(.value | length == 1)) | from_entries
```
Also identified another definitely invalid repository for the regex
> Handle scenarios where a product has differing repository values

- vulnfeeds/cmd/cperepos/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
References to cgit.freedesktop.org have been discovered in the wild, and this is doesn't quite walk and talk like other cGit webservers. Furthermore, it's a mirror of gitlab.freedesktop.org, so canonicalise to this in case callers want to clone the repo returned
> Handle the special case of cgit.freedesktop.org

- vulnfeeds/cmd/cperepos/README.md
- vulnfeeds/cmd/cperepos/main.go
- vulnfeeds/cpp/README.md
- vulnfeeds/cpp/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/utility/utility.go
* Remove redundant code from PoC NVD to OSV converter
* Move repository inference functionality over to CPE Dictionary parser
* Cover an edge case where bare repository URLs have a trailing slash
> Move repo detection to CPE dictionary parser

- gcp/appengine/frontend_handlers.py
This removes the UVI and GSD ecosystem entries on the vulnerabilities list. They still show up in the ecosystem list because there are entries that are marked as invalid.
We would require adding an additional index to have the `osv_get_ecosystems` function return only ecosystems with non invalid bugs.
> Add filter for ecosystem count

- deployment/staging.yaml
- deployment/terraform/modules/osv/main.tf
- gcp/appengine/deploy.sh
- Set up App Engine instance.
- Set up Cloud Redis instances.
- Set up VPC connector.
- Add App Engine default IAM permissions.
- Make App Engine deploy script take in a project ID rather than hardcoding "oss-vdb".
TODO:
- Make App Engine deployment work by sharing a base app.yaml.
The test instance is running at https://oss-vdb-test.wl.r.appspot.com/ now by deploying a manually edited (and uncommitted) app.yaml.
> Start terraform set up for App Engine.

- osv/ecosystems.py
- osv/ecosystems_test.py
The `last_affected` value was not being propagated properly in the deps.dev path. This only affects Maven OSV entries with `last_affected` specified.
Fixes #908.
> Fix `last_affected` enumeration for deps.dev

- vulnfeeds/cmd/cperepos/main.go
I realised I'd been using this exclusively with the flag until today when I wasn't, and had the default filename wrong.
> Fix the default CPE Dictionary filename

- gcp/appengine/frontend3/src/templates/about.html
- gcp/appengine/frontend3/src/templates/home.html
- Add "CLI Tools" button to home page to scroll down to the relevant section. (Similar to "Use the API").
- Remove the $GOPATH/bin prefix to match https://github.com/google/osv-scanner/pull/77.
- Tweak wording for OSV-Scanner section on "About" page
> UI tweaks.

- gcp/api/integration_tests.py
The current state of https://github.com/advisories/GHSA-hrm3-3xm6-x33h breaks the test, so use a
different package altogether. Adjust for test scenarios accordingly.
> Fix semver integration test

- docker/exporter/Pipfile.lock
- docker/worker/Pipfile.lock
https://github.com/google/osv.dev/pull/893
and
https://github.com/google/osv.dev/pull/895
are trying to update certifi to fix a security vulnerability, but it's running into problems with protobuf and seems to be downgrading google-cloud-datastore no good reason.
I temporarily added certifi to Pipfile and ran "pipenv update certifi" to generate these Pipfile.lock changes
> Dependabot is doing weird stuff updating certifi, let's DIY

- gcp/appengine/frontend_handlers.py
https://osv.dev/VULN-ID would redirect to
https://osv.dev/vulnerability/VULN-ID, if VULN-ID exists.
Fixes #930.
> Create short redirect link format for vulnerabilities.

- vulnfeeds/cmd/cperepos/main.go
GitLab seems to have a variety of repos derived. Some redirect to others (separately, the Golang git repo cloning code seems to be hanging on redirects, which is a separate issue to resolve). This leaves only the "real" repo being detected, which is
https://gitlab.com/gitlab-org/gitlab
> Add false-positive repo matches for GitLab

- deployment/oss-vdb-test/k8s/deploy.sh
- docker/exporter/Pipfile.lock
- docker/worker/Pipfile.lock
Updates pipenv.lock, for some reason the pipenv.lock was considered out of date, maybe we need to restrict the versions on our pipenv files more to avoid this in the future. 
Also updates deploy script to not check origin/master, but the remote `github.com/google/osv.dev` specifically, this is required because the upstream remote might be named differently from `origin` (e.g. I name my fork `origin`, and the main repo `upstream` instead).
And fix issue with date checks where bash assumes it's consuming hex number instead of decimal number because of the leading 0.
> Update deployment script and pipenv.lock

- osv/ecosystems_test.py
- run_tests.sh
This matches production behaviour.
Avoid leaking the API key for deps.dev in test output.
This is an interim measure to address Maven flakiness causing intermittent test failures and won't work when we move tests over to GitHub Workflows. The ultimate solution is to make the tests hermetic and mock out the network dependencies.
> Make the Maven tests use deps.dev

- deployment/oss-vdb-test/k8s/cloudbuild.yaml
- deployment/oss-vdb-test/k8s/gke/alpine-cve-convert/alpine-cve-convert.yaml
- deployment/oss-vdb-test/k8s/gke/combine-to-osv/combine-to-osv.yaml
- deployment/terraform/environments/oss-vdb-test/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/variables.tf
- vulnfeeds/cmd/alpine/run_alpine_convert.sh
Adds the cve conversion release configs and process into the cloudbuild for the test environment, also sets up the cloud bucket in terraform.
> Add cve conversion and alpine k8s tasks to osv-vdb-test

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/modules/osv/osv_api.tf
- deployment/terraform/modules/osv/variables.tf
Adds a Terraform variable to set the API frontend base ESP image version.
Stops Terraform trying to recreate the image whenever there's a new version available.
> Explicitly set API ESP version in Terraform

- deployment/oss-vdb-test/k8s/cloudbuild.yaml
Docker images weren't being pushed to registry, and tasks were using the worker image
> Fix oss-vdb-test Cloud Build steps for cve conversion & alpine tasks

- osv/semver_index_test.py
- run_tests.sh
`semver_index_test` was not in `run_tests.sh`.
A change from a while ago also seems to have broken the test, which hadn't been picked up.
> Fix semver_index_test not being run

- renovate.json
This way the release engineer of the week can focus on getting the release out on Monday, and then get any dependency PRs merged through the latter half of the week in time for the following Monday's release.
> Update dependencies mid-week

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yaml
Support running workflows when merge queue is switched on. Cloud build doesn't seem to support merge groups yet though, so have to merge #971 before enabling merge queues again.
> Trigger workflow on merge group

- osv/ecosystems/maven.py
- osv/ecosystems/maven_test.py
Fixes #1020 
This should also fix some of the missing vulnerabilities in #1018 on reimport:
- GHSA-v62j-cxhh-fq22
- GHSA-g2qw-6vrr-v6pq
- GHSA-789v-h9hw-38pg
> Fix Maven handling of version 0

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
This is slightly horrible due to RE2's lack of support for lookarounds (negative lookbehind assertions in this instance). The most pragmatic approach I could come up with is to sanity check the results. Thank goodness for existing comprehensive test cases.
> Reproduce the existing normalization functionality from osv/bugs.py

- vulnfeeds/vulns/vulns.go
We will be relying on this for records generated from CVEs where the vulnerability is not fixed.
> Add the OSV Schema's `last_affected` field to the Event struct

- docker/worker-base/Dockerfile
20.10.23 was still broken. I verified on GKE that 20.10.22 does indeed work.
Part of #1019
> Downgrade Docker a bit more.

- docker/worker-base/Dockerfile
This prevents them from getting upgraded when a later child image does `apt-get upgrade`.
> Hold docker-ce, docker-ce-cli packages in worker-base.

- vulnfeeds/cves/versions.go
* only emit something when we've got something useful to emit
* prefix with the CVE that was in scope for better utility
> Improve signal to noise ratio of this log output from ExtractVersionInfo

- docker/exporter/exporter.py
This fixes #1007 by also exporting "withdrawn" bugs, i.e. ones with status INVALID.
> Only skip exporting bugs that have an UNPROCESSED status

- deployment/build-and-stage.yaml
- deployment/oss-vdb-test/k8s/cloudbuild.yaml
- deployment/oss-vdb-test/k8s/gke/exporter/exporter.yaml
- deployment/oss-vdb-test/k8s/gke/importer/importer.yaml
- deployment/oss-vdb-test/k8s/gke/workers/workers.yaml
- docker/exporter/Dockerfile
- docker/exporter/build.sh
- docker/importer/Dockerfile
- docker/importer/build.sh
- docker/worker-base/build.sh
- docker/worker/Dockerfile
- docker/worker/build.sh
- gcp/api/deploy_backend
- Point the staging environments deployments to images in `oss-vdb`.
- Automatically build GKE and API backend images on push to master
- Modify GKE worker deployment for `oss-vdb-test` to no longer build images
- Deployment to `oss-vdb` is currently unchanged - images are still rebuilt on deployment
- Parallelized `build_and_stage.yaml` docker image building to make it faster
- Added a check in `build_and_stage.yaml` to make sure triggers don't happen out-of-order if the Cloud Build is triggered multiple times close together
> Consolidate staging & production docker registry and build images on push to master.

- README.md
Add a more explicit call out to the existence of ecosystems.txt in the export GCS bucket to aid in downloading all of the per-ecosystem `all.zip` files more efficiently.
Surfaced by #1054
> Explicitly call out ecosystems.txt

- setup.py
This is required to update downstream consumers
(such as https://github.com/google/osv.dev/tree/master/gcp/functions/pypi) to uptake recent schema changes.
> Bump PyPI package version.

- README.md
The previous link went to the docs, with the faq tag. But nothing is tagged as faq in the docs. I updated the link to the osv.dev about page, which is presented as an faq.
> Updated bad link.

- gcp/api/deploy_backend
We will need to remember to do this for our Cloud Deploy setup as well. Terraform cannot manage this as this is part of the [ignored changes](https://github.com/google/osv.dev/blob/932929f0f31584734b94339ea9cacf3158fd9bed/deployment/terraform/modules/osv/osv_api.tf#L18)
We are seeing some occasional OOM issues -- this bump should hopefully resolve that.
> Bump memory for backend API instances.

- docker/exporter/exporter.py
- vulnfeeds/git/repository.go
- vulnfeeds/git/repository_test.go
This will facilitate exact and fuzzy matches on CPE versions in CVE records.
> Populate a per-repository map of normalized version tags

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/git/repository.go
It's in the cves package, and just happens to be in a file named versions, but it's not so obvious outside of the package that it's for normalizing versions when it's just called Normalize
> Make it clearer that Normalize is for versions

- vulnfeeds/git/repository_test.go
The live remote Git repos need to be replaced with fakes.
> Fix brittle test with external dependencies

- deployment/gae/oss-vdb-test/app.yaml
- deployment/gae/oss-vdb-test/cron-service.yaml
- deployment/gae/oss-vdb/app.yaml
- deployment/gae/oss-vdb/cron-service.yaml
- deployment/gae/oss-vdb/testing-app.yaml
- deployment/terraform/modules/osv/main.tf
Make a new Redis resource for the frontend because Terraform can't reproduce the one on production.
To not break the existing website & allow for rollbacks, the old one will stay around for about a month.
I've already run `terraform apply` on production and staging to generate the IPs, so no changes will appear in the plan check.
> Fix Terraform Redis Issues

- vulnfeeds/cpp/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/vulns/vulns.go
Also expand AttachExtractedVersionInfo to support these fields.
This way we can generate OSV records containing Limit or LastAffected if Fixed cannot be determined.
> Expand the VersionInfo struct to support Limit and LastAffected

- osv/ecosystems/maven_test.py
@G-Rath found this case was failing in google/osv-scanner#279.
OSV.dev didn't need any fixes, but adding these tests to be safe.
> Add Maven version tests for leading 0's

- tools/datafix/delete_invalid.py
- tools/datafix/withdraw_invalid.py
It turns out there's a maximum of 500 updates per transaction, so break
it into appropriately sized batches.
Also add verbosity so the records being acted on can be inspected
easily.
For #1098
> Batch operations

- deployment/deploy-prod.yaml
Cloud Deploy doesn't automatically know where to promote a release if it's not currently deployed on staging (i.e. if it's not the most recent commit).
Explicitly telling which target to deploy to should fix this.
> Add `--to-target` flag to Cloud Deploy promotion

- docker/worker/oss_fuzz.py
- docker/worker/worker.py
Some of the OSS-Fuzz errors are bisection errors that we do expect (and is not the fault of the OSV infrastructure).
Note this does not address some problematic error logging that lives in code in the OSS-Fuzz repo that we import.
> Downgrade some error logs to warnings.

- docker/worker/worker.py
- docker/worker/worker_test.py
- gcp/appengine/handlers.py
- gcp/appengine/index.yaml
- osv/impact.py
- osv/impact_test.py
- osv/models.py
> Completely remove old AffectedCommit code.

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/test_data/nvdcve-1.1-test-data.json
This adds some preliminary test coverage to `ExtractVersionInfo` and avoids adding duplicates  to`AffectedVersion`, preventing duplicate commit hashes getting added further downstream when they are mapped.
This highlights the potential need to look more holistically at the nodes when extracting versions, because each one could be for a completely different CPE...
> Deduplicate affected versions

- vulnfeeds/cpp/main.go
This way we have all the necessary information available in a single log line.
> Include the repo that was consulted in failure logs

- gcp/api/integration_tests.py
`test_query_semver_multiple_package` was failing because the query for
version 2.4.0 of github.com/go-yaml/yaml Go is now returning
https://github.com/advisories/GHSA-r88r-gmrh-7j83 and https://github.com/advisories/GHSA-wxc4-f4m6-wwqv in addition to GO-2020-0036
and GO-2021-0061
Remove the length test for what the API returns, as it is less detailed
and made redundant by the following `assertCountEqual` test.
> Fix API integration tests

- vulnfeeds/cmd/cperepos/main.go
These jumped out at me from eyeballing failed version to commit resolution.
> Exclude more repositories that are not canonical sources of OSS

- deployment/clouddeploy/gke-workers/base/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/base/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/kustomization.yaml
- deployment/deploy-prod.yaml
This is my first attempt at setting up all the additional plumbing for the Debian copyright metadata mirroring.
The objective is to get this up and going in the staging environment, prior to a release getting it going in the production environment.
> Productionizing Debian copyright metadata mirroring

- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-copyright-mirror.yaml
When setting up the other cron job I realised I had the production bucket name wrong.
> Use correct production bucket name

- deployment/clouddeploy/gke-workers/base/gen-cperepos-map.yaml
- deployment/clouddeploy/gke-workers/base/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/gen-cperepos-map.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/gen-cperepos-map.yaml
- deployment/deploy-prod.yaml
Set up all the additional plumbing for the CPE repo map generation.
The objective is to get this up and going in the staging environment, prior to a release getting it going in the production environment.
> Initial commit of productionization of gen-cperepos-map

- vulnfeeds/cmd/cperepos/main.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
Interim move to allow the denylisting to be used more broadly by baking it into the repository URL extraction and normalization function.
Added benefit, better testing.
Unexpected bonus of that: discovered repositories hosting their own GHSA's were being incorrectly ruled out of scope, so that's a bit of a win...
> Refactor repo denylisting for reuse

- vulnfeeds/cmd/cperepos/Dockerfile
- vulnfeeds/cmd/cperepos/gen_cperepos_map
1. The runtime image has a busybox gzip that doesn't support the more descriptive long-form flag names. Oh well. I tried.
2. The intermediate image used to build the cperepos Go binary appears to dynamically link against glibc, which isn't present in the runtime image. Built it static link it instead.
> Fix a couple of issues with containerizing cperepos

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/gen-cperepos-map.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/gen-cperepos-map.yaml
Somehow the first line of these got lost in all the copy pasta, and I'm sure that is contributing to some unexpected behaviour with respect to inherited environment variables.
> Fix up YAML files

- deployment/terraform/modules/osv/workers_gke.tf
Each indexer pod needs a lot more memory than it needs CPUs. The current standard-32 leaves about 22 cores completely unused because there's not enough memory available to spin up more pods on each node.
> Update highend node type to much better fit indexer behavior

- deployment/terraform/modules/osv/workers_gke.tf
Works when running apply locally.
> Remove local_ssd_count, and convert to ssd

- vulnfeeds/cmd/debian-copyright-mirror/debian-copyright-mirror
This was resulting in paths like
`osv-test-cve-osv-conversion/debian_copyright/debian_copyright/metadata.ftp-master.debian.org` which is unnecessarily deep and doesn't match expectations on the consumption side.
> Remove duplicate embedded directory name

- deployment/build-and-stage.yaml
- gcp/appengine/cleanup_versions.sh
Add a build stage that executes a new script that cleans up all but the last 5 App Engine versions.
> Automate cleaning up excessive App Engine versions

- gcp/appengine/cleanup_versions.sh
With the increase to 106 versions, it's totally conceivable there won't be any versions to delete, so do it conditionally
> Handle not having any versions to remove

- vulnfeeds/cmd/cperepos/gen_cperepos_map
I think I got too overzealous with rsync `-d`'s and this is unintentionally (by me) wiping out the CPE Dictionary XML file that is also copied to `$WORK_DIR`, from looking at the logs.
> Fix cperepos map generation

- deployment/terraform/modules/osv/workers_gke.tf
Add local ssd entries to the disk, minimum is 4. Each disk is 375 gb for 1.5tb of local storage per node.
This should fix the out of disk space errors.
It seems like by default if there are local ssd's attached, then emptyDir uses the local ssds. It's really hard to find solid documentation on this though.
> Update local ssd entry again

- deployment/terraform/modules/osv/main.tf
> Delete old, unused redis instance

- deployment/clouddeploy/gke-workers/base/importer.yaml
- deployment/terraform/modules/osv/workers_gke.tf
Update highend for actual ephemeral storage, and importer pool for taint to stop other services crowding out the importer from running.
> Highend and importer pool terraform update

- gcp/appengine/blog/content/posts/announcing-osv-service-level-objectives.md
Quick update of the SLO blog post to reflect the new docs page. 
For some reason, the ordered list is not rendering in the blog, so I adjusted that slightly too.
> Update FAQ link in blog post

- deployment/deploy-prod.yaml
My previous change to this file seems to have been botched by the looks of it...
Fixes:
```
/usr/bin/../lib/google-cloud-sdk/lib/third_party/ruamel/yaml/constructor.py:283: DuplicateKeyFutureWarning: while constructing a mapping
in "deploy-prod.yaml", line 41, column 3
found duplicate key "args" with value "[]" (original value: "[]")
in "deploy-prod.yaml", line 43, column 3
To suppress this check see:
http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
warnings.warn(DuplicateKeyFutureWarning(*args))
Created [https://cloudbuild.googleapis.com/v1/projects/oss-vdb/locations/global/builds/603e0a12-c9d2-466b-b465-80abd8b6b99f].
Logs are available at [ …
```
> Fix incorrect YAML

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/gen-cperepos-map.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/gen-cperepos-map.yaml
- vulnfeeds/cmd/cperepos/README.md
- vulnfeeds/cmd/cperepos/gen_cperepos_map
- vulnfeeds/cmd/debian-copyright-mirror/debian-copyright-mirror
rsyncing > 100K files from GCS on a single-core node was proving very slow, so use a tarball instead.
I also picked up an error in the documentation, which had been transposed into the code, so the desired file wasn't even being retained :-(
> Reduce file transfers to speed up runtime

- deployment/clouddeploy/gke-workers/base/gen-cperepos-map.yaml
It seems to be OOMing (but not in ways that result in an overall container early termination)
> Increase RAM for this pod

- Pipfile
- docker/exporter/Pipfile.lock
- docker/worker/Pipfile.lock
- gcp/api/Pipfile.lock
- gcp/functions/pypi/Pipfile
- osv/semver_index.py
- osv/semver_index_test.py
- setup.py
semver 3.0.0 breakingly renamed `VersionInfo.isvalid` to `Version.is_valid`.
> Upgrade semver to >=3.0.0

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/alpine-cve-convert.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/debian-convert.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/debian-first-version.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/gen-cperepos-map.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/alpine-cve-convert.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-convert.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-first-version.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/gen-cperepos-map.yaml
- vulnfeeds/cmd/alpine/main.go
- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/download-cves/main.go
- vulnfeeds/utility/logginghelpers.go
Change logging target for vulnfeeds depending on what environment it's running in.
This changes:
- alpine
- cve-downloader
- combine-to-osv
to get their project from the environment instead of hard coding. (Added a extra utility function to create the Logger wrapper and retrieve the project from the env).
This does not change cperepos to avoid merge conflicts.
Then changes almost all of the yaml configs to include the GOOGLE_CLOUD_PROJECT environment variable (this includes the cperepos yaml files, can undo that if it causes merge conflicts @andrewpollock )
Also fixes alpine converter not using the logger wrapper for invalid versions.
> Change logging target for vulnfeeds to be dynamic

- osv/ecosystems/_ecosystems.py
Add `AlmaLinux`, `Rocky Linux`, and `ConanCenter` to the supported ecosystems list.
Currently, these all are using the `OrderingUnsupportedEcosystem`, which should suffice for importing. I'll work on their own ecosystem helpers in another PR.
> Add newly supported ecosystems

- vulnfeeds/cpp/main.go
Instigated by CVE-2022-1664, which is ostensibly for dpkg (debian:dpkg) but netapp:ontap_select_deploy_administration_utility also uses dpkg, so the dpkg source repo gets (incorrectly) attributed to this CPE as well.
That then flows onto future CVEs that reference the netapp software (plus other CPEs) cross-contaminating them with the incorrect repo. This is one (rare) scenario where reusing precomputed repos for CPEs causes a domino effect of incorrect associations in later CVEs.
> Add a denylist for known non-OSS that is also known problematic

- Pipfile
- Pipfile.lock
- docker/worker/Pipfile.lock
- setup.py
https://github.com/pypa/packaging/issues/321 removed support for parsing legacy PyPI versions, which we needed to make our version enumeration/sorting work.
This upgrade happened in
https://github.com/google/osv.dev/commit/f96826094d1c2d766d4949c70cf2b9aae7ff45f3, but somehow we didn't notice this breakage.
> Downgrade packaging.

- gcp/api/integration_tests.py
Our integration tests broke because of this: https://osv.dev/vulnerability/GO-2023-1737, which is an unfixed vulnerability that was just published on Friday, and we have a test that's expecting no vulnerabilities.
Moved that test to a separate simple package that only ever had 1 vuln in 2020, so it's less likely to break in the future.
> Fix integration tests

- gcp/api/server.py
Python treats a SIGINT as a KeyboardInterrupt exception by default, so in the event of the container getting a SIGINT in production, log this explicitly.
> Add some additional instrumentation for troubleshooting

- gcp/api/server.py
Added the quick fail for Kernel queries, and tried matching the ndb query timeout with the GRPC time_remaining function. Added a log to check if that function does what I think it does and matches what we set in cloud run. 
Also added a bunch of type hints just to make development more efficient.
> Add typing, add timeout, add kernel quick fail

- deployment/clouddeploy/osv-api/run.yaml
- deployment/terraform/environments/oss-vdb-test/api/api_config.tftpl
- Set `timeoutSeconds` to 60, instead of the default 300, for the backend api to match what is on the frontend
- Also set the staging instance's frontend timeout to 60 to match prod
- Reduce the backend's `containerConcurrency` to 20 (from default 80). This is 2x the number of threads in the thread pool for the server. May reduce further in future.
> Make api backend timeout match frontend, reduce container concurrency

- gcp/api/server.py
- vulnfeeds/git/repository_test.go
Remove the deprecated default option and pass it in directly.
By filling out default options, every query now prints a warning log because of this line in the implementation code:
if default_options is not None:
_log.warning(
"Deprecation warning: passing default_options to the Query"
"constructor is deprecated. Please directly pass any "
"arguments you want to use to the Query constructor or its "
"methods."
)
https://github.com/googleapis/python-ndb/blob/a3a181a427cc292882691d963b30bc78c05c6592/google/cloud/ndb/query.py#L1339
Though looking at the git blame has been "deprecated" since 4 years ago in version v0.0.1
> Fix timeout argument

- osv/repos.py
Reasoning:
* it gets retried, so a first (or second) failure + successful reattempt is just noise
Reduces non-actionable instances of the likes of:
```
Clone failed: Command '['git', 'clone', 'https://github.com/github/advisory-database.git', '/work/sources/ghsa']' returned non-zero exit status 128.
```
in the error logs.
> Only log the clone failure on the final attempt

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/base_nvd-cve-osv.yaml
Looks like env vars need to be strings in kubernetes manifests.
Used parentheses instead of quotes since `IN_SCOPE_YEARS` is meant to be an array.
> Fix IN_SCOPE_YEARS in nvd-cve-osv

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
This seemed to go through verbatim with parenthesis, when what's going to be needed is a quoted string, as it'll wind up being multiple space-separated values.
Saw a log run like this, which was not what's intended:
```
Commencing conversion run
Downloading NVD CVE dumps
Downloading latest CPE Git repository map
Converting NVD CVE records from (2022) to OSV
Copying NVD CVE records from (2022) successfully converted to OSV to GCS
find: /tmp/nvd2osv/(2022): No such file or directory
CommandException: No URLs matched. Do the files you're operating on exist?
CommandException: No URLs matched: /tmp/nvd2osv/(2022)/outcomes.csv
Results summary available at gs://osv-test-cve-osv-conversion/nvd-poc/nvd-conversion-outcomes-(2022)-2023-05-23T06:01+00:00.csv
Conversion run complete
```
> Try and fix handling of environment variable

- .github/workflows/scorecards.yml
Newest version (2.3.4) does allow scorecard's "no file" URI to be parsed correctly https://github.com/ossf/scorecard/issues/3063
Also, the version comment was pretty outdated.
> Fix scorecard action by pinning `github/codeql-action` to 2.3.3

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/base_nvd-cve-osv.yaml
Add more signposting that copies are in existence until this has been validated successfully in staging.
> Symlinks didn't work, go back to direct copies

- vulnfeeds/utility/logginghelpers.go
When GOOGLE_CLOUD_PROJECT env variable is not passed in, we fall back to stdout logging rather than exiting.
> Fallback log to stdout for vulnfeeds

- docker/worker-base/Dockerfile
Need to do this before #1338 (which enforces Python 3.11.1) because the PR test runner image `gcr.io/oss-vdb/ci` uses the worker image.
`gcr.io/oss-vdb/ci` should probably be automatically rebuilt for PRs if the worker image changes...
> Update `worker-base` image to Python 3.11.1

- tools/indexer-api-caller/caller.go
This adds a convenience flag to scan all the (top level) subdirectories within a given directory.
> index-api-caller: Add a "-dir" flag.

- .github/workflows/lint.yaml
- CONTRIBUTING.md
- Pipfile
- Pipfile.lock
- docker/worker-base/Dockerfile
- docker/worker/Pipfile
- docker/worker/Pipfile.lock
- gcp/api/Dockerfile
- gcp/api/Pipfile
- gcp/api/Pipfile.lock
- gcp/appengine/Pipfile
Since our local environments have now just upgraded Python 3.11.2, our Pipfiles need to be changed. Having the patch version pinned makes maintaining/upgrading everything difficult, so I've just unpinned them.
This should mean that dependabot/renovate-bot will use the latest version, 3.11.3 when checking updates, so I've bumped our worker-base to 3.11.3 also.
We have a transient dependency, `async-timeout` that has the marker `python_full_version <= '3.11.2'`:
https://github.com/google/osv.dev/blob/e756517994e3f250c5426e765a1287608b4e6174/Pipfile.lock#L19-L25
[It's brought in by `redis` and it's just removed and replaced by anything in for Python 3.11.3](https://github.com/redis/redis-py/blob/d95d8a24ed2af3eae80b7b0f14cbccc9dbe86e96/setup.py#L37).
This shouldn't impact us locally if …
> Unpin Python patch version

- vulnfeeds/cmd/cperepos/main.go
These are incorrectly getting a repository associated with them via Debian copyright metadata.
> Add a denylist for generically named and/or known non-OSS

- gcp/api/server.py
- Improve performance of affected commits queries by making it keys_only.
- Adds logging to  package queries that don't have ecosystems.
> Improve performance of affectedcommits 

- README.md
- docs/third-party.md
The link checker caught another dead link. The previously linked go package was recently deprecated and is no longer available. 
If we wanted to, we could replace this link with a link to the [Go vuln database](https://go.dev/security/vuln/database) but I don't think that is the intention of this section. I am inclined to just delete the link.
> Remove unavailable package

- vulnfeeds/tools/debian/debian_converter/convert_debian.py
Debian advisories' CVE lines lists multiple CVE's that's fixed by the new version. This is not what aliases field is used for, and is better suited to the related field. 
This will have the consequence of not being able to search by the CVE on the osv.dev website to find the DSAs, since only aliases are currently placed in the search_indices, not related. Created #1380 to track this.
> Change aliases for debian to related instead

- .github/workflows/link-checker-on-push.yml
- .github/workflows/link-checker.yml
I have adjusted this so it runs once daily. 
It also runs on pushes, but only scans any files that have been modified. Failures on push should not prevent merging, but we can remove this in the case it does. 
If the link checker finds something when you push, you can either address it in your pull request, or you can open an issue and I will fix it.
> Adjusted link checker to run as cron

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/variables.tf
The other week I enabled GCS bucket access logging directly, without reflecting it in Terraform (I think I even did it incorrectly, the logging bucket specified was in my own project).
Also add the logs bucket itself
> Reflect GCS bucket access logging changes in Terraform

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/worker/worker.py
- vulnfeeds/git/repository_test.go
Add a new timestamp attribute to pubsub messages emitted by the importer
Then this attribute is present, have the worker log how much time passed between when the messages were published and when the tasks were completed.
This will allow for a log based metric to measure how long things are taking, notably when it comes to importing, for SLO measurement.
> Add a log message for a task's latency

- docs/_sass/color_schemes/better_contrast.scss
I think there was an update to our jekyll theme and it no longer accepts "px" units in the css. So I removed a line so it can build.
> Fix broken GitHub page

- docker/indexer/Dockerfile
The last few builds/deployments of the indexer have been spitting out errors:
```
/indexer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /indexer)
/indexer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /indexer)
```
Set `CGO_ENABLED=0` in the builder image to stop it dynamically linking these libraries that don't seem to be available in the distroless image.
> Statically link libraries in indexer image

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/worker/worker.py
Renames `timestamp` attribute in the pub/sub message used for logging to `req_timestamp`.
OSS-Fuzz also uses the timestamp attribute in the Pub/Sub message, with a different format and meaning. This clashes with the timestamp info added to help logging.
> Timestamp error fixes

- vulnfeeds/utility/logginghelpers.go
LoggingHelper already had the functionality to redirect to stdout (when cloud logger is nil), so undo the JSON redirect and set the gcloud logger to nil instead.
> Better logging redirection

- deployment/clouddeploy/osv-api/run.yaml
The default setting uses TCP, which could potentially report the instance is available before the grpc server is actually ready.
> Make API backend startupProbe use grpc

- osv/impact.py
This is to help with troubleshooting why converted CVEs aren't successfully having their commits converted back to versions.
Also add type hints
> Include the remote repository URL in some of the impact assessment code

- docker/worker/worker.py
Fall back to using `source` when it is not set
> The importer sets `source_id` selectively

- gcp/api/Pipfile.lock
- gcp/api/integration_tests.py
- gcp/api/run_tests.sh
- gcp/api/server.py
- gcp/api/server_test.py
Main functional change in this PR is making `arch=source` to mean `arch=<anything>`, since a source vulnerability will affect all architectures. 
Fixes a problem discussed here: #1321 
Did a bit of refactoring to do this:
- Moved the PURL matching logic around so that PURLs are not cleaned when passed around, but only cleaned when matching specifically with the datastore. 
- Also added the same additional matching step of `_match_purl` to `query_package` that's being used in `query_version`. 
- Updated `_match_purl` to consider `arch=source` to mean `arch=<anything>`.
> Refactor and update PURL matching in the API

- docs/api/index.md
When reviewing the docs for pagination, I realized there was another place where we could add something about the determineversion API. 
[Preview available here](https://hayleycd.github.io/osv.dev/api/)
> Adding determineversion info to the API index page

- docs/api/post-v1-determineversion.md
- tools/indexer-api-caller/README.md
Added instructions on how to use the API indexer tool to version multiple libraries at once. 
[Preview available](https://hayleycd.github.io/osv.dev/post-v1-determineversion/#try-the-api-with-our-tool)
> Adding information for versioning multiple libraries.

- docker/worker-base/Dockerfile
Noticed my Cloud Top is now using Python 3.11.4.
I think there should be a way to get dependabot/rennovate to make these PRs.
Alternatively, we could change the base image so we don't need to build python from source.
note: The ci image that runs our tests needs to be manually deployed but is based on the worker image, so it can only really be rebuilt after this is merged...
> Bump worker-base to Python 3.11.4

- gcp/appengine/frontend3/src/templates/list.html
This aligns table headers on the /list page:
> Fix header column

- osv/ecosystems/_ecosystems.py
- osv/ecosystems/haskell.py
- osv/ecosystems/haskell_test.py
Add version enumeration for the Haskell ecosystems: Hackage (the main package index) and GHC (the toolchain).
Fixes: https://github.com/google/osv.dev/issues/1418
> Hackage and GHC version enumeration (#1418)

- docker/ci/build.sh
- docker/deployment/Dockerfile
- docker/deployment/build.sh
- gcp/appengine/frontend3/package-lock.json
Add --pull to the new build scripts, and pin pipenv version to 2023.6.12 for the deployment image.
Also remove ^ from package-lock that  was missed in the previous PR.
> We've pinned pipenv because pipenv requirements was behaving differently on the most recent version, and we were matching on the output to remove the requirement from the App Engine deployment:
> 
> in 2023.6.12 the output for the editable osv package was
> 
> -e ./../..
> in 2023.7.23 it was
> 
> ../../
This does not seem to be an intentional change from pipenv, as it's not logged in the patch notes, but from bugs in their new implementation of the requirements: https://github.com/pypa/pipenv/pull/5757, so this might change back in the future versions.
> Add --pull to the new build scripts, and pin pipenv version to 2023.6.12

- renovate.json
Dependabot often has updates that don't show up in renovate bot. That's because renovatebot doesn't directly update any transient dependencies. 
Enabling this option instructs renovatebot to relock the lockfiles, which will bump all transient dependencies.
See https://docs.renovatebot.com/configuration-options/#lockfilemaintenance and https://github.com/renovatebot/renovate/discussions/15762
> Enable lockfile maintaince

- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend3/src/templates/vulnerability.html
Addresses outstanding feedback from #1483, and makes the information presented less consistent, focusing on only displaying what's available and applicable.
Also softened the wording for vulnerabilities without a summary on the listing page to deemphasize the information deficit.
> Reintroduce vulnerability source summary to vulnerability page

- vulnfeeds/cmd/alpine/main.go
- vulnfeeds/test_data/parts/alpine/CVE-2015-9251.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2016-2176.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2016-8568.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2017-13723.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2017-14448.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2017-9352.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2017-9993.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2019-14811.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2021-3770.alpine.json
- vulnfeeds/test_data/parts/alpine/CVE-2022-33745.alpine.json
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
Convert combine-to-osv to use VersionInfo to better integrate with cve/cpp conversion code.
> Convert combine-to-osv to use VersionInfo

- cloudbuild.yaml
- deployment/build-and-stage.yaml
- deployment/staging.yaml
- vulnfeeds/git/repository_test.go
Moving Cloud Build triggers to 2nd Gen repositories mean that they have to be regional and cannot use N1 machines.
> Change Cloud Build to use E2 machines

- deployment/build-and-stage.yaml
`gcloud builds list` needs a region flag now that builds are regional.
> Fix `build-and-stage.yaml`

- deployment/clouddeploy/gke-workers/base/scaler.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/scaler.yaml
We're getting an error in Cloud Deploy:
```
error: resource mapping not found for name: "pubsub" namespace: "" from "/workspace/stable/manifest.yaml": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
ensure CRDs are installed first
```
Let's see if this fixes it
> Try using `autoscaling/v2` for pubsub autoscaler

- .github/workflows/osv-scanner-pr.yml
- .github/workflows/osv-scanner-scheduled.yml
Adds two OSV-Scanner github actions
- `osv-scanner-pr.yml` blocks PRs that introduce new vulnerabilities, and annotates the vulnerable changed file.
- `osv-scanner-scheduled.yml` runs OSV-Scanner periodically and writes new vulnerabilities into the security code scanning tab. No notification system set up, so you have to manually look in code scanning tab for now.
> Dogfood our OSV-Scanner action!

- docker/ci/install_go.sh
- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cves/cve.go
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
This consults the CVE 5.0 record in the CVE List, because the 4.0 schema in the NVD doesn't have a machine-readable way to determine dispute status.
> Mark disputed CVEs as withdrawn

- README.md
- added a [link to a common serialization library](https://github.com/saveourtool/osv4k) of OSV for Kotlin MPP (via kotlinx.serialization) and Java (via Jackson)
> OSV4K: Java/Kotlin serialization library for OSV

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/combine-to-osv.yaml
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
After much poking around, I realised that while combine-to-osv was writing to the staging GCS bucket, it was *reading* from the production one. This was made harder to track down by an incorrect variable being used in the logged output. Also use `set -u` to make incorrect variable usage more self-evident.
> Make the CVE consolidation hermetic to staging

- vulnfeeds/cpp/main.go
These are not necessary as input to the consolidation pipeline
> Exclude any AffectedVersions from the output

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
Including the NVD input seems to causing the job to run into the current 1h deadline and get terminated, double the deadline to get a sense of how long it is taking to complete and what optimisations might be necessary.
Annoyingly this wasn't being very well surfaced in the logs, and additionally the concurrency policy seemed to be dueling with the deadline, causing further confusing log entries.
> Increase deadline for combine-to-osv

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/cpp/run_cve_to_osv_generation
I discovered
https://cloud.google.com/blog/products/storage-data-transfer/new-gcloud-storage-enables-super-fast-data-transfers while I was looking for speed optimisations
Increase CPUs for this job
This job is GCS transfer intensive, and will benefit from the parallelisation available with more than one CPU
> Use `gcloud storage` to accelerate GCS transfers and use more CPUs

- vulnfeeds/cves/cve.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/test_data/nvdcve-1.1-test-data.json
The configurations object of an NVD CVE is particularly gnarly and can essentially be recursive. Rework the struct to reflect this, and adjust the parsing to account for it. Add test coverage
> Improve CVE configuration parsing for CPEs

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
This is intended to increase the concurrency of the GCS file transfers to speed up the entire thing.
> Cargo cult what the importer is doing (with a tweak)  to get more computing power

- vulnfeeds/cves/cve.go
- vulnfeeds/vulns/vulns_test.go
I don't understand how this was working at all before...
> Fix reference time for CVE 5 timestamps

- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
Despite the
```
Package  *AffectedPackage `json:"package,omitempty"`
```
I think that because it's a pointer to a struct with default values, it's not being considered "empty" so it doesn't get omitted, and the record winds up with an unsightly looking
```
package: {}
```
which seems to be further angering the importing of it.
Improve the existing tests for this, including the PURL one, which was not testing correct behaviour.
> Avoid an empty package field in the resulting OSV record

- CONTRIBUTING.md
- tools/lint_and_format.sh
Based on observations from #1455, provide a better lit path for new contributors to ensure they have the appropriate prerequisites installed for local validation of proposed changes.
> Make lint_and_format.sh more user friendly for first time contributors

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
Now that I (slightly) better understand Kubernetes, throw even more CPU at the problem.
(The GCS file transfer is no longer exceptionally slow, so I'm not sure how much this will help, but hey, let's find out)
> Throw even more CPU at the problem

- deployment/clouddeploy/gke-workers/base/workers.yaml
Every time we've been deploying, 30 worker nodes were created, then immediately scaled back to 1 (or more depending on pending tasks).
Instead, just start with 1 replica and let the scaler make more if needed.
> Reduce initial workers replicas to 1

- osv/models.py
- osv/vulnerability.proto
OSV records converted from CVE records do not have a package specified and the exporter is currently exporting with an empty packages field.
> Don't set (and export) an empty packages field

- deployment/terraform/environments/oss-vdb-test/website.tf
The newer "google_cloud_run_v2_service" used for the website mirror has a `labels` field that Cloud Deploy changes, and terraform cannot change back.
> Add 'labels' to terraform cloud run ignore changes

- vulnfeeds/cpp/main.go
- vulnfeeds/cves/versions.go
The refactoring from #1510 introduced an incorrect logic inversion, and records were failing to be converted successfully due to no commits being found. They also weren't being added to what was returned, when they should have been.
Output additional logging to assist with following the flow for troubleshooting purposes.
> Fix logic error with preferencing predetermined fix commits

- gcp/api/Dockerfile.esp
- gcp/api/test_server.py
This allows us to run `make run-api-server` on glinux without file permission issues when mapping in ADC or other credentials.
> Fix: Remove --privileged flag and run ESP as root in local dev

- deployment/terraform/modules/osv/gcp_apis.tf
- deployment/terraform/modules/osv/project_iam.tf
Give cloud build default service account access so we can remove esp-test.
> Fix: Give cloud build service account access so we can remove esp-test

- Makefile
- cloudbuild.yaml
- gcp/api/integration_tests.py
- gcp/api/run_tests.sh
- gcp/api/test_server.py
Once we have done this, we should be able to throw the service account onto the bonfire.
> Remove service account download from cloudbuild

- deployment/deploy.sh
- deployment/terraform/environments/oss-vdb/.terraform.lock.hcl
Specify the short sha length to always return 7, which matches the cloud deploy short sha length.
This is needed because sometimes git will return more than 7 characters in the short sha.
https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_default_substitutions
> Specify short deploy length

- renovate.json
Attempt to fix renovate bot grouping, the previous `matchPaths` key has been removed. It's not clear if `matchRepositories` has the same functionality.
> Attempt to fix renovate bot grouping

- deployment/clouddeploy/osv-api/run.yaml
I had initially set it to 2x the thread pool count in #1291, but it seems we occasionally might run into health check problems because of this.
Curious to see if/how much this increases the number of instances we have.
> Set API containerConcurrency to equal thread pool

- osv/ecosystems/nuget.py
Hitting this code path was causing
```
AttributeError: 'dict' object has no attribute 'text'
```
> Fix exception in error handling in nuget

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
It turns out that `--no-user-output-enabled` is the new `--quiet`
Verified by interactive testing in a running pod.
> Suppress rsync output the Right Way

- vulnfeeds/git/repository.go
- vulnfeeds/git/repository_test.go
- vulnfeeds/git/versions.go
- vulnfeeds/git/versions_test.go
There's a particularly hairy fuzzy tag matching scenario that doesn't lend itself easily to the regex, where the repo name ends in a digit and the tags have this in their prefix. It leads to incorrect normalization of the tag. So try and identify such cases and preemptively remove the name-based prefix from the tags to be normalized.
> Ease fuzzy tag matching by removing repo name

- deployment/clouddeploy/osv-website/run-staging.yaml
- deployment/terraform/environments/oss-vdb-test/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb-test/website.tf
- gcp/appengine/handlers.py
Added the few static folders that are in the App Engine [app.yaml](https://github.com/google/osv.dev/blob/3501048dc4a7b8ee26cbba3d79119b7ebc0f9994/deployment/gae/oss-vdb-test/app.yaml) that were missing from the Flask handlers so they can be served on Cloud Run.
Also, set the minimum number of Cloud Run instances to 1 (instead of 0) to match the App Engine config.
Also also, fix terraform irrecoverably breaking when some settings are changed in the UI
> Add missing static files to Cloud Run website, set minimum instance count to 1

- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
It was discovered during manual validation that for records with multiple ranges and no known introduced commit, redundant zero introduced values are generated
> Avoid adding unnecessary duplicate zero-value introduced fields

- vulnfeeds/cpp/main.go
The situation where `cves.ExtractVersionInfo` opportunistically derives a fixed commit from a CVE's references means that also unconditionally successfully resolving a `last_affected` version to a commit results in both a `last_affected` commit *and* a `fixed` commit, which is not schema compliant, so don't do that.
> Resolve a last_affected version to a commit if no preexisting fixed commit

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
Allow a hand-curated OSV record to override one that is generated by
`combine-to-osv` in the event that we need/want to manually override
something.
Intended usage:
`gsutil cp gs://${OUTPUT_BUCKET}/osv-output/CVE-YYYY-NNNN.json`
(manually edit the file)
`gsutil cp gs://${INPUT_BUCKET/osv-output-overrides/CVE-YYYY-NNNN.json`
profit
> Interim overlay support

- vulnfeeds/vulns/vulns.go
`vulns.AddPkgInfo` was incorrectly aggregating events and not taking multiple repositories into consideration in the rare circumstances they exist in the input.
This also ensures that _every_ range (when there is multiple) gets a zero `introduced` value added when necessary.
> Correct how vulns.AddPkgInfo aggregates ranges by repo

- gcp/appengine/source_mapper.py
- go.work.sum
GitLab is subtly different to GitHub, so subclassing GitHubVCS is not appropriate. Define the necessary regexes for correct operation.
> frontend: correct handling of GitLab commit and compare URLs

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
Per
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits this defaults to 1, which makes it difficult to get a sense of how long a failing job has been failing for or to investigate any differences between a job that has started failing and ones that weren't.
I find the defaults to be backwards. Wouldn't you want more failed jobs to be retained than successful? Am I missing something here?
> Increase failedJobsHistoryLimit to 3

- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/combine-to-osv/main_test.go
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/test_data/cvelistV5/cves/2021/26xxx/CVE-2021-26917.json
- vulnfeeds/test_data/cvelistV5/cves/2023/23xxx/CVE-2023-23127.json
- vulnfeeds/test_data/cvelistV5/cves/2023/38xxx/CVE-2023-38408.json
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
This change makes consulting the CVE List to determine dispute status
(for marking converted CVEs as withdrawn) conditional and consult a local Git clone rather than the CVE
List remotely, in an attempt to speed up the overall run time of `combine-to-osv`.
It refactors `vulns.CVEIsDisputed` to consult a local clone of the CVE List rather than make numerous individual HTTP requests.
This should significantly speed up and improve the reliability of checking CVEs to see if they are disputed.
> Refactor vulns.CVEIsDisputed to use a local clone and speed up execution

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
Looks like I got this wrong, seeing failures in latest run's logs:
```
Unable to determine CVE dispute status of CVE-2017-8832: : open cves/2017/8xxx/CVE-2017-8832.json: no such file or directory
```
> Correct path to local CVE list clone

- docs/data.md
Copied the index.html from the debian-osv and cve-osv-conversion GCS buckets and reference the osv-vulnerabilities bucket in the same manner, and hey presto, it's way nicer to browse.
> Improve browseability of OSV exports

- osv/impact.py
This PR resolves the issue - https://github.com/google/osv.dev/issues/1607
In impact.py, the name "ranges" is used both as a method name and a variable name for a list. The PR changes the variable name to avoid confusion and unexpected behavior.
> Change local variable name in ranges method

- gcp/appengine/index.yaml
Add in the missing index for ecosystem filtering while sorting by timestamp.
> Add additional missing index

- Makefile
I encountered some unfamiliar errors trying to run the frontend locally that were resolved by running `npm install`, so run this automatically as part of the relevant Makefile targets to make it easier for people not familiar with NPM to get things done.
> Make running the frontend locally more turnkey

- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
Rather than iterate over `affected[].packages`, iterate over each `affected`
element, this way elements with multiple `ranges[]` entries can be
rendered as separate package-like tabs.
This is to predominantly address CVEs that end up with multiple GIT
ranges on them.
> frontend: render multiple repos correctly

- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
Per "Make the upstream source self-evident to OSV.dev end users" of "MVP for supporting contributed data fixes" ahead of launching NVD CVEs in OSV.
Make more off-site links open in a new tab
This way the originating record is still available to users.
Continuation from #1647
> frontend: surface human-friendly link to record source

- docker/exporter/exporter.py
- docker/importer/importer.py
- docker/worker/worker.py
GKE sends SIGTERM signals to pods when it needs to terminate them, and `tempfile.TemporaryDirectory()` does not clean up its files on the persistent SSD when that happens in its scope.
Manually clear the files when starting the pods.
> Remove temporary files when GKE pods start

- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
- Use alternate approach to rendering multiple repo ranges as proposed
in https://github.com/google/osv.dev/pull/1656#issuecomment-1734978673.
- Fix various unbalanced tag issues and indent the template a bit better
to make this more apparent. This seems to be the root cause of
rendering issues in https://github.com/google/osv.dev/pull/1661.
> Fix vulnerability details page

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/test_data/nvdcve-1.1-test-data.json
- Not all GitLab URLs (e.g. gitlab.freedesktop.org) have the repo in the first two parts of the URL path
- Not all GitLab URLs (legacy?) have a hyphen separating the repo from the remainder of the path
This was causing an invalid URL to be extracted from CVE-2022-46285, which went on to cause the worker to fail to successfully enumerate versions.
> Handle some edge cases in GitLab URLs

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
It turns out that `-c` with `gcloud storage rsync` is the equivalent of `-C` with `gcloud storage rsync`, so we weren't getting the desired behaviour any more :-(
> Reinstate gsutil rsync -c behaviour

- docker/worker/worker.py
This will assist with debugging the entire logged session of a worker with the same thread ID (as added by `_setup_logging_extra_info()`)
> Add an explicit log entry for when a task runner starts

- docker/worker/worker.py
Right now the completion of a worker task thread is logged, but the commencement of it (with any useful contextual information) is not, which makes it difficult to follow the journey of particular failing record imports.
> Log the creation of a worker task thread

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
At the end of version extraction, strip out any last_affected versions when there are preferred fixed versions present, to avoid the mix of fixed and last_affected versions ever being converted to commits and potentially winding up in the PackageInfo/VersionInfo input to combine-to-osv.
> Don't emit last_affected versions when there are fixed versions

- go.work.sum
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
These turned up a few times in generated records that crash analysis
> Handle GitHub and GitLab commit URLs with a .patch suffix

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
This was resulting in an erroneous false match and an invalid fix commit hash being extracted.
> Stop bundling GitHub and GitLab commit URLs in with Bitbucket

- vulnfeeds/tools/debian/debian_converter/Pipfile
- vulnfeeds/tools/debian/debian_converter/Pipfile.lock
- vulnfeeds/tools/debian/debian_converter/convert_debian.py
Fixes #1698 by removing "fixed" entries when the value is "`<unfixed>`". Currently there are only 3 entries with `<unfixed>`.
A similar case where the "fixed" entries is "`<end-of-life>`" is also now omitted (there are currently only 5 advisories with this).
Also bump the python version and update lockfile to make local development easier.
> Omit unfixed from debian entries

- vulnfeeds/tools/debian/Dockerfile
- vulnfeeds/tools/debian/debian_converter/Pipfile
Use the google cloud sdk base docker image since it's the main dependency (that can't be installed via pkg manager). https://hub.docker.com/r/google/cloud-sdk
> google/cloud-sdk:alpine, google/cloud-sdk:VERSION-alpine: (smallest image with no additional components installed, Alpine-based)
> Simplify dockerfile and support python 3.11

- vulnfeeds/cpp/main.go
Support denylisting by vendor, regardless of product, and denylist netapp, a third product has caused misattribution.
Denylist `netapp:cloud_backup`, causes misattribution to OpenSSH
> Support denylisting by Vendor, and denylist netapp after three different product strikes

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
I had previously not considered the import process and the need for the `repo` in the generated records to be cloneable, and was focusing on human-usable repo URLs, which crashes analysis.
> Translate cGit and GitWeb URLs to a Repo that is cloneable

- vulnfeeds/cpp/main.go
Rather than risk false positives and emit records where the Introduced version was mapped to a commit and the Fixed version was not, fail to convert these records. Introduce a new failure mode outcome, so these can be easily identified afterwards.
> Do not emit partially converted records

- osv/repos.py
When a git repository failed to clone, we had just been logging an error and continuing. [The code later assumes the clone was successful](https://github.com/google/osv.dev/blob/36c344dee7e46cc1fa5cf0dea2222552b9efe953/osv/impact.py#L321), which was causing another exception. 
Instead, just raise an exception when the clone fails to make it more obvious what's wrong.
> Raise exception when git clone fails

- gcp/appengine/source_mapper.py
Manually tested with data from [CVE-2023-40303](https://oss-vdb-test.wl.r.appspot.com/vulnerability/CVE-2023-40303)
```
In [1]: import osv
In [2]: import source_mapper
In [3]: vcs = source_mapper.get_vcs_viewer_for_url("https://git.savannah.gnu.org/git/inetutils.git")
In [4]: vcs.get_source_url_for_revision("e4e65c03f4c11292a3e40ef72ca3f194c8bffdd6")
Out[4]: 'https://git.savannah.gnu.org/cgit/inetutils.git/commit?id=e4e65c03f4c11292a3e40ef72ca3f194c8bffdd6'
```
> Add a URL rewriter for Savannah repo URLs

- gcp/api/integration_tests.py
Fix the integration tests by using a different commit hash and reference vulnerability.
> The commit hash used for querying by commit now returns 28 vulns

- deployment/clouddeploy/gke-workers/base/exporter.yaml
Update exporter frequency to every hour to increase freshness of our GCS data.
> Increase exporter frequency to every hour.

- deployment/terraform/environments/oss-vdb-test/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/workers_gke.tf
#1723 is trying a major version bump of the Google Terraform providers, which changed the way GKE taints are defined, so I've done the bumps manually with the required changes.
`terraform plan` shows it's adding some new `terraform_labels` to the Cloud Run services, with metadata about the Cloud Deploy pipeline which includes the current 'release-id' which hopefully isn't a problem when it changes outside of Terraform.
I've also explicitly added the `required_providers` to the root modules (see the [best practices](https://developer.hashicorp.com/terraform/language/providers/requirements#best-practices-for-provider-versions)), so hopefully renovate-bot won't blindly do breaking changes in the future.
> Bump and specify Terraform provider versions

- gcp/appengine/Dockerfile
There's some weirdness going on with docker builds failing. This might help?
We should be using a particular node version in here anyway.
> Specify node:20.9 in website docker image

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
As seen as a reference on [CVE-2021-28429](https://osv.dev/CVE-2021-28429)
> Add support for another variation of GitWeb URLs

- gcp/appengine/source_mapper.py
- vulnfeeds/cves/versions_test.go
- vulnfeeds/test_data/nvdcve-1.1-test-data.json
Add an end-to-end test case to validate [CVE-2021-28429](https://osv.dev/CVE-2021-28429)
Add support to the frontend for linking to commits in the FFmpeg repo.
I haven't been able to test this locally because I'm having problems running the frontend locally.
> Build on #1761 to add support for another variation of GitWeb URLs

- gcp/appengine/source_mapper.py
The '.git' is needed in the resulting URL.
> Adjust the second capture group

- .github/workflows/osv-scanner-pr.yml
It looks like nothing gets inherited from the defaults when you start overriding at the job level.
> Add permission to read contents

- vulnfeeds/cpp/main.go
This isn't open source, and winds up getting github.com/lxml/lxml associated with it, which then causes that repo to incorrectly wind up being tried for other CVEs that also have that CPE on them.
> Denylist oracle:zfs_storage_appliance_kit CPE

- vulnfeeds/cpp/main.go
Correct a bug where the last detected repo (for CVEs with multiple CPEs) is the one used by ensuring all repos for all the CPEs on a CVE are included in the per-CVE repo list.
> bugfix: use all available repos, not the last one

- docker/alias/alias_computation.py
For some reason, querying for `> ''` on the repeated property causes some of the same bugs to appear multiple times in the query. It doesn't seem to happen with `!=`
> Avoid datastore comparison bug

- vulnfeeds/cpp/main.go
Because we repeatedly run over year in-scope year's JSON file, searching the logs for the metrics makes it hard to figure out which log entry relates to the run for which year.
> Make the individual year's metrics easier to discover

- docker/indexer/shared/shared.go
- docker/indexer/stages/processing/processing.go
- docker/indexer/storage/storage.go
This can cause bad matches against libraries that depend on the correct library we're trying to identify (#1766).
> Indexer: don't index vendored libraries.

- docker/indexer/stages/processing/processing.go
Followup to #1780 , Fixes #1766 .
Just after I merged in the previous PR I realized I missed DocumentVersion datastore name.
> Add datastore label to bucket node entry

- .gitignore
- docker/indexer/stages/processing/processing.go
Skip cleaning older versions for now, until we update osv-scanner and indexer scanning tools to also ignore vendor folders.
> Skip cleaning older versions for now 

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/test_data/nvdcve-1.1-test-data.json
extractVersionsFromDescription wasn't doing the same pragmatic fallback to last_affected for unvalidatable versions that was previously added to ExtractVersionInfo.
> Add last_affected support to extractVersionsFromDescription

- vulnfeeds/git/versions.go
- vulnfeeds/git/versions_test.go
When doing prefix matching, do not do it versions with a "pre-release" textual suffix, to avoid undesired matches.
Addresses multiple converted CVEs in Apache InLong that were showing as unfixed (their repo has some strange release tagging practices).
> Improve fuzzy version matching

- vulnfeeds/git/repository.go
- vulnfeeds/git/repository_test.go
- vulnfeeds/git/versions.go
- vulnfeeds/git/versions_test.go
These have been observed to be involved with CVE conversions that are falsely reporting as unfixed or failing to convert entirely
Support tags that have the repo name in the middle (as seen causing CVE-2023-4366{6,7,8})
Support tags that have the Java package name in them (fixes: #1776)
> Add support for normalizing some more obscure tags

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/environments/oss-vdb/unmanaged.md
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/variables.tf
Import osv-backup into terraform
Add lifecycle policies to avoid keeping really old backups. Currently set to 60 days.
> Add lifecycle and import osv-backup into terraform

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
The new API-based approach + splitting by year seems to be OOMing. Switch the NVD conversion job over to the highend cluster as well.
> Increase RAM for both jobs utilising NVD data

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/nvd-cve-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/nvd-cve-osv.yaml
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/cpp/run_cve_to_osv_generation
a) it's slow
b) it's RAM intensive to split into years
c) the acquisition is duplicated
Revert "Increase RAM for both jobs utilising NVD data (#1837)"
This reverts commit 6ee42da2edd8a019e94ef4285cf02c09bd647e43.
Once #1839 lands (I've made a one-time manual copy of the data in the interim so this isn't dependent on it) the source data will be routinely populated.
> Decouple the direct aquisition of the NVD data

- vulnfeeds/cmd/alpine/Dockerfile
- vulnfeeds/cmd/combine-to-osv/Dockerfile
- vulnfeeds/cmd/cperepos/Dockerfile
- vulnfeeds/cmd/download-cves/Dockerfile
- vulnfeeds/cpp/Dockerfile
https://hub.docker.com/layers/library/golang/1.21-alpine/images/sha256-f475434ea2047a83e9ba02a1da8efc250fa6b2ed0e9e8e4eb8c5322ea6997795?context=explore has less vulnerabilities in it
I wonder if we can get Dependabot to do something useful here?
> Update golang buildchain Docker image

- vulnfeeds/cmd/download-cves/main.go
- vulnfeeds/cves/cve.go
- vulnfeeds/cves/nvd2.go
The hand-constructed NVD API 2.0 struct was naively done and appears to lead to nil pointer panics under certain conditions.
> Use the fully fledged struct for downloading

- vulnfeeds/tools/debian/debian_converter/Pipfile
- vulnfeeds/tools/debian/debian_converter/Pipfile.lock
Before #1832, `debian-converter` had `pandas==2.1.1` in the Pipfile.lock, despite the Pipfile specifying `pandas==1.5.3`. (how did this happen??)
It looks like `pandas==1.5.3` doesn't install properly in the docker container due to some problem with installing a compatible version of numpy (?)
Bumped pandas to the latest version, which seems to install when I was running it manually in the container.
> Bump pandas to v2 in debian convert

- docker/cron/backup/backup.py
- docker/cron/make_bugs_public/make_bugs_public.py
- docker/cron/process_results/process_results.py
Python doesn't automatically load these submodules (all other `osv.X` seem to work as side effects of other imports)
> Import `osv.logs` in cron

- docker/importer/importer.py
@jess-lowe had to add a new repo type to the test instance for her work.
The test instance currently doesn't recognize it and crashes when it encounters it. Don't do that.
> Don't crash importer on invalid repo type

- gcp/appengine/frontend_handlers.py
Unclosed `<!--` in the vulnerability details sections aren't escaped due to a [problem with markdown2](https://github.com/trentm/python-markdown2/issues/563).
Temporarily manually escaped these.
> Temporary fix for markdown `<!--` escape issue

- vulnfeeds/go.mod
The go.mod minor version causes issues with older versions of go (1.20 and older).
> Revert go.mod minor version change

- gcp/appengine/frontend3/package-lock.json
@renovate-bot  changed this to be invalid in https://github.com/google/osv.dev/pull/1893#discussion_r1446738483
Revert it to what it used to be.
I don't know how that happened
> Revert spicy-sections integrity change

- docker/alias/alias_computation_test.py
- docker/importer/importer_test.py
- docker/worker/worker_test.py
- osv/impact_test.py
- osv/tests.py
Killing the main datastore process leave its child processes running and orphaned.
Should've tested this properly before :upside_down_face:
Used the `/shutdown` endpoint that [apparently exists](https://github.com/googleapis/java-datastore/blob/1849e0be44e94fbfa48211484de4af602ca6b614/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java#L323) (and works!).
I have no idea if there's proper documentation for this...
> Stop Datastore emulator properly

- docker/mock_test/mock_test_handler.py
The constant spam of successful GET requests, while a good indication that the request is successful, is unnecessary. 
Now it will just log nothing if it is a successful (200) error, and do its normal thing when it's unsuccessful.
> Fixed logging all of the successful GET commands during testing.

- gcp/appengine/frontend3/src/templates/vulnerability.html
The vulnerabilities missing packages/ecosystems were causing issues in that they also had no repo field, which caused 500 errors on these endpoints.
> Fixed vulnerability having no repo field causing 500 errors.

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yaml
- .github/workflows/scorecards.yml
Some of the jobs has unnecessary `read-all` access, this PR modifies the default access to none and a job can overwrite the permission.
> modify job permissions

- README.md
As I'd not spotted this was different to the third party docs added in
2a4022c818232b32573841a6f506796a25d13120.
> Add dependency-management-data to README

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
Improve on the quick fix shoe-horned into PR #1936 by restoring external configurability of the oldest desired year and biasing for the current and more recent years first (because Andrew hates delayed gratification)
> Bias future-year-proofing for the most recent year

- deployment/clouddeploy/osv-api/run.yaml
Large batch queries can impact how long other queries running on the same instance take, making the liveness queries take possibly over a second to respond and failing the liveness checks.
I've bumped the probe `timeoutSeconds` up from the default 1 to 5 to see if this reduces the number of failures that happen. I've also explicitly defined the `failureThreshold` and `periodSeconds`, but I've set them to the defaults values.
> Make API liveness probe more lenient

- osv/models.py
- source_test.yaml
- tools/sourcerepo-sync/run_source_update.sh
- tools/sourcerepo-sync/source_repo_default.yaml
Added some documentation around what each configuration means for SourceRepository and set up cloud build trigger bash script to run the source repository updater no-dry-run.
> SourceRepository Sync 

- docker/indexer/stages/preparation/preparation.go
This is blocking tags in libuv from being processed. With this change, these errors will be logged and ignored so tags later in the iteration are not ignored.
libuv example:
```
E0212 23:28:24.789819   23579 preparation.go:158] Failed to resolve refs/tags/pubkey-bnoordhuis: unsupported object type
E0212 23:28:24.789910   23579 preparation.go:158] Failed to resolve refs/tags/pubkey-cjihrig: unsupported object type
E0212 23:28:24.789991   23579 preparation.go:158] Failed to resolve refs/tags/pubkey-cjihrig-kb: unsupported object typeE0212 23:28:24.789819   23579 preparation.go:158] Failed to resolve refs/tags/pubkey-bnoordhuis: unsupported object type
E0212 23:28:24.789910   23579 preparation.go:158] Failed to resolve refs/tags/pubkey-cjihrig: unsupported object type
E0212 23:28:24.789991 …
```
> Ignore reference resolution errors in indexer preparation.

- gcp/appengine/frontend3/package-lock.json
Not sure why the package sha is updated while the version remains the same.
PR https://github.com/google/osv.dev/pull/2012/files
> Revert spicy-sections sha back

- docker/exporter/exporter.py
Readability tweaks to the export code to reduce ramp up comprehension time.
Log the exception as an exception for maximum utility.
> Make the GCS exports slightly easier to reason about

- deployment/terraform/environments/oss-vdb-test/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/.terraform.lock.hcl
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/workers_gke.tf
Bumped all the terraform providers to the latest versions & relocked.
Also bumped the [esp-v2](https://github.com/GoogleCloudPlatform/esp-v2/releases) image to the latest.
> Update terraform requirements

- deployment/terraform/modules/osv/scripts/gcloud_build_image
The `mktemp` command on our alpine terraform image is actually stricter about what it accepts, causing a fail it to fail to apply.
```
/ # mktemp --help
BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.
Usage: mktemp [-dt] [-p DIR] [TEMPLATE]
Create a temporary file with name based on TEMPLATE and print its name.
TEMPLATE must end with XXXXXX (e.g. [/dir/]nameXXXXXX).
Without TEMPLATE, -t tmp.XXXXXX is assumed.
-d	Make directory, not file
-q	Fail silently on errors
-t	Prepend base directory name to TEMPLATE
-p DIR	Use DIR as a base directory (implies -t)
-u	Do not create anything; print a name
Base directory is: -p DIR, else $TMPDIR, else /tmp
```
Namely:
> TEMPLATE must end with XXXXXX
We've just never updated the ESP image since we changed the terraform image to use alpine. …
> Fix use of `mktemp` on alpine

- renovate.json
Prevent Renovate from upgrading Python base image in `Dockerfiles`
Add a new `packageRule` to maintain `python:3.11-slim` for stability in docker. Renovate was previously [automatically upgrading](https://github.com/google/osv.dev/pull/2000/files) this image, causing potential compatibility issues.
> Disable Dockerfile Python upgrading

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/backup.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/backup.yaml
- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/variables.tf
- docker/cron/backup/backup.py
The existing backup doesn't easily distinguish between entity types. This makes it easier for internal consumers to use our AffectedCommits data.
Using a different bucket here so we can set a different lifecycle policy (3 days TTL) than our existing backup bucket (60 days TTL).
> Backup AffectedCommits in a separate bucket.

- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
The previous copying technique optimised for getting the records to GCS as fast as possible for opportunistic ingestion by combine-to-osv.
The problem with this approach is that if any improvements to the conversion code stop generating records that shouldn't be generated, the most recent copy lingers in GCS indefinitely. This is causing situations like the one described in #1961
So collect all of the records generated and copy them to GCS at the end of the complete run, deleting anything in GCS that wasn't just copied.
> Adjust how converted records are copied to GCS

- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
Some filenames wind up with an embedded quote character or are very long due to the CPE vendor/product name and this seemed to cause some copy operations to fail.
> Make the copying more resilient

- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
Pre-copying the CSV summary to GCS before the final rsync with `--delete-unmatched` (as introduced in #2023) just means that they don't survive :-(
> Also stage the CSV conversion summary

- deployment/clouddeploy/osv-api/run.yaml
- gcp/api/server.py
Reduce concurrency from 10 to 5 to reduce the number of inflight data store queries are being made per instance. This is an attempt at fixing the latency/timeout issues for the batch_query API endpoint.
> Lower concurrency to improve performance

- docker/exporter/exporter.py
- tools/datafix/reimport_gcs_record.py
Fixes the issue `AttributeError: module 'google.cloud.storage' has no attribute` brought by https://github.com/google/osv.dev/pull/2046
> import retry module

- gcp/api/server.py
The way I've been adding error reporting information is incompatible with defining extra json fields. :(
Tests didn't pick this up because it's only enabled when running on Cloud Run :(
For now, just dump the json string into the log message
PURL parsing re: https://github.com/google/osv.dev/pull/2047#discussion_r1520836700
Also checks a bit more thoroughly for invalid queries
> Temp fix for logging errors & Parse PURLs for logs

- gcp/api/server.py
- osv/logs.py
The way Error Reporting information was being added to logs was preventing us from adding additional `json_fields` to our logs.
Changed from inserting Error Reporting information in a Log Record Factory to a Log Filter.
See: https://docs.python.org/3/howto/logging-cookbook.html#using-filters-to-impart-contextual-information
Also put the API logged fields back into the json data.
> Allow for json fields in python logs

- deployment/clouddeploy/osv-api/run-batch.yaml
- deployment/clouddeploy/osv-api/skaffold.yaml
- deployment/terraform/modules/osv/osv_api.tf
Make a duplicate Cloud Run API backend with no concurrent requests for processing batch queries.
Don't route traffic to it yet - the traffic routing is controlled by terraform which is run before Cloud Deploy and we don't want it to completely take down our batch queries if something goes wrong.
> Set up second Cloud Run backend for batch queries (part 1)

- gcp/api/server.py
Adds the trace fields to most of the logs produced by the API, so it's easier correlate the logs to their requests.
Relevant links:
https://cloud.google.com/trace/docs/setup#force-trace
https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields
> Add trace to API logs

- deployment/terraform/environments/oss-vdb-test/api/api_config.tftpl
- deployment/terraform/environments/oss-vdb/api/api_config.tftpl
- deployment/terraform/modules/osv/osv_api.tf
Merge this after #2057 / #2058 has been released.
Route batch query traffic to the new Cloud Run service.
> Set up second Cloud Run backend for batch queries (part 2)

- docs/faq.md
The links to the API page on the current FAQ page go to https://google.github.io/osv.dev/faq/api/, which is 404. This change fixes that behavior by going up a folder.
Tested: built and verified change by following https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md#contributing-documentation
> Fix API links in FAQ page

- source.yaml
- source_test.yaml
Caveat: The lack of version enumeration greatly reduces the utility of this data.
> Add the Ubuntu OSV data source to production

- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/404.html
- gcp/appengine/frontend_handlers.py
This change, adds a custom 404 page. The new template extends the existing base template and uses the existing styles.
issue: https://github.com/google/osv.dev/issues/1556
Here is how it looks:
**On desktop screen**
**On mobile/tablet screen**
> Add 404 template

- vulnfeeds/cmd/debian/main.go
- vulnfeeds/cmd/debian/main_test.go
- vulnfeeds/test_data/parts/debian/CVE-2016-1585.debian.json
- vulnfeeds/test_data/parts/debian/CVE-2018-1000500.debian.json
- vulnfeeds/tools/debian/debian_converter/first_package_finder.py
- Sorts the Debian OSV outputs to remain consistent each runs (https://github.com/google/osv.dev/issues/2103)
- Fixes the `AffectedVersions`
- modifies `first_package_finder.py` to support future Debian releases, like Debian 13.
> Sort Debian OSV pkgInfos

- osv/ecosystems/bioconductor.py
Enumeration seems to be failing for Bioconductor 3.19:
```
$ GET https://packagemanager.posit.co/__api__/repos/4/packages/a4?bioc_version=3.19
{"code":4,"error":"Package 'a4' not found","payload":null}
```
but works for 3.18 and 3.1 (the bounds of the array returned by `get_bioc_versions()`)
/cc @tylfin for visibility
> Workaround for Bioconductor test breakage

- gcp/api/integration_tests.py
The additional matching CVE has now been rejected, and the text of the description has changed. I suspect we haven't seen the last of this yet, as a rejected CVE should be resulting in a withdrawn OSV record...
(I'm investigating why that isn't the case, but want to unbreak the test)
> Fix querying by commit integration test more

- gcp/appengine/frontend3/src/styles.scss
Small PR that fixes the padding issue of the background image in 404 page, to address [this](https://github.com/google/osv.dev/pull/2114#issuecomment-2064688650) comment.
issue: https://github.com/google/osv.dev/issues/1556
Before:
After:
> Fix the padding of the background image

- docker/importer/importer.py
null `directory_path` sources in Datastore wind up as NoneType, which makes `os.path.join()` have a bad time.
Other users of `directory_path` are NoneType-tolerant
> Handle null directory_path sources

- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/templates/list.html
Issue: #1697 
As mentioned in the issue, the vulnerability list page gets stuck after apply filters and click on the browser's back button, I've done some research on this but can't find a nice solution, and I feel this could be a weird bug of Turbo. So I just disabled the Turbo cache behavior for vulnerability list page, and it just reloads the page after click the back button.
Please let me know if you have a better suggestion.
> Improve browser navigation back for vulnerability list page

- gcp/appengine/frontend3/src/templates/vulnerability.html
Issue: #381 
Since [spicy-sections](https://github.com/tabvengers/spicy-sections) doesn't have a feature of expanding all collapsed sections by default, I decided to programmatically click on those package headers when the page is loaded. But this method is bit of awkward, so let me know if you have a better idea.
Mobile view:
An alternative way of implementing similar feature is using `exclusive-collapse` mode for `spicy-section`, but in that mode only the first section is expanded by default, and users are only able to expand one section (which is kind of similar with the tab-bar mode). Here is a demo of different modes of Spicy Section, and you just need to click on the "exclusive-collapse" button to check exclusive-collapse mode:
https://spicy-sections.glitch.me/programatic.html
> V2 UI: Handle overflowing tabs on vulnerability details better

- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/combine-to-osv/main_test.go
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/cmd/debian/main.go
- vulnfeeds/cmd/debian/main_test.go
Fixes https://github.com/google/osv.dev/issues/2103
The current `modfied` time of a combine-to-osv entry only reflects the CVE modified time without checking if any `parts` has been changed. Updates code to set the `modified` field to the most recent modification time of parts' components or the original CVE entry.
- Uses `os.Stat(file).ModTime()` to check the last modified time of each part.
- Maintains a map to record the most recent modification of each part file associated with each CVE ID.
- Updates `PackageInfo`'s `modified` field if the part modified time is later than the original CVE's modified time.
It may not be the best implementation, but its failure wouldn't affect the logic of any existing code.
> Update last modified time of combine-to-osv entries

- gcp/appengine/frontend3/img/feed.svg
- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/styles.scss
This PR introduces a rss link to the site.
Issue: #1048 
i'm not quite sure about if we should just add a link tag or display a RSS icon beside the Github icon at the top right corner:
or maybe we want both of them? Please let me know your suggestion.
> Add RSS link to the page

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cves/versions.go
Instability in this data structure adds unnecessary noise.
There is currently the potential for variability in the output, which is resulting in unnecessary file copying to GCS (because the checksum of the file changes), and we're trying to get the true modification time of a resultant OSV record to reflect that of the newest constituent input part to `combine-to-osv`.
Before (for CVE-2016-0502):
```
[
{
"fixed_version": {
"affect_commits": [
{
"repo": "https://github.com/mysql/mysql-server",
"introduced": "54df0057e18d8c82c23fbd4e0bf5b5dc2e762955"
},
{
"repo": "https://github.com/mysql/mysql-server",
"fixed": "020dcec4a12e61cf5853623a2cd7b06d6bdb351f"
},
{
"repo": "https://github.com/mariadb/server",
"introduced": "5bfe1a3917ee1bddc7f2cde0c88961875148873c"
},
{
"repo": …
```
> Sort the AffectedCommits

- docker/importer/importer.py
This way a deliberate threshold of zero doesn't cause a misfire.
> Return early when there's nothing to delete

- .github/workflows/lint.yaml
- docker/ci/install_go.sh
- docker/indexer/Dockerfile
- docker/indexer/go.mod
- docker/terraform/Dockerfile
- docs/go.mod
- go.work
- tools/datastore-remover/go.mod
- tools/indexer-api-caller/go.mod
- vulnfeeds/cmd/alpine/Dockerfile
- vulnfeeds/cmd/combine-to-osv/Dockerfile
- vulnfeeds/cmd/cpe-repo-gen/Dockerfile
- vulnfeeds/cmd/debian/Dockerfile
- vulnfeeds/cmd/download-cves/Dockerfile
- vulnfeeds/go.mod
This resolves the vulnerabilities reported on Go 1.22.1.
> Update Go version to 1.22.2

- docker/deployment/Dockerfile
Bump up the npm version to v8.19.4 from v8.5.1 . This allows npm to build the frontend correctly, since as of v8.5.2 integrity checks are not performed on git remotes (the hash is not stable between npm versions).
> Bump npm version to v8.19.4

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cves/versions.go
Also stop looking once one's been found.
While eyeballing the cleanup in staging I noticed some records being deleted that were not expected, and it was because they had previous converted when they only had commit references, but then didn't once they had versions and the commit references, due to this case-sensitivity mishandling the situation.
> Search for existing commits case-insensitively

- deployment/clouddeploy/gke-workers/base/exporter.yaml
- docker/exporter/Dockerfile
- docker/exporter/export_runner.py
- docker/exporter/exporter.py
Exporter currently take too long to complete (around 1 hour and 10 minutes), and will only get longer to run as the OSV database expands.
This change parallelizes the exporter along each ecosystem, separating the ecosystem export portion of the script from the selection of each ecosystem. This roughly reduced the time taken down to how long the longest ecosystem takes to export, 13 minutes or so.
> Add parallel exporter

- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/combine-to-osv/main_test.go
- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/cmd/debian/main.go
- vulnfeeds/cmd/debian/main_test.go
Same as https://github.com/google/osv.dev/pull/2158
Merge after weekly release and https://github.com/google/osv.dev/pull/2164
> Relaunch "Update last modified time of combine-to-osv entries"

- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
The `gcloud storage rsync --checksums-only` command always updates the modified time on GCS objects once a file has been touched, even if the file content remains the same. Updates it to `gsutil rsync` command to keep the original modified time on GCS objects when nothing has been changed.
> Fix modified time of nvd part entries

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
Prior to this change, in the vulnerability page, id of the vulnerability was displayed as title.
This change updates the title to display the human readable summary for the title, and adds ID as an data description.
resolves #2078
example 1 - Before:
After:
Example 2 - Before:
After:
> Update the title to display summary instead of id

- docker/importer/importer.py
I noticed this was not behaving as intended during manual dry-run testing in Production.
> Do not process OSS Fuzz in delete-only mode

- docker/worker/oss_fuzz.py
- docker/worker/worker.py
Fixes #2178. 
BoringSSL maintainers would like more control / vetting of entries. Disable the import for now until we have a better system in place to enable that.
> Disable boringssl OSS-Fuzz -> OSV import

- gcp/appengine/frontend3/src/templates/vulnerability.html
Issue: https://github.com/google/osv.dev/issues/381
Initially the page listens the window onload event, and programatically clicks on the headers so the sections will be expanded. But since we use Turbo, it will request the new page by using fetch request rather than doing a full reload, so the `load` event won't be triggered.
In this PR we make the script listens `turbo:load` event which always happens when visiting a new page.
Result:
> Fix collapsed packages when navigate to vulnerability page

- deployment/terraform/modules/osv/website.tf
There's been no problems with Cloud Run so far.
This is 25/75, next PR will be 50/50, then 100/0.
> Bump website cloud run traffic

- tools/datafix/reimport_gcs_record.py
This prevents a messier Datastore API failure (the IN operator only supports up to 30 values) when querying for more than 30 Bugs and signposts a solution.
> Improve the usability when operating on a larger number of records

- gcp/api/integration_tests.py
The cleanup of stale GCS-based records changed the CVE record landscape.
> Fix integration tests withdrawn CVEs

- deployment/terraform/modules/osv/website.tf
I will delete all our app engine stuff probably in the next week or two, in case we really need to roll back.
> Migrate website traffic entirely to Cloud Run

- gcp/appengine/frontend3/src/templates/blog_post.html
Issue: #2184
Turbo always tries to cache the page after a link, but after navigate to a new page, it can't get the images of the blogs cause they use relative path, e.g.
https://github.com/google/osv.dev/blob/2e1117e5c9360f755d46165eaf2f2bf6b576d09f/gcp/appengine/blog/content/posts/announcing-guided-remediation-in-osv-scanner/index.md?plain=1#L36
This PR disables the cache feature of Turbo Drive which is a quick solution, but this will reduce the performance when navigate back to the blog (content won't be stored and it will load a fresh page).
Another solution is improving the images path for each blog, for example use `/static/blog/posts/announcing-guided-remediation-in-osv-scanner/gr_main.png` instead of `gr_main.png`. But by going this way, we need to keep in mind to use absolute path …
> Fix 404 error when navigating away from blog page

- deployment/build-and-stage.yaml
- deployment/deploy-prod.yaml
- deployment/staging.yaml
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/website.tf
Since the website's happily running on Cloud Run, we can stop deploying it to App Engine.
Deleting App Engine from terraform is going to take a few steps, because terraform isn't smart enough to delete the resources in the required order (it tries to remove some resources before the resources that are using them)
> Remove App Engine from deployment process

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
This change adds the following info to the vulnerability page:
- purl: https://ossf.github.io/osv-schema/#affectedpackage-field
- Severity: https://ossf.github.io/osv-schema/#severity-field
- Credits: https://ossf.github.io/osv-schema/#credits-fields
resolves #2081
Regarding the second items on the issue:  per-range ecosystem/database_specific fields I left a [question](https://github.com/google/osv.dev/issues/2081#issuecomment-2071687782) on the issue.
> Add missing OSV schema fields to vulnerability page

- gcp/appengine/source_mapper.py
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
GitWeb URLs are very snowflakey. They don't always have the `gitweb.cgi` distinguishing URI, but they do seem to have the `p=\*.git` query string.
Furthermore, they don't always map to a cloneable https:// URL.
This PR handles the small range of GitWeb URLs currently observed in the wild, extending support for the repo that will make CVE-2024-3094 (that xz vulnerability) convertible.
Also teach the frontend how to rewrite GnuPG repos for existing CVEs that are converting.
> Support converting xz CVE-2024-3094

- vulnfeeds/cmd/cpe-repo-gen/main.go
- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/main_test.go
- vulnfeeds/git/repository.go
- vulnfeeds/git/repository_test.go
#2233 introduced a small regression, in that repositories for CPEs that have no usable tags are no longer present in the VendorProductToRepoMap (intentionally).
This also means that CVEs for these repos that lack tags but otherwise have a commit hash in the CVE's references now get excluded from consideration from conversion.
CVE-2023-0327 before #2233 had an entry in the VendorProductToRepoMap for `theradsystem_project:theradsystem`,
even though the repo wasn't usable. Afterwards, it does not, resulting in:
```
[CVE-2023-0327]: Failed to derive any repos for "theradsystem_project" "theradsystem"
[CVE-2023-0327]: Summary: [CPEs=1 AppCPEs=1 DerivedRepos=0]
[CVE-2023-0327]: Passing due to lack of viable repository
```
because of the added rigour of `cves.ValidRepo()` …
> Fix for a small conversion regression

- gcp/appengine/frontend3/src/styles.scss
Removed the text-transform property so affected packages ecosystems should be in normal case:
Closes #2240
P.S Hey again :D
> Fixed UI Affected Packages Ecosystems label being in uppercase

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
Issue: #2216
Result:
Does not render a toggle button if it's a short list:
> Collapse fields on vulnerability page when it's too long

- .github/workflows/issue-signposting.yml
According to https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines this ought to do the trick and make the output look a little nicer, based on how it's currently rendering for #2251
YAML sucks.
> Improve multiline formatting in issue automation

- deployment/terraform/modules/osv/website.tf
This just removes App Engine from the load balancer. I'll manually apply this on prod after it's merged.
I still need to understand what happens to Datastore if we delete App Engine entirely.
> Remove App Engine backend from GCLB

- gcp/appengine/frontend_handlers.py
Issue: #1117
Automatically redirect to the first page if query string has a negative page number
> Handle negative page for vulnerability list page

- docker/worker-base/Dockerfile
Renovatebot lockfile maintenance #2245 and #2244 uses the latest Pipenv version, which doesn't seem to be backwards compatible. Specifically, it adds a marker (python >= 3.7) to an editable dependency (./../..) (our osv dependency).
Older versions of Pipenv running `pipenv sync` will fail, so updating the CI image to the latest version of pipenv. If you have manually installed pipenv, you'll also need to update your local dev pipenv after #2245 and #2244 is merged.
> Update to the latest pipenv version to make renovatebot changes valid

- .github/workflows/lint.yaml
- docker/deployment/Dockerfile
- gcp/appengine/Dockerfile
- vulnfeeds/tools/debian/Dockerfile
Turns out we are setting the pipenv version in quite a few places 
Follow up to #2260
> Update rest of pipenv versions to 2023.12.1

- docker/terraform/README.md
- docker/terraform/cloudbuild.yaml
I'd like to use an [import block](https://developer.hashicorp.com/terraform/language/v1.5.x/import) to help import the datastore into terraform, which was introduced in v1.5.
Please also update your local terraform versions to at least 1.5.
1.5.7 isn't the latest version of terraform, but version 1.6 is when they changed their license and I don't really understand those ramifications :sweat_smile:
> Update terraform version

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/main.tf
The App Engine resource automatically created the datastore database. Added & imported the datastore resource explicitly.
> Explicitly manage datastore in terraform

- deployment/clouddeploy/gke-workers/base/debian-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/debian-cve-convert.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/kustomization.yaml
Deploy `debian-cve-convert` cron job on production.
> Enable Debian combine-to-osv on prod

- vulnfeeds/cves/versions_test.go
"https://gitlab.freedesktop.org" is currently under maintenance, which causes some test failures. 
Temporarily disable related tests to allow PR merging.
> Disable failed tests to unblock deployment

- gcp/appengine/cache.py
- gcp/appengine/frontend_handlers.py
- gcp/appengine/main.py
**Problem:**
Every 24 hours, a few unfortunate visitors will have osv.dev take incredibly long to load (over 30 seconds), as the ecosystem counts cache expires, and the website tries to count the number of advisories in each ecosystem.
**Solution:**
This PR adds a smarter refresh logic where at half the cache timeout duration (24 hours / 2 = 12 hours), the next request will update the cache in a background thread, while still returning results instantly from the existing cache. When updated, the old cache value is updated and the cache timeout reset. 
This also keeps track of whether an update is already in progress, and prevents python from spawning multiple threads to update the same thing.
---
Also some minor cleanup of main.py
> A smarter osv.dev website caching implementation

- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
Issue: #2152 
This PR introduces a new GET vulnerability details API
> Create get vulnerability details API

- deployment/terraform/modules/osv/gcp_apis.tf
- deployment/terraform/modules/osv/main.tf
Fun fact: You can't actually remove App Engine from a Google Cloud project (without deleting and re-creating the whole project).
I've experimented with this on a test project - deleting the App Engine resource doesn't seem to do anything besides making Terraform stop tracking it. We can manually disable the App Engine application in the GCP UI, which won't delete our data.
> Remove App Engine from Terraform

- tools/datafix/reimport_gcs_record.py
It turns out that trying to reimport a subsequently non-existent record (i.e. when the originating CVE was rejected), the source file no longer exists in GCS and the retrieval failure raises an exception, which is being silently caught, which then caused the transaction to terminate.
So don't silently catch exceptions, other than the general one used to terminate in dry-run mode.
Also removed unnecessary copy-pasta for this program's use case (it's hard-limited to 30 records at a time due to Datastore query limits, so batching makes no sense).
> Fix a bug that causes premature termination of processing

- tools/datafix/delete_bugs_with_source.py
- tools/datafix/delete_invalid.py
- tools/datafix/withdraw_invalid.py
Avoid any copy pasta fails if someone cribs from one of these for a future script and replicate the exception handling fix from #2283 to all the scripts.
> Replicate the exception handling fix from #2283

- docs/api/get-v1-vulns.md
- docs/api/post-v1-determineversion.md
- docs/api/post-v1-query.md
- setup.py
https://github.com/google/osv.dev/issues/1637: Add case sensitive requirement to API docs 
https://github.com/google/osv.dev/issues/2281: Update Python required version to 3.11+
> Update docs to reflect API case sensitivity and python version

- docs/faq.md
Add a line break to prevent a section being considered part of the previous one.
Also fix a minor grammatical inconsistency.
> Fix incorrect formatting in the FAQ

- gcp/appengine/generate_sitemap.py
- gcp/appengine/generate_sitemap_test.py
This change:
- Adds a route to dynamically generate sitemap.xml on the first request.
- Implements caching mechanism to serve the generated sitemap.xml from the directory on subsequent requests.
- Updates the Flask app to include the generate_sitemap function.
- Ensures the sitemap is generated during the initial deployment and reused afterward.
This change improves the SEO functionality by ensuring the sitemap is always available and up-to-date, with minimal performance overhead.
issue: #1639
> Add dynamic sitemap generation route and caching mechanism

- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
While investigating some schema violations, I noticed that #2280 was adding empty Event structs when there were multiple non-`introduced` events for a repo.
Clean up some dead code that the static checker was complaining about.
> Prevent invalid empty Events from being added by AddPkgInfo()

- deployment/clouddeploy/gke-workers/base/generate-sitemap.yaml
- deployment/clouddeploy/gke-workers/base/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/generate-sitemap.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/kustomization.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/generate-sitemap.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/kustomization.yaml
- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/main.tf
- deployment/terraform/modules/osv/variables.tf
- deployment/terraform/modules/osv/website.tf
- docker/cron/generate_sitemap/generate_sitemap.py
- docker/cron/generate_sitemap/generate_sitemap_test.py
- gcp/appengine/frontend_handlers.py
Set up sitemaps generation on a cronjob to a bucket.
The bucket is served via the load balancer on paths prefixed by `/sitemap_`
This PR contains:
- New bucket for prod and test
- New bucket backend for serving assets
- Load balancer config to redirect requests to the bucket backend when appropriate
- Cron config for prod and test
> Set up sitemaps 

- osv/tests.py
- Unbreak the tests for https://github.com/google/osv.dev/pull/2244
- https://github.com/libgit2/pygit2/blob/master/CHANGELOG.md#1150-2024-05-18 states that the deprecated `object.oid` has been removed in favour of `object.id` (it would be nice to have a way to surface deprecated but not decommissioned usage so this didn't need to be done so reactively)
- Tidy up some whitespace
> Prepare for pygit2 1.15.0

- docker/exporter/exporter.py
Might fix https://github.com/google/osv-scanner/pull/1007#issuecomment-2164464087
Sort the entries before adding to the zip archive.
> Sort zip in exporter

- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
- osv/__init__.py
- osv/ecosystems/_ecosystems.py
This change adds deps.dev link for supported ecosystems in the vulnerability page.
- Implemented a check against a map of supported ecosystems to ensure compatibility with deps.dev.
- Added functionality to generate a link to deps.dev for packages if they're supported.
resolves https://github.com/google/osv.dev/issues/1551
Sample output:
> Add a link to dep.dev for the supported ecosystems

- vulnfeeds/git/repository_test.go
Add additional signposting to help unfamiliar users troubleshoot unexpected test failures
> Disable test case failing due to Internet dependency outage

- gcp/appengine/Pipfile
- gcp/appengine/Pipfile.lock
- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
> Add severity column to vulnerability list

- gcp/appengine/frontend3/src/styles.scss
issue: https://github.com/google/osv.dev/issues/1013
This change:
- declares the height of search box to avoid layout shift
- declares the size of published sorted arrow icon
- declares the height of text fields above the turbo frame
Before:
After:
> Fix layout shift in list page

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
Prior to this change, when the introduced version in the affected range was 0, the tooltip displayed: "The exact introduced commit is unknown".
This change, updates the html block to be more readable, and displays a more descriptive tooltip based on the type of the range, indicating if it has versions or commits.
resolves: https://github.com/google/osv.dev/issues/2336
Sample output for GIT range:
Sample output for other type of ranges:
> Display the correct introduced event tooltip

- osv/ecosystems/haskell.py
- osv/ecosystems/haskell_test.py
Test failure due to #2367 is preventing anything getting merged.
> Temporarily disable GHC test

- gcp/appengine/frontend3/src/styles.scss
- gcp/appengine/frontend3/src/templates/vulnerability.html
- gcp/appengine/frontend_handlers.py
resolves https://github.com/google/osv.dev/issues/2254
This change applies the following changes to both severity details in the body as well as affected ranges:
- displays severity base score and rate score in vuln page
- adds link to external cvss calculator (FIRST website)
Before:
After:
> Issue 2254/add link to cvss calculator

- osv/ecosystems/haskell.py
- osv/ecosystems/haskell_test.py
Fixes #2367 
We were using `per_page=-1` on the GitLab tag get request to get every tag for GHC enumeration. That recently stopped returning every tag.
Changed it to query for each page, per  https://docs.gitlab.com/ee/api/rest/index.html#pagination-link-header
> Handle pagination of GHC enumeration

- docker/worker/poetry.lock
- gcp/api/poetry.lock
- gcp/appengine/poetry.lock
- gcp/functions/pypi/poetry.lock
- poetry.lock
- tools/datafix/poetry.lock
We need to rerun poetry lock when pyproject.toml changes, (this will almost certainly be caught by tests when we enable this by default). I didn't do that in the previous PR, so doing it now.
> Relock all poetry files

- gcp/appengine/frontend3/src/styles.scss
Because of how our font (Overpass?) looks, it causes the text to feel too high in a tag. This tries to add some manual padding to push it down.
Before:
After:
> Fix tag styling on frontend

- gcp/appengine/frontend3/src/styles.scss
Updated code card styles to meet AA colour contrast accessibility standards. This is part of some [recommendations](https://www.notion.so/ackamagroup/OSV-Design-work-May-2024-52c16f640bd640a9a6ad5b6d4bb8721e#40d7a1b9587040019c2c051b025a66dc) discovered through some accessibility analysis.
> style(gcp/appengine/frontend): changed style of codecard to improve usability

- gcp/appengine/frontend3/src/base.html
- gcp/appengine/frontend3/src/styles.scss
@another-rex first contribution here!
We may need to expand on this, but briefly, improving accessibility of the front end. There are more suggestions where this one comes from. Not sure if this document has free access: https://www.notion.so/ackamagroup/OSV-Design-work-May-2024-52c16f640bd640a9a6ad5b6d4bb8721e?pvs=4#40d7a1b9587040019c2c051b025a66dc
Added icon to external links, I'm using the one that is already used on the website, to enhance navigation. This icon would indicate external links within the top main tab.
> chore(gcp/appengine/frontend3): tabs anchor with external icon and target blank

- gcp/api/Pipfile
- gcp/api/pyproject.toml
Reverts google/osv.dev#2379
Our deployments have been failing because this update had conflicting dependencies on protobuf.
> Revert "chore(deps): lock file maintenance api"

- docs/data.md
Refresh for current sources
Currently excludes linking to REST API-based sources. Open to suggestions on how best to link to these.
> Add missing sources and ecosystems

- osv/impact.py
Learned about https://docs.python.org/3/library/exceptions.html#BaseException.add_note via go/python-tips/067
and since I've been looking at this code recently, knew exactly where to use it.
Fixes: #1821
> Annotate any exceptions with the vulnerability ID

- .github/workflows/staleness.yml
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label
> Anyone with triage access to a repository can apply and dismiss labels.
> Exempt backlog label from stale treatment

- .github/workflows/lint.yaml
- Makefile
- docker/importer/run_tests.sh
- docker/worker/run_tests.sh
- gcp/api/run_tests.sh
- gcp/appengine/run_tests.sh
- run_tests.sh
- tools/sourcerepo-sync/run_source_update.sh
- tools/sourcerepo-sync/run_tests.sh
Pipenv doesn't automatically check if the `Pipfile` matches the `Pipfile.lock` when running `pipenv sync`. Added `pipenv verify` commands in all the places to do the manifest/lockfile verification. This should prevent things like #2379 from passing our tests.
Poetry seems to automatically do this validation when you run `poetry install` (But there is a `poetry check` command as well?)
> Run `pipenv verify` before sync

- docs/faq.md
I'd like to link to this in outreach emails, and make it more self-contained as the initial introduction to OSV.
> Tighten up the initial FAQ entry

- source.yaml
- source_test.yaml
Ubuntu has recently published a bunch of records with CVE IDs which is causing problems for us.
Explicitly ignore them for now.
> Ignore CVE IDs from Ubuntu

- source.yaml
- source_test.yaml
Manually (tediously) replicate the moral equivalent of #2434
Correct a couple of late-discovered errors in #2434
Remove some redundant entries in some of the sources.
Validation:
```
$ grep -c  -- 'ignore_patterns' source_test.yaml
23
$ grep -c  -- '- name:' source_test.yaml
23
$ grep -c  -- 'ignore_patterns' source.yaml
24
$ grep -c  -- '- name:' source.yaml
24
```
> Propagate prefix filtering to Production

- gcp/appengine/frontend_handlers.py
AlmaLinux has colons in its identifiers, which were not working correctly because the regex didn't match them, and they were being URL encoded.
> Have the shorthand vulnerability redirector handle IDs with colons

- gcp/api/server.py
- Added affected version check for the new API query approach.
- Removed some logs that were added previously for testing purposes.
> fix(api): add enumeration version check

- .github/workflows/staleness.yml
This way they're easily identifiable for later review
Add a nudge to encourage contribution for stale issues.
Convert message text to multiline strings for ease of future maintenance
Aggregate related configuration for ease of comprehension and future maintenance
> Label closed stale issues/PRs

- Pipfile.lock
Renovate bot updated the poetry.lock but didn't touch the Pipfile.lock. Relock the Pipfile manually to update dependencies. https://github.com/google/osv.dev/pull/2412
> Manually lock pipfile

- tools/datafix/reimport_gcs_record.py
Rather than crash and prematurely end an invocation with potentially more bugs left to process, gracefully handle `UnexpectedSituation` exceptions and continue processing the rest of the bugs.
Necessary because there are still some Git-sourced CVEs in Datastore that require reimporting from GCS, and tickle this edge case.
> Don't crash on an UnexpectedSituation

- .github/ISSUE_TEMPLATE/converted-nvd-cve-data-quality-report.md
I've seen many reports using this template that are about GHSA records, not CVE records, so try to reiterate at reporting time what is expected to minimise user confusion and unnecessary work for everyone.
> feat: clarify record type expected for template

- README.md
- docs/third-party.md
More third-party tools are using OSV, making it difficult for us to maintain the OSV third-party tool list. 
- Discontinue maintaining the full list and trim it down to only popular ones (currently those with 900+ stars).
- Update the `pip-audit`/`GUAC` link to its GitHub page to maintain consistency.
> docs: update third party tool list

- docker/worker-base/Dockerfile
- gcp/api/Dockerfile
- gcp/appengine/Dockerfile
- vulnfeeds/tools/debian/Dockerfile
This should fix the current API and osv-website deployment failure.
> Generation 1 of cloud run overrides the HOME environment variable, causing
> poetry to run in the incorrect environment, as it defaults to using `$HOME/.cache/poetry/virtualenvs/...`
> 
> This forces it to create the virtualenv in the same directory as the project, avoiding this issue.
https://cloud.google.com/run/docs/known-issues#home
> fix: Fix cloud run images by having poetry install the virtualenv directly into the project directory.

- gcp/appengine/Dockerfile
Followup to #2476 osv-website docker is a multi-stage build. This moves the environment variable to the correct stage.
> fix: the environment variable is set in the wrong appengine build stage

- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- vulnfeeds/cmd/combine-to-osv/Dockerfile
- vulnfeeds/cmd/combine-to-osv/main.go
Given that we're seeing the GCS copy phase at the end of the execution
of combine-to-osv overrun the current CronJob:
- allow the CronJob to run concurrently, on the assumption that they
will be operating on different sets of files concurrently, in the
worst case scenario
- double the maximum runtime to 4h to prevent premature termination
- don't restart on failure, to advoid masking failures and on the
assumption the next scheduled run will be "soon enough"
Pin Cloud SDK at [485.0.0](https://cloud.google.com/sdk/docs/release-notes#48500_2024-07-23) to test the hypothesis that something was introduced in [486.0.0](https://cloud.google.com/sdk/docs/release-notes#48600_2024-07-30) that caused a latency regression.
Also add some additional instrumentation to what gets logged so we have data …
> fix(combine-to-osv): attempt to work around execution latency problems

- vulnfeeds/cmd/combine-to-osv/main.go
https://github.com/google/osv.dev/pull/2388 significantly increased `combine-to-osv` runtime and caused job failures. Remove the URL validation to reduce time.
Follow up PR: run all HTTP request parallelly.
> fix: remove security tracker URL validation to reduce job runtime

- CONTRIBUTING.md
add [Git conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) requirement to keep commit history clean.
> docs: add Git conventional commit requirement

- docker/terraform/Dockerfile
- vulnfeeds/cmd/alpine/Dockerfile
- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/cpe-repo-gen/Dockerfile
- vulnfeeds/cmd/debian-copyright-mirror/Dockerfile
- vulnfeeds/cmd/debian/Dockerfile
- vulnfeeds/cmd/download-cves/Dockerfile
- vulnfeeds/cmd/nvd-cve-osv/Dockerfile
- vulnfeeds/tools/debian/Dockerfile
A recent apparent GCS performance regression in the Cloud SDK highlighted uncontrolled upgrading of the Cloud SDK Docker image. Pin everything to what #2480 pinned to for stability.
> fix(build): pin all usage of cloud-sdk image

- docs/osv_service_v1.swagger.json
The addition of `CVSS_V4` in #2312 did not add it to the Swagger documentation.
Open to suggestions on how to guard against such divergence in the future.
Fixes: #2485
> fix(api): add CVSS_V4 to API Swagger documentation

- vulnfeeds/tools/debian/Dockerfile
The switch from `google/cloud-sdk:449.0.0-alpine` to `gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine` was not a drop-in replacement:
This moved from Alpine 3.18.4 to 3.20.2 and 3.20.2 is more intolerant of the `pip install poetry==1.8.3` being performed:
```
error: externally-managed-environment
```
Install Poetry via `apk` instead.
> fix(build): install Poetry via apk instead of pip

- renovate.json
Currently grpcio being updated is causing dependency resolution failure because grpcio and google-cloud dependencies depend on non overlapping protobuf versions. Until google-cloud updates to protobuf v5 , we should add this exclusion to stop renovatebot from attempting to update grpcio.
> fix(workflow): Disable grpcio updating until support for new protobuf gets added to google-cloud

- deployment/clouddeploy/gke-workers/base/exporter.yaml
The large number and size of records coming from Ubuntu made our exporter job start exceeding the memory limit.
Throw some more memory at the problem until it goes away.
> fix: bump exporter memory allowances

- deployment/terraform/modules/osv/osv_api.tf
- gcp/api/server.py
- Refactored the code to take in a cutoff time and place all the shared logic in a context method.
- Separate out batch query time limit and normal query time limit, as they have very different behavior. The batch query can and should be longer as it does not return all the details, the `to_response` step after the initial query takes much less time compared to the full response. Batch query also takes longer in general in the querying step compared to normal queries.
- Bump up the envoy_connection_buffer_limit_bytes by 10x. I'm not sure what impact this will have, but currently the responses made by the ubuntu query will exceed the previous limit (10mb to 100mb limit).
At 30 seconds, the current query might timeout on a fresh instance (fresh datastore connection, no JIT optimisations …
> fix(api): Reduce dynamic paging time to 20 seconds

- osv/ecosystems/maven.py
- osv/ecosystems/maven_test.py
Maven `Version` doesn't support `>=`, causing [version query](https://github.com/google/osv.dev/blob/30d55798022eabb000ecc091f03ec7d5a2002c4a/gcp/api/server.py#L1250) failures. Add the `total_ordering` function to support all kinds of ordering.
> fix: add total ordering to Maven version

- docker/deployment/Dockerfile
- docker/indexer/Dockerfile
- docker/worker-base/Dockerfile
- gcp/api/Dockerfile
- gcp/appengine/Dockerfile
This avoids uncontrolled changes to build dependencies sneaking into our Docker image builds, and is considered best practice.
The Docker Hub expresses both an "index digest" and a "manifest digest". I have used the latter, as this seemed the correct thing to do.
> build: pin remaining unpinned third-party Docker images

- docker/indexer/Dockerfile
The previous hash was resulting in a weird error when pulling the image.
Verified this hash by pulling it locally first.
> build: repin distroless image dependency

- gcp/appengine/frontend3/src/templates/list.html
https://github.com/google/osv.dev/issues/2422
Display "Not specified" if packages is missed in the vulnerability details
Before fix:
Result:
> fix: missing Packages for some malicious packages

- gcp/api/server.py
Re-enable and optimise the query by checking the affected versions first.
> feat: enable new version query approach on test instance

- osv/ecosystems/alpine.py
- osv/ecosystems/alpine_test.py
- osv/ecosystems/bioconductor.py
- osv/ecosystems/bioconductor_test.py
- osv/ecosystems/cran.py
- osv/ecosystems/haskell.py
- osv/ecosystems/haskell_test.py
- osv/ecosystems/maven_test.py
- osv/ecosystems/nuget.py
- osv/ecosystems/nuget_test.py
- osv/ecosystems/packagist_test.py
- osv/ecosystems/pub.py
- osv/ecosystems/pub_test.py
- osv/ecosystems/pypi.py
- osv/ecosystems/pypi_test.py
- osv/ecosystems/rocky_linux_test.py
- osv/ecosystems/rubygems.py
- osv/ecosystems/rubygems_test.py
- osv/ecosystems/ubuntu_test.py
Some ecosystem `sort_key` functions do not validate versions before converting them to their ecosystem-specific formats. This leads to several errors occur when using `sort_key` to compare user-input versions with affected ranges.
Add version validation before conversion to ensure no errors occur.
> fix: handle invalid version input in ecosystem sort_key

- vulnfeeds/cmd/download-cves/mirror_nvd
To address apparent overrun issues (and also hopefully reduce the amount of RAM the job requires) use a more time and memory efficient technique to split the monolithic NVD dump by year.
This avoids creating multiple in-memory arrays of the same data
Refactor invocation for better readability
> fix(nvd-mirror): use a more efficient technique to split NVD by year

- docs/Gemfile
- docs/Gemfile.lock
Manual reproduction of the Ruby dependency update from #2501 that seems to be glitching: https://github.com/google/osv.dev/pull/2501#issuecomment-2298972141
> fix(deps): manually update docs Ruby deps

- deployment/clouddeploy/gke-workers/base/nvd-mirror.yaml
When the NVD API is being flaky, as it often is, and a page of results 503's enough times to cause the whole download to abort, it's highly unlikely that another shot at it from the very beginning is going to complete within the overall deadline, so save the time and network resources for the next regularly scheduled run.
A recent failed run blew up trying to retrieve offset 100,000 of 261,123 total results, and the second attempt ran into its deadline at offset 50,000.
> fix(nvd-mirror): do not restart on failure

- vulnfeeds/cmd/download-cves/mirror_nvd
This greatly speeds up the completion of this final stage of the mirroring and based on manual testing in Staging, comfortably fits within the existing RAM allowances for the job.
> feat(nvd-mirror): run the year splitting in parallel

- .github/workflows/pr-check.yml
Enforces PR naming to follow with the Git [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- Uses https://github.com/amannn/action-semantic-pull-request to check
- Fails to comply will result in the PR title check failing:
> chore: add PR title check to follow Git commit convention

- osv/ecosystems/_ecosystems.py
- osv/ecosystems/chainguard.py
- osv/ecosystems/chainguard_test.py
- osv/ecosystems/wolfi.py
- osv/ecosystems/wolfi_test.py
Both Chainguard and Wolfi [use the Alpine Package format](https://github.com/wolfi-dev#wolfi-features). Implement the `sort_key()` function for both, using the Alpine version library.
Related to https://github.com/google/osv.dev/issues/2401
> feat(api): support Chainguard and Wolfi version query on test instance

- gcp/api/cursor.py
- gcp/api/integration_tests.py
- gcp/api/server.py
The current paging/cursor implementation is slightly hacky and fails at various edge cases, and for many query types does not work at all, e.g. (queries without ecosystem, semver queries...). 
When initially implemented, the assumption was almost all API calls resulted in one datastore query. This is no longer the case. 
This refactor/rework adds:
- New cursor type
-  which can represent 3 states (Start, End, InProgress) in a type safe way (through enums, thanks for the ideas @michaelkedar @DonggeLiu!)
- Also stores the ndb.Cursor inside
- Also stores which query number the ndb.Cursor is for when there are multiple queries
- can serialise to a page token, and deserialise in a backward compatible fashion.
- Reworked logic to centralise cursor handling to make the code more readable and …
> feat: Proper working cursor

- source.yaml
- source_test.yaml
Correctly permit all expected prefixes (PUB-A was being excluded in error).
Reorder and harmonize so that a side-by-side vimdiff or other comparison more easily surfaces inconsistencies and omissions.
**_Notable retained inconsistency: `rockylinux-rlsa` (prod) vs `rockylinux` (staging), as I think a wholesale source name change will be disruptive?_**
> fix(datasources): correct Android ignore_pattern

- deployment/clouddeploy/gke-workers/base/nvd-mirror.yaml
Given the cron job runs every 2 hours, there's nothing gained by arbitrarily terminating it before that. At 260K records over 130 pages, the best case scenario for *retrieval* alone is ~780 seconds (and growing) and with intermittent failures and retries, could exceed an hour.
And that's before the time taken to split by year.
> fix(nvd-mirror): increase deadline to 2h

- source.yaml
- source_test.yaml
One of the patterns is just slightly different than the others 🥷 , complete coincidence that android also added some new irrelevant json files.
> fix: Fix android ignore pattern subtle regex error

- gcp/api/integration_tests.py
- gcp/api/server.py
- osv/ecosystems/alma_linux_test.py
Add package name check before the affected version check, and filter out unmatched packages.
> fix(api): add package name check

- CONTRIBUTING.md
Update integration test command to the correct one ([`api-server-tests`](https://github.com/google/osv.dev/blob/7ec31bd721f63790ceea0028388d065249b272e4/Makefile#L37))
> docs: update integration test command

- renovate.json
Remove the [`prHourlyLimit`](https://docs.renovatebot.com/configuration-options/#prhourlylimit) to let renovate open as many PRs as needed in its runs on Wednesday mornings.
Also, bumped the [`prConcurrentLimit`](https://docs.renovatebot.com/configuration-options/#prconcurrentlimit) to 20 (from the default of 10), since we seem to currently have 17 pending updates.
Hopefully, this won't be too noisy / too much backlog.
> fix(deps): let renovate open more PRs per week

- gcp/api/server.py
Handle version query without a package
> fix(api): fix invalid cursor error

- vulnfeeds/cmd/combine-to-osv/Dockerfile
To attempt to reproduce previous file transfer latency for debugging
Merge after this week's release to compare Staging performance with Production.
> chore(combine-to-osv): upgrade Cloud SDK to 486.0.0

- vulnfeeds/cmd/combine-to-osv/Dockerfile
We're able to reproduce the GCS performance degradation with 486.0.0, let's see if that's still the case with the latest available version...
> fix(combine-to-osv): trial upgrading Cloud SDK to 491.0.0

- source_test.yaml
Add SUSE and openSUSE source (around 20k records), details: https://github.com/google/osv.dev/issues/2543
SUSE prefixes: `SUSE-SU-` (most records), `SUSE-OU-`, `SUSE-FU-` and `SUSE-RU-`
openSUSE prefixes: `openSUSE-SU-`
Merge after https://github.com/google/osv.dev/pull/2571
> feat: add SUSE/openSUSE source to test instance

- vulnfeeds/cmd/combine-to-osv/main_test.go
- vulnfeeds/cmd/debian/main.go
- vulnfeeds/cmd/debian/main_test.go
- vulnfeeds/test_data/parts/debian/CVE-2017-6507.debian.json
Combine Debian security issues without an urgency tag into OSV. Details: https://github.com/google/osv.dev/issues/2482
This will significantly increase entries to combine-to-osv, and should be merged only after [SDK performance testing](https://github.com/google/osv.dev/pull/2546).
> feat: combine more Debian security tracker data into OSV

- docker/importer/importer.py
- docker/importer/importer_test.py
Some deleted rockylinux-rxsa records surfaced a bug with the handling of deleted GCS records with colons in their ID.
> fix(importer): correctly handle deleted GCS records with colons in ID

- source_test.yaml
The staging instance has no SSH credentials and we aren't writing anything back so don't need to authenticate
> fix(sources): switch oss-fuzz to https

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
The `combine-to-osv` job takes more than 1 hour to write files to the cloud, while `debian-cve-convert` (around 40k files) takes less than 1 minute. Although `combine-to-osv` processes more files than `debian-cve-convert`, the time difference is excessive.  `debian-cve-convert` uses `gsutil`, and  `combine-to-osv` uses gcloud SDK. 
Attempt to replace `gcloud` with `gsutil` in `combine-to-osv` and conduct performance testing to determine if this improves performance.
The `importer` relies on `blob.time_created` to determine if GSC records need to be re-imported. Updating to `gsutil` should not affect the creation time; only the modification time will remain the same if there are no changes.
> refactor(combine-to-osv): attempt to change `gcloud` to `gsutil`

- gcp/api/server.py
Add a special case for ubuntu entries to reduce the page size by 10x. Because Ubuntu entries are incredibly large.
> fix: Special case paging for ubuntu entries

- .github/workflows/pr-check.yml
I noticed that this hasn't been pinned, which it should be to make scorecard happier
> ci: pin `amannn/action-semantic-pull-request` to a commit

- .github/workflows/codeql-analysis.yml
- .github/workflows/link-checker-on-push.yml
- .github/workflows/link-checker.yml
- .github/workflows/lint.yaml
I noticed that this hasn't been pinned, which it should be to make scorecard happier
> ci: pin `actions/checkout` to a commit

- source.yaml
Add SUSE and openSUSE source (around 20k records), details: https://github.com/google/osv.dev/issues/2543
SUSE prefixes: `SUSE-SU-` (most records), `SUSE-OU-`, `SUSE-FU-` and `SUSE-RU-`
openSUSE prefixes: `openSUSE-SU-`
Test instance PR: https://github.com/google/osv.dev/pull/2570
> feat(data source): add SUSE/openSUSE source to prod instance

- source.yaml
Add [`UBUNTU-CVE-` records](https://github.com/canonical/ubuntu-security-notices/tree/main/osv/cve) into prod instance
Test instance PR: https://github.com/google/osv.dev/pull/2607
> feat(data source): re-enable UBUNTU-CVE- into prod instance

- tools/aliaslookup/aliaslookup.py
I think there was some copy pasta here from another tool, this wasn't doing the right thing when invoked with a list of CVEs.
> fix(aliaslookup): do the right thing with multiple inputs

- .github/workflows/staleness.yml
I noticed that this hasn't been pinned, which it should be to make scorecard happier
> ci: pin `actions/stale` to a commit

- vulnfeeds/cmd/combine-to-osv/README.md
Primarily to better surface how to override an OSV record, originally described in #1604
> docs(combine-to-osv): add basic service documentation

- docker/worker/oss_fuzz.py
It's a follow-up to https://github.com/google/osv.dev/pull/2201. The comments point to https://github.com/google/osv.dev/issues/2178 because the reason is the same.
> fix: update the OSS-Fuzz denylist

- source_test.yaml
The temporary GitHub repo set up for ingestion is using [LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github), which the Importer does not support, so I have copied the repo's contents to an existing GCS bucket for a one-time test import.
> chore(sources): convert Red Hat temporary staging to GCS

- osv/ecosystems/_ecosystems.py
Correct a typo and also a thinko with normalizing fall-through ecosystem names
We'll need to reimport the Red Hat source in Staging once this change is live there.
> fix(ecosystems): treat Red Hat as supported

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yaml
- .github/workflows/scorecards.yml
This updates all actions to their latest major (and mostly minor, though I didn't check all of those) versions along with ensuring that they're pinned to a SHA rather than a version
> ci: update and pin all actions where possible

- docker/importer/importer.py
- docker/importer/importer_test.py
I noticed evidence of GCS upload failures from this while I was scrutinizing an importer run's logs.
> fix(importer): retry oss-fuzz GCS exports

- .gitignore
- vulnfeeds/cmd/debian/main.go
- vulnfeeds/faulttolerant/http.go
I noticed a recent spate of 503s in the error logging that may have benefited from this
> fix(debian): make fault-tolerant HTTP downloads

- docker/importer/importer.py
- docker/importer/importer_test.py
- docker/mock_test/mock_test_handler.py
Use the `Last-Modified` header (or the latest `modified` vuln date if the header is missing) to set the REST SourceRepository's `last_update_date`, instead of using the time when the importer ran.
Should alleviate #2670 for well-behaved REST sources, though it still doesn't handle cases where the source itself adds a record with date before the previous updated date.
While I was here, I also tidied up the `ignore_last_import_time` logic a bit (because the long line splitting was annoying).
> fix: Set `last_update_date` to the time reported by the REST endpoint

- Makefile
- gcp/appengine/Dockerfile
- gcp/appengine/blog/content/posts/announcing-data-quality-initiatives/index.md
Invoke hugo with the `--buildFuture` flag
Also fix year typo in blog post for data quality
> fix(blog): include future-dated content when generating blog

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/main_test.go
The repo caching validates repos are usable for tag to commit mapping (i.e. they have tags) before adding them.
It's possible that a CVE has a commit reference for a repo with no tags (but it's usable as-is because we assume the commit is a Fixed commit).
These repos were not being added to the repo cache, but the repo cache was being used as a short cut by subsequent calls to `ReposFromReferences()`, overwriting the internal state on what repos were known for a CVE with multiple CPEs.
This meant that for CVE-2024-45313, which has multiple CPE entries:
- the `Fixed` commit was being extracted as a reference (as desired)
- the full set of known repos was not being cached
- the versions also extracted didn't resolve (as can happen)
- the CVE was being rejected as having no Fixed commits …
> fix(nvd-cve-osv): handle the edge case of a valid repo reference

- source_test.yaml
Ubuntu CVEs have different URLs than USNs. Separate them into two sources with different human-readable links.
UBUNTU-CVE URL: https://ubuntu.com/security/CVE-2024-47076
USN URL: https://ubuntu.com/security/notices/USN-7045-1
> fix(data source): update human_link for UBUNTU CVEs

- gcp/appengine/frontend_handlers.py
I hit weirdness with an incomplete vulnerability page, which took longer than I'd have liked to get to the bottom of. It was because the source `redhat-stage` was renamed to `redhat` AND the particular record I was looking at had failed to import successfully from the newly named `redhat` source.
This scenario is unexpected enough that it shouldn't be something that happens silently.
> chore(frontend): improve frontend vuln debuggability

- tools/sourcerepo-sync/README.md
- tools/sourcerepo-sync/source_sync.py
Problem:
```
+ poetry run python source_sync.py --kind SourceRepository --project oss-vdb-test --file ../../source_test.yaml --no-dry-run --verbose
Loaded 26 local source repositories
Validated 26 source repositories
Retrieved 26 source repositories from datastore
Traceback (most recent call last):
File "/workspace/tools/sourcerepo-sync/source_sync.py", line 162, in <module>
main()
File "/workspace/tools/sourcerepo-sync/source_sync.py", line 134, in main
validate_repository(ds_repos, False)
File "/workspace/tools/sourcerepo-sync/source_sync.py", line 69, in validate_repository
if 'link' in repo and repo['link'][-1] != '/':
~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```
happening on https://github.com/google/osv.dev/pull/2699 was harder to get to the bottom of than …
> fix(sourcerepo-sync): improve debugability

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
The log line added in #2678 was causing a panic when `vp` is nil (that we didn't notice :facepalm:).
I believe it's causing processing to stop early, so we end up missing records and marking them as 'withdrawn' #2704
Also adding some checks elsewhere where vp might be dereferenced.
Also added the `-e` flag to the run bash script so any other failures stop it from uploading (thanks @another-rex for pointing this out)
> fix(nvd-cve-osv): check for nil when logging `VendorProduct`

- gcp/appengine/frontend_handlers.py
The CVSS calculators throw exceptions when parsing fails, which were uncaught and causing 500's on our website.
> fix: catch exception parsing CVSS scores on frontend

- docker/exporter/exporter.py
https://github.com/google/osv.dev/pull/2707 removed subdirectories from both the ecosystem export functionality and the `ecosystem.txt` list. To ensure a smooth transition for users, keep the `ecosystem.txt` file unchanged for now and then announce this change.
TODO:
- Announce the removal of subdirectories to users
- Remove all ecosystem releases from `ecosystem.txt`
- Update exporter doc
> fix(exporter): revert ecosystem.txt changes

- osv/models.py
Some records will be withdrawn from upstream and may also have their affected package information deleted. These records currently cannot be exported and may cause confusion for our customers due to missing records.  Adding an "EMPTY" ecosystem will represent these records for exporting.
> feat: add an EMPTY ecosystem for withdrawn records

- docker/exporter/export_runner.py
- docker/exporter/exporter.py
Add a ZIP file containing records from all ecosystems to solve https://github.com/google/osv.dev/issues/2423.  Write everything to the default work directory for reuse by the new unified all.zip (instead of using temporary directories). Clean up the work directory afterward.
> feat(exporter): add a unified all.zip

- gcp/appengine/frontend_handlers.py
`[empty]` ecosystem shouldn't be shown on vulnerability/list page
> fix(frontend): hide empty ecosystem

- docker/importer/importer.py
Currently the REST API is entirely silent about what records it is processing. This commit addresses that and makes the instrumentation more in line with the Git and GCS sources, for easier debugging.
> feat(importer): instrument REST API importing

- docker/worker/worker.py
Pathologically large records can be too big for Datastore, resulting in "entity is too big" errors and unhandled exceptions. This is happening for a few of the Red Hat records at present.
This commit handles failures to `put()` the bug in Datastore, and logs the exception with context as to the offending record, to ease debugging.
> fix(worker): handle Datastore exceptions

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/importer-deleter.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/importer-deleter.yaml
Reviewing the logs in staging from the aftermath of #2678, it looks like we need a much lower safety threshold for it provide any value.
```
Counted 53432 parsed vulnerabilities (from 55198 blobs) for cve-osv
1736 Bugs in Datastore considered deleted from GCS for cve-osv
```
20% is still way too high to consider as a normal level of churn.
> fix(importer-deleter): use a 10x lower safety threshold

- docs/faq.md
- osv/models.py
There was some some recent confusion around `modified` time behaviour.
This commit makes it more clear that any future alias group recalculation will result in a change to the record's `modified` time.
> docs(faq): signpost alias calculation impact on modified time

- source.yaml
Ubuntu CVEs have different URLs than USNs. Separate them into two sources with different human-readable links.
UBUNTU-CVE URL: https://ubuntu.com/security/CVE-2024-47076
USN URL: https://ubuntu.com/security/notices/USN-7045-1
Test instance changes: https://github.com/google/osv.dev/pull/2684
> fix(data source): update human_link for UBUNTU CVEs in prod

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
The NVD CVE conversion currently takes about 4 hours to run. This commit adds an afternoon run as well, mostly for the benefit of Staging, where it gives another opportunity for changes to be exercised in the same business day.
> chore(nvd-cve-osv): Run twice a day

- docker/worker/worker.py
- docker/worker/worker_test.py
This commit appears to correctly handle the failure mode encountered in Production with pathologically large Red Hat records, at least with the Data Store emulator.
> fix(worker): handle Datastore exceptions again

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/staging-api-test.yaml
- docker/staging_api_test/perform_api_calls.py
- source.yaml
We recently added more Linux ecosystem records, and the original memory limit is not enough to fetch all vulnerabilities. Increase the memory limit and the runtime."
> fix(staging-api-test): increase memory limit

- vulnfeeds/cmd/nvd-cve-osv/main.go
This commit harmonizes the Cloud Logging log name with the previous naming tidy up done in #1936
> feat(nvd-cve-osv): rename log name

- osv/ecosystems/bioconductor.py
It looks like a previously made assumption was incorrect.
While we're here, remove a workaround -- it seems to work now.
> fix: bioconductor tests.

- osv/models.py
The addition queries to find the related bugs was querying for the whole record, even though it only needs the id.
Changed the queries to grab only the db_id.
> fix: use projection for related queries

- docker/exporter/exporter.py
Follow-up PR for https://github.com/google/osv.dev/pull/2725
TODO:
- Manually remove all ecosystem release directories from the test instance after the code merges (e.g. `Debian:10/`).
- Manually remove them from the prod instance after next week's release.
> feat(exporter): remove distro releases from ecosystem.txt

- deployment/clouddeploy/osv-website/run-prod.yaml
- deployment/clouddeploy/osv-website/run-staging.yaml
The actual change to staging and prod is that memory is bumped to 1024Mi from 512Mi.
> fix: Specify memory and CPU limits for osv-website.

- gcp/api/server.py
We're seeing some 502 and 504 errors reported from API queries. Without the details of each query, it's hard to reproduce and find the root causes. 
Adds logs for the test instance. It does not record actual user queries, only queries from our load tests.
> feat(api): log queries for test instance

- deployment/clouddeploy/osv-api/run.yaml
We are already using 8GB for the past week in prod, this change makes the release not replace it back down to 4GB. 
After this is merged double check staging to see if it correctly updates.
> fix: Double memory for API server

- deployment/clouddeploy/osv-api/run.yaml
https://github.com/google/osv.dev/pull/2799 increased the memory usage from 4Gi to 8Gi, but the deployment failed due to 
> Invalid value specified for container memory. For 1.0 CPU, memory must be between 128Mi and 4Gi inclusive.
> For more troubleshooting guidance, see https://cloud.google.com/run/docs/configuring/memory-limits
Bumps CPU to 2, matches with the current prod setting.
> fix(api): double the CPU for API server

- .gitignore
- deployment/clouddeploy/osv-website/run-prod.yaml
- deployment/clouddeploy/osv-website/run-staging.yaml
Some big records were still causing a memory outage for osv.dev, this increases it up to 4Gb's, the maximum memory limit on one core.
The osv.dev website only uses around ~1-2 instances, compared to our API which uses 20 instances, and is also using 8Gb per instance, so this is pretty small increase in relative cost. 
(The gitignore is for the hurl tool, which allows me to send http requests for testing)
> fix: Upgrade the website's memory limit

- gcp/api/server.py
as even the current 100 is too big (~35mb response size). 50 might not be low enough, and we might want it to be even lower.
> fix: Lower ubuntu linux query paging limit

- Makefile
- gcp/api/test_server.py
Commonly when testing changes for the backend, we want to keep the ESP translation layer up continuously, while rapidly restarting the python code with changes.
This makes it easier to launch just the translation layer.
> feat: Make it easier to launch the api server locally without the backend.

- osv/third_party/univers/README.md
The AboutCode open source projects have recently moved to a new GitHub org
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> chore: Update URL to new AboutCode org

- gcp/appengine/frontend3/src/templates/vulnerability.html
This commit improves the user journey for providing record feedback, by removing the round-trip through the FAQ (when possible) and making the callout to report it directly to the record's source more self-evident.
Part of #2191
Co-authored-by: Rex Pan <rexpan@google.com>
> feat(frontend): improve record feedback user journey

- source_test.yaml
This commit enables #2821 to work for more existing sources by adding additional `human_link` values where they can be determined.
The somewhat gross approach taken for SuSE was chosen rather than adding code implementing a single-use custom filter.
Part of #2191
> feat(sources): add more human_links to staging

- gcp/appengine/frontend3/src/templates/vulnerability.html
This commit addresses post-merge feedback on #2821 and opens the link to the FAQ entry in a new window/tab
> fix(frontend): open FAQ in a new tab/window

- vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
- vulnfeeds/cmd/download-cves/mirror_nvd.sh
- vulnfeeds/cmd/nvd-cve-osv/run_cve_to_osv_generation.sh
This commit adds an error handler to the wrapper script that runs the batch job workload, so that if it fails unexpectedly due to being run with `set -e`/`set -u` we stand a better chance of GCP's error reporting alerting us to it, or at least having additional context in the logs when investigating.
This is because until we get proper k8s job monitoring implemented, we're solely dependent on error reporting alerting us to job failures.
> feat: make critical batch jobs fail more noisily

- renovate.json
This reverts commit eb51576dc242fdcd1142b9e7e89b99029f3adef7.
The original commit did not have the desired effect, and we're now actively seeking assistance from Renovate on
https://github.com/renovatebot/renovate/discussions/32379 so having it further clouds the issue.
> revert(renovate): "fix(renovate): try to improve lockfile PR titles (#2668)"

- vulnfeeds/cves/versions.go
This commit addresses the performance regression introduced in #2836 by only making a remote network request for URLs that have passed initial muster as being appropriately shaped.
(#2836 causes a significant blowout in runtime of a conversion run due to the aggregate latency of all the remote link checking)
> perf(vulnfeeds): validate URLs on a more as-needed basis

- gcp/appengine/frontend3/src/templates/vulnerability.html
- source.yaml
This commit partially replicates the changes from https://github.com/google/osv.dev/pull/2822 to production, adding
additional human_links for records for Rocky Linux (but not yet SuSE), to improve signposting around the desired user journey for data feedback going directly to the source.
It also modifies the frontend to not link out for `openSUSE`-prefixed records, because the approach taken in #2822 doesn't seem to work.
Part of #2191
> feat(sources): add more human_links to production

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/importer.yaml
This only impacts sources that have `strict_validation` enabled for them, such as in #2837
Part of #2188
> feat(importer): enable strict validation in staging

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/importer.yaml
This commit fixes the specification of the `--strict_validation` flag for the importer in staging. It seems #2841 had it wrong, based on:
```
importer.py: error: argument --strict_validation: ignored explicit argument 'True'
```
> fix(importer): correctly specific strict validation flag

- gcp/appengine/frontend3/src/templates/vulnerability.html
This commit addresses the other (more important) location where special casing for openSuSE `human_link` that was overlooked in #2844
Thanks to @hogo6002 for picking up on this.
> fix(frontend): add missing special-case for openSuSE human links

- docs/faq.md
- gcp/appengine/frontend3/src/templates/404.html
- gcp/appengine/frontend3/src/templates/list.html
- gcp/appengine/frontend_handlers.py
This commit modifies the 404 flow so that:
- when a request for a non-existent vulnerability is received, the 404 page reflects the nature of the failed request
- when it is known that the vulnerability failed to import, this is explicitly surfaced
A new FAQ entry discussing this is also added.
Additionally, the 404 generation was tidied up to make it easier to understand where the 404 comes from. There were many unreachable paths that called `abort()`, which made the code unnecessarily unreadable.
It also addresses requests for `/favicon.ico` generating 404's from the redirector by adding an explicit handler for it.
Part of #2190
> feat(frontend): improved UX for missing vulnerabilities

- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/importer.yaml
- tools/source-sync/source_sync.py
This commit:
- Adds support to download all sources concurrently, each in their own thread, rather than sequentially, in the interests of saving time. It emits an interim progress report of which sources are still being downloaded every time a thread completes
- Adds support for an arbitrary number of sources to download other than just all or one of them
- Adds support for excluding an arbitrary number of sources when downloading all of them
- fixes a bug where the `--verbose` flag was not being honoured when downloading all sources.
> feat(source-sync): overhaul behaviour

- docker/importer/importer.py
This commit makes record ID inference more exception-proof by handling all exceptions. Because this function is already being called by the exception handler for a previous failed attempt parsing a record, it is guaranteed to struggle to successfully parse the record under a variety of unknown circumstances, and so raising another exception is not desired.
> fix(importer): avoid raising an exception when handling invalid data

- source_test.yaml
I discovered a human-friendly upstream link for Chainguard's advisories
Part of #2191
> feat(sources): add human_link for chainguard to staging

- vulnfeeds/cmd/pypi/main.go
This is to reduce the chance of introducing false positive matches.
Refs:
- https://github.com/pypa/advisory-database/issues/207
- https://github.com/pypa/advisory-database/issues/205
> pypi vulnfeeds: Support ignoring unbounded vulnerabilities.

- gcp/datastore/index.yaml
https://github.com/google/osv.dev/issues/2790
There are identical indexes defined (L36-L41 and L43-L48) and this PR removes the duplicate one.
> chore: remove duplicate index

- tools/datafix/refresh_ids.py
fix: #2786
This script can also be used if we ever change the key format in the future, we just need to update the check for whether a key needs to be updated or not. 
I'll run this on a machine in the US when merged.
> feat: Add script to refresh IDs to the new format.

- gcp/datastore/index.yaml
We didn't document how to create and clean up indexes, this PR adds the links to `gcloud` documentation.
> docs: update index.yaml with `gcloud` references

- docker/worker/Dockerfile
- gcp/api/Dockerfile
- gcp/website/Dockerfile
#2920 didn't remove them from the `COPY`, builds are failing.
> fix: remove setup.py from Docker files

- docker/exporter/exporter.py
- osv/models.py
- osv/sources.py
For some reason, recently the [EMPTY] ecosystem exporter started failing. The failure is because oss-fuzz special case in the to_vulnerability() code always assumes that there is a project name available. 
This is not the case for withdrawn, public, INVALID status entries, throwing an exception.
I'm not clear on why suddenly it started happening today, when the record has not been changed since 2021. It could have something to do with the Key change done recently, perhaps it was failing at an earlier error because the key was invalid. 
Added some additional logging as well to make it easier to debug the exact record that caused this error next time.
> fix: oss-fuzz + exporter error

- gcp/api/server.py
Only start the cloud profiler for test instance so that we can continue our investigation on this without interrupting production release.
> fix(api): only start cloud profiler for test instance

- docker/worker/worker.py
Follow up on https://github.com/google/osv.dev/pull/2928
Instead of logging the error, raise an exception so that caller is able to add record ID to the error.
> fix(worker): raise an exception for invalid source

- gcp/api/Dockerfile
Install build-essential for Cloud Profiler based on the [instructions](https://cloud.google.com/profiler/docs/profiling-python)
> fix(api): install build-essential for cloud profiler

- source_test.yaml
This enables strict mode in the OSV.dev staging environment for all sources in staging that have been deemed already be publishing 100% OSV JSON Schema compliant records, with the notable exception of the RustSec Advisory Database due to https://github.com/rustsec/advisory-db/issues/2135 and the inclusion of PyPA despite https://github.com/pypa/advisory-database/issues/217 (because of https://github.com/pypa/advisory-database/pull/208)
Part of #2188
> feat: pilot enabling strict mode on all JSON Schema compliant sources

- osv/ecosystems/_ecosystems.py
The [OSV spec](https://ossf.github.io/osv-schema/#affectedpackage-field) requires Alpine packages to have a `:v<RELEASE-NUMBER>` suffix. Currently, our API has inconsistencies regarding Alpine queries:
- It returns a 400 status code with the error message "Invalid ecosystem" for all Alpine package/ecosystem queries without a release number.
- However, for Alpine PURL queries (e.g. 
`pkg:apk/alpine/postgresql14?arch=source`), it returns all matching vulnerabilities across all releases.
Also we recently switched our PURL query from PURL string matching to package/ecosystem matching (https://github.com/google/osv.dev/pull/2900). This change causes all Alpine-related PURL API queries to fail because PURL string doesn't contain any release info and the PURL spec doesn't define how to include …
> fix(api): allow Alpine queries without a release number

- osv/purl_helpers.py
- osv/purl_helpers_test.py
- Refactored `purl_helper.py` to store ecosystem to PURL mapping in one dictionary.
- Implemented PURL converters for all ecosystems mentioned in the issue https://github.com/google/osv.dev/issues/2402 except for Android, Git, Linux, and those not currently shown in OSV (such as Photon OS).
- Android package names (e.g. `/platform/packages/modules/Bluetooth`) can't be converted to PURL
- Git and Linux aren't explicitly mentioned in the standard [PURL spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) (let me know if I've missed any).
- New added PURL converters:
- AlmaLinux, Chainguard, CRAN, GitHub Actions, openSUSE, Red Hat, Rocky Linux, SUSE, Ubuntu, Wolfi
> feat: add more purl converters

- docs/_sass/color_schemes/custom_dark.scss
Our FAQ uses [Just the Docs](https://just-the-docs.com/docs/configuration/) dark mode, but we overwrote the default text and header colour, changing two slightly different colours to all white. This makes our `h3` tags difficult to find. This PR reverts the color scheme settings for headers and body text to improve visibility (slightly different colours between headers and body text).
> fix(faq): Revert custom header color and text settings for better contrast

- docs/_sass/color_schemes/custom_dark.scss
[previous](https://github.com/google/osv.dev/pull/2934) reverted the custom text colour, but because it didn't specify a replacement colour, the text reverted to the default light mode colour. This change sets the default text colour for dark mode.
> fix(ui): set dark colour for FAQ text

- gcp/api/integration_tests.py
- gcp/api/server.py
- osv/purl_helpers.py
- osv/purl_helpers_test.py
fixes https://github.com/google/osv.dev/issues/2960
Although OSV.dev currently doesn't have any `ConanCenter` records, it's listed in the OSV schema. So adding support for ConanCenter PURL query.
The other ecosystems listed in the comments cannot be converted into PURL strings because they are not defined in the PURL spec. Queries for these ecosystems will return a 400 error with an "unknown PURL ecosystem" message
> fix(api): support conan purl query

- gcp/api/integration_tests.py
- gcp/api/server.py
- osv/purl_helpers.py
We didn't have any PURL ecosystem validation until [PR 2900](https://github.com/google/osv.dev/pull/2900) was merged.  [PR 2900](https://github.com/google/osv.dev/pull/2900) introduced some [breaking changes](https://github.com/google/osv.dev/issues/2960#issuecomment-2518943142) that affect users querying ecosystems for which we currently lack a PURL converter, especially those not specified in the PURL specification.
This PR changes the response from a 400 error code to a 200 status code with an empty response unblock users. A more considered design will be discussed later with the team and implemented.
> fix(api): remove all purl ecosystem validation

- gcp/api/server.py
- osv/purl_helpers.py
- osv/purl_helpers_test.py
Related issue: https://github.com/google/osv-scanner/issues/1428
Added support for Go module PURL strings containing `subpath`
> fix(api): handle golang subpath

- osv/ecosystems/_ecosystems.py
- osv/ecosystems/_ecosystems_test.py
- osv/models.py
Related issue https://github.com/google/osv.dev/issues/2963
OSV-Scanner mismatches Ubuntu vulnerabilities due to variations in ecosystem naming (e.g., :LTS, :Pro). 
Adds a function to expand the Ubuntu ecosystem list with all possible variants, ensuring accurate vulnerability matching.
TODO:
> feat: expand Ubuntu ecosystem to include more variants

- gcp/api/server.py
- osv/ecosystems/_ecosystems.py
Resolves https://github.com/google/osv.dev/issues/2963
Updates the API query to support variant-insensitive matching of affected package ecosystem names. A match is found if the package ecosystem name, after removing all variants, is the same as the queried ecosystem name.
TODO:
> feat(api): match ecosystem names without variants

- gcp/api/integration_tests.py
- osv/ecosystems/nuget.py
- osv/ecosystems/pypi.py
- osv/ecosystems/rubygems.py
[Malicious package](https://github.com/ossf/malicious-packages/tree/main/osv/malicious) publishes OSV records for crates.io, npm, NuGet, PyPI, and RubyGems. Queries for NuGet, PyPI, and RubyGems (npm and crates.io use semantic versioning, so the matching process is different) only match vulnerabilities against specific `affected versions`. However, malicious package records may only provide `affected ranges` instead of individual versions in some cases (e.g. https://api.osv.dev/v1/vulns/MAL-2022-7426). OSV also can't enumerate affected versions for a malicious package as those versions have been deleted. This causes issues like https://github.com/google/osv.dev/issues/2407
Switching the API query version matching from `_query_by_generic_version()` to …
> feat(API): update version matching for NuGet, PyPI and RubyGems

- renovate.json
`docker/poetry/requirements.txt` is autogenerated and dependencies are pinned, we probably should not ask renovatebot to update the dependencies in it.
> chore: ignore `docker/poetry/requirements.txt` in renovatebot

- docker/poetry/requirements.txt
Reverts google/osv.dev#3012
though this PR didn't trigger build failure, but we should not update this `requirements.txt`
> chore(deps): revert "update dependency urllib3 to v2.3.0"

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/osv_api.tf
The memory of the API 'frontend' (the ESPv2) was bumped to 2GB manually. Adjusted the terraform configs to do this.
Also updated the ESPv2 base image to the latest version.
> fix: define resource limits on api frontend & update espv2 version

- vulnfeeds/cves/nvd2.go
Even though the NVD CVE API v2 schema says there's a maximum of 500 references, the response given for [CVE-2009-3555](https://nvd.nist.gov/vuln/detail/cve-2009-3555) has 620.
This was causing a fatal error decoding the JSON response, stopping `nvd-mirror` from completing.
I've just manually commented-out the auto-generated length check to remediate this - not sure what the better long-term solution is for this.
> fix(nvd-mirror): remove limit on cve references field

- gcp/api/integration_tests.py
- osv/ecosystems/debian.py
The current Debian's vulnerability matching only checking the affected version. This is a problem for container scanning, as we only enumerate versions during the import from source. So, many vulnerabilities are mismatched if the package is slightly newer than the import time. For example, the `linux` package at version 6.1.112-1 shows about 490 vulnerabilities for Debian 12. but at version 6.1.119-1, it only finds 14 vulnerabilities.
Switching to range matching to check both the affected range and affected versions.
> feat(api): switch Debian version query to range matching

- osv/ecosystems/debian.py
- osv/ecosystems/ubuntu.py
The second argument of a Debian `Version` is supposed to be a string, but we were setting it to an int for invalid versions.
This was causing an exception when comparing two invalid versions against each other in query_by_comparing_versions.
> fix: invalid debian versions causing comparison exceptions

- vulnfeeds/git/versions_test.go
This test started failing recently.
I *think* it's because the tag it was checking against was deleted from the repo, so I've changed it to point to a new, existing tag & commit.
It now passes the tests, but I'm not sure if the test is still testing what it's intending to.
@andrewpollock if you want to take a look when you're back.
> fix: failing vulnfeeds test

- deployment/build-and-stage.yaml
- vulnfeeds/tools/debian/Dockerfile
I missed this in #3003, and looks like poetry on apk is version 1, which broke when we updated to v2
Had to change the debian-convert image to build from the root of the repo to be able to grab the poetry requirements.txt from the docker directory.
> fix: manually install poetry in debian-convert

- gcp/website/blog/content/posts/osv-scanner-v2-beta1-is-ready/index.md
> docs(blog): update OSV-Scanner v2 beta blog post

- source_test.yaml
The original commit lacked an `ignore_pattern`, this commit adds one for consistency with other sources.
> fix(sources): add ignore_pattern for Mageia

- gcp/website/blog/content/posts/automating-and-scaling-vex-generation/index.md
This commit adjusts the link to the executive order to the Biden administration's archive.
The new administration's clean out of whitehouse.gov broke it.
> fix(blog): update executive order link

- deployment/clouddeploy/gke-workers/base/alias-computation.yaml
- deployment/clouddeploy/gke-workers/base/alpine-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/backup.yaml
- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/base/cpe-repo-gen.yaml
- deployment/clouddeploy/gke-workers/base/debian-convert.yaml
- deployment/clouddeploy/gke-workers/base/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/base/debian-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/debian-first-version.yaml
- deployment/clouddeploy/gke-workers/base/exporter.yaml
- deployment/clouddeploy/gke-workers/base/generate-sitemap.yaml
- deployment/clouddeploy/gke-workers/base/importer-deleter.yaml
- deployment/clouddeploy/gke-workers/base/importer.yaml
- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
- deployment/clouddeploy/gke-workers/base/nvd-mirror.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb-test/staging-api-test.yaml
This fixes what was introduced in #3118
Labels must be strings not ints. Based on `terraform plan`, this is no-op, but is intended to address the Cloud Deploy failure encountered.
> fix: labels are strings

- .github/workflows/lint.yaml
- docker/ci/install_go.sh
- docs/go.mod
- gcp/indexer/go.mod
- tools/datastore-remover/go.mod
- tools/indexer-api-caller/go.mod
- vulnfeeds/go.mod
Fixes the reported vulnerability [GO-2025-3447](https://osv.dev/vulnerability/GO-2025-3447)
Is there a way to get renovate/dependabot to do this?
> chore: update Go version to 1.23.6

- gcp/functions/pypi/poetry.lock
- gcp/functions/pypi/pyproject.toml
Resolves [GHSA-79v4-65xg-pq4g](https://osv.dev/GHSA-79v4-65xg-pq4g).
For some reason, dependabot and renovate are failing to do this update, so I've done it manually.
> fix(functions): bump cryptography to 44.0.1

- vulnfeeds/cmd/debian-copyright-mirror/Dockerfile
- vulnfeeds/cmd/debian-copyright-mirror/debian-copyright-mirror.py
- vulnfeeds/cmd/debian-copyright-mirror/debian-copyright-mirror.sh
The k8s CronJob monitoring has highlighted that the debian-copyright-mirror job appears to be overrunning. The wget mirroring approach is grossly inefficient.
This replaces that with a more efficient parallel curl execution, using a YAML file conveniently available to construct the URLs to download.
It sacrifices the attempt at only updating changed files, as this isn't easily possible with curl.
The runtime is now < 10 minutes in local testing!
> fix(debian-copyright-mirror): overhaul for more efficient run length

- deployment/terraform/environments/oss-vdb/main.tf
This builds on #3123 and incorporates #3124 and will be applied as part of the next release of Production.
> feat(monitoring): add notifications to k8s CronJob monitoring in production

- vulnfeeds/git/repository.go
- vulnfeeds/git/repository_test.go
This fixes a bug discovered in the pre-normalization of tags with a v prefix, they were incorrectly running through the Java package treatment and being completely wiped out :-(
Discovered while investigating the unexpected withdrawal of CVE-2023-39631
> fix(vulnfeeds): correct version normalization for tags with a v prefix

- deployment/terraform/modules/k8s_cron_alert/k8s_cron_alert.tf
This adds a severity of ERROR to the generated alerting policies so that the incidents opened have this severity, rather than none at all.
> refactor(monitoring): add a severity to k8s CronJob alerting

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/main_test.go
- vulnfeeds/git/repository_test.go
This commit tightens up the repo validation to exclude repos that don't have any usable tags, unless the reference URL is obviously a commit.
The primary benefit here is that useless repos don't cause CVEs to be in-scope for attempting conversion that shouldn't, while not disregarding CVEs that have a potential fix commit as a reference, but a repo that is otherwise useless for version-to-commit mapping.
In other words, it improves the overall conversion metrics by firming up the denominator some more.
Last staging run against 2025 NVD data:
```
nvdcve-2.0-2025.json Metrics: {TotalCVEs:2870 CVEsForApplications:205 CVEsForKnownRepos:420 OSVRecordsGenerated:188 Outcomes:map[]} 
```
Local regression test:
```
nvdcve-2.0-2025.json Metrics: {TotalCVEs:2876 CVEsForApplications:205 …
```
> feat(vulnfeeds): better validate repos found in references

- source.yaml
This commit enables JSON schema validation enforcement at import time in Production for home databases maintained by OSV.dev.
At this time, no records are currently failing to import in Staging (where this has been enabled for some time).
Part of #2188
> feat(sources): enforce JSON schema validation for OSV.dev-maintained home databases

- gcp/workers/worker/worker.py
This adjusts the latency logging behaviour so that it only happens when a task completes successfully (as opposed to times out, and is subject to being retried).
Fixes: #1871
> fix(worker): only log import latency for non-time outs

- osv/models.py
As the internal data store name for upstream from external sources is 'upstream_raw', it needs to be set properly when received from the sources.
> fix: importer not importing upstream values from sources 

- gcp/workers/alias/run_cron.sh
Change: moved alias_computation and upstream_computation into bash script to be run in the same cron job. 
Chose not to run in parallel out of concern for memory usage.
> feat(cron): Adding upstream calculation to the alias cron job

- gcp/workers/alias/run_cron.sh
Indicate when alias computation starts/ends and when upstream computation starts/ends
> fix(cron): added logging to differentiate alias vs upstream computation in cron

- deployment/clouddeploy/gke-workers/base/exporter.yaml
The exporter is reliably taking >50m to complete, based on recent runs.
This adjusts the monitoring accordingly.
> fix(exporter): accept the current reality of run length

- gcp/workers/exporter/export_runner.py
- gcp/workers/exporter/exporter.py
- osv/models.py
This adds a file size delta function to prevent the unintended overwriting of a file with a significantly smaller one.
It only uses it for the unified all.zip upload at present, as I'm not sure how to identify when to use it for the ecosystem-specific zip files as they seem to be bundled in with the individual record files.
> feat(exporter): add a safe_upload_single function

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
This tightens up what `cves.Commit()` considers acceptable by validating the assumed commit hash from GitHub and GitLab URLs as matching a SHA1 regex.
This prevents tags and tags with ancestry specification from being erroneously treated as a commit hash.
e.g.
- https://github.com/curl/curl/commit/curl-7_50_2
- https://github.com/curl/curl/commit/curl-7_50_2~32
as seen in the likes of CVE-2016-7141
> fix(vulnfeeds): be stricter about acceptable commits from URLs

- gcp/workers/exporter/exporter.py
This fixes a bug in `safe_upload_single` where the existing blob metadata was not available for size calculation.
`bucket.blob()` is just a constructor, `bucket.get_blob()` actually retrieves the existing blob's metadata.
> fix(exporter): correctly retrieve blob metadata

- source_test.yaml
Add V8 advisory to the test environment.
As per internal discussions, we are adding a V8 advisory to OSV.
The Chromium team has a [policy](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/updates.md) that states that direct embedders of Chromium packages such as V8 are responsible for using an up-to-date version of V8 packages. The definition of that is that the V8 package is at most one week old.
Since these types of packages do not have their own identifiers and therefore no advisory could be created, enforcement of such policies was not possible. We now created a synthetic advisory generator that takes such time-based policies and converts them into regularily updated advisories that OSV can read: …
> feat(test): add V8 advisory to test environment.

- source_test.yaml
I noticed that the import source link has "advisories" twice, which breaks the link. I suppose this is because it appends the whole path to the advisory file instead of just the file name, so I removed the advisories subfolder from the link field.
https://test.osv.dev/vulnerability/V8-FRESHNESS
> fix(test): Fix V8 source link.

- Makefile
- gcp/website/frontend_emulator.py
@michaelkedar and I created figured out how to utilize the datastore emulator to mock the data from locally rather than connecting to staging, so that small frontend tests, like checking behaviour consequences of bad data, can be mocked without introducing bad data in staging. 
Future PRs could introduce a better data set and method: for example, a public bucket or being able to upload a zip of OSV vulns to test on. 
For now this suits the purpose of testing behaviour when there are cycles in the graph.
> feat: added a way to locally test frontend changes without connecting to GCP

- source_test.yaml
add Ubuntu LSN to OSV with record prefix `UBUNTU-LSN`
Related: https://github.com/google/osv.dev/issues/3204
> feat: add Ubuntu LSN to staging instance

- gcp/workers/worker/worker.py
This commit includes the record's vulnerability ID in a structured log field for the worker's code path that imports updates to vulnerability records.
After reviewing the current logger behaviour, it was determined that the opportunity exists to add this existing structured log field in more places, to aid with tracing the path of a specific record through the worker.
This is intended to enable filtering logs emitted from `_do_update()` for a specific vulnerability ID by using `jsonPayload.bug_id`
> feat(worker): include vulnerability ID in more logs

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
This fixes a bug in a switch case for multiple selectors that was not working as intended
> fix(vulnfeeds): correct use of switch

- gcp/workers/exporter/exporter.py
- gcp/workers/importer/importer.py
This uses the same technique as #3248 to increase the HTTP connection pool, retries and blocking behaviour on exhaustion for the GCS client used in the importer.
The importer (at least running in deletion mode) is experiencing the same exhaustion issues the exporter was, with lengthy increases in runtime.
> fix(importer): adjust GCS client to reduce HTTP connection exhaustion

- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
This job takes around 6h to complete on a good run, so restarting it multiple times just delays the next regularly scheduled run (which potentially already has a fix in it)
> fix(nvd-cve-osv): do not restart on failures

- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/main_test.go
This fixes a logic error introduced in #3162
That previously was not correctly handling the independent scenarios of the reference containing an extractable commit hash OR the reference being derivable as a valid and usable repository, and was causing CVEs that previously had a valid and usable repository in a reference to no longer have that repository derived for it.
> fix(nvd-cve-osv): regression in reference repo extraction

- vulnfeeds/cves/versions_test.go
Based on the page currently being served by
https://gitlab.freedesktop.org/virgl/virglrenderer/-/commit/b05bb61f454eeb8a85164c8a31510aeb9d79129c
Currently planned outage: 2025-03-16 -> 2025-03-22
> test(vulnfeeeds): freedesktop.org is having a scheduled outage

- source.yaml
This enables strict schema validation for home databases we have an "in-house" affiliation with. No problems have been observed in Staging for records from these home databases where this has been the case since
#2943
Part of #2188
> feat(sources): enable schema validation for more of production

- osv/repos.py
This upgrades the logging to capture the entire exception to assist with future debugging.
Seeing
`Failed to load existing checkout: reference 'refs/heads/master' not found` being logged in conjunction with processing for the `ghsa` source, which seems nonsensical given there's no branch configured anywhere.
> chore: log exception

- gcp/api/Dockerfile
- gcp/website/Dockerfile
This corrects the image digest hash to be the amd64 instead of i386 one, accidentally used in #3260
> fix: use the amd64 python 3.12.8-slim digest

- tools/source-sync/source_sync.py
This fixes the f-string so the source name is emitted as intended
> fix(source_sync): correct output for exceptions

- osv/ecosystems/maven.py
Range matching gives more accurate results than only checking affected versions. In some cases, versions may fail to enumerate and cause false negative query results for users.
same as https://github.com/google/osv.dev/pull/2971
> feat(api): update maven query method

- .github/workflows/staleness.yml
This also treats `backlog` tagged PRs as exempt from auto-closure as stale, just like how issues are treated.
> chore(workflows): exempt autoclosing of backlog tagged PRs

- .github/workflows/staleness.yml
- deployment/clouddeploy/gke-workers/base/exporter.yaml
I *think* the exporter is running into its CPU limit and getting evicted as a result, and the CPU limit seems to be unnecessarily low, given it's running on a highend node with 32 CPUs?
> fix(exporter): increase CPU limit for exporter

- gcp/website/poetry.lock
- gcp/website/pyproject.toml
Should stop GHSA-hc5x-x2vx-497g from showing up in our vuln scanning.
Not sure why renovate/dependabot haven't made this PR (is it because it's a major version update?)
> fix(deps): update gunicorn to 23.0.0

- gcp/website/frontend_handlers.py
Add vanity URL metadata to return when go gets a package from osv.dev.
I think this is set up in a way where in the future we can also add osv-scanner to the vanity URL by putting it on a sub path.
Needs to be merged before #3299 for it to work.
> feat: Add go vanity metadata

- vulnfeeds/cmd/alpine/Dockerfile
- vulnfeeds/cmd/combine-to-osv/Dockerfile
- vulnfeeds/cmd/cpe-repo-gen/Dockerfile
- vulnfeeds/cmd/debian-copyright-mirror/Dockerfile
- vulnfeeds/cmd/debian/Dockerfile
- vulnfeeds/cmd/download-cves/Dockerfile
- vulnfeeds/cmd/nvd-cve-osv/Dockerfile
- vulnfeeds/tools/debian/Dockerfile
Returning to the generic `alpine` tag will enable Renovate to be able to upgrade this image periodically.
This pins to the current latest Alpine google-cloud-cli Docker image (515.0.0, from 2025-03-18).
We had previously pinned to 485.0.0 (from 2024-07-23), due to performance regressions between `gcloud storage rsync` versus `gsutil rsync`.
That version is:
- getting very old
- showing signs of bitrotting with newer Python runtimes
- potentially hiding deprecations that may surprise us
I believe we have re-converged back on `gsutil` for everything currently, and with the additional k8s CronJob monitoring now in place, we should pick up any future upgrades that introduce any new performance regressions.
> chore(vulnfeeds): resume tracking the latest google-cloud-cli image

- deployment/clouddeploy/gke-workers/base/alias-computation.yaml
- deployment/clouddeploy/gke-workers/base/alpine-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/backup.yaml
- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/base/cpe-repo-gen.yaml
- deployment/clouddeploy/gke-workers/base/debian-convert.yaml
- deployment/clouddeploy/gke-workers/base/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/base/debian-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/debian-first-version.yaml
- deployment/clouddeploy/gke-workers/base/exporter.yaml
- deployment/clouddeploy/gke-workers/base/generate-sitemap.yaml
- deployment/clouddeploy/gke-workers/base/importer-deleter.yaml
- deployment/clouddeploy/gke-workers/base/importer.yaml
- deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
This adjusts the restart policy for high(ish) frequency CronJobs from `OnFailure` to `Never`
The thinking here is that restarting a failing pod with the exact same container image (and therefore build of the binary) is unlikely to be helpful in the cases where the problem is a runtime bug in that binary, and it just delays the next scheduled run of what is potentially a newer container image with a fix for the aforementioned bug (or possibly a different k8s specification).
If the problem is transient, the next scheduled run will be "soon enough" to be morally equivalent to just restarting the same pod.
And we have monitoring to still catch any longer-term crash looping that prevents a successful completion.
It also fixes a string quoting issue that the linter was complaining about
> chore(k8s): don't restart failing high-frequency CronJobs

- gcp/website/frontend_handlers.py
Enable upstream/downstream in frontend. 
Merge this when performance is verified in staging. 
Finally closes #3052
> feat(frontend): enable upstream/downstream in prod

- vulnfeeds/cmd/nvd-cve-osv/README.md
This adds documentation on how to access the CSV reports for the latest conversion run from `nvd-cve-osv` and some possible analyses that can be performed on that data
> docs(nvd-cve-osv): how to do CSV-based analysis of conversion

- deployment/clouddeploy/gke-workers/base/alpine-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/combine-to-osv.yaml
- deployment/clouddeploy/gke-workers/base/cpe-repo-gen.yaml
- deployment/clouddeploy/gke-workers/base/debian-convert.yaml
- deployment/clouddeploy/gke-workers/base/debian-copyright-mirror.yaml
- deployment/clouddeploy/gke-workers/base/debian-cve-convert.yaml
- deployment/clouddeploy/gke-workers/base/importer-deleter.yaml
The `importer-deleter` had a cron schedule of `"* */3 * * *"`, so it was trying to run at every minute of each 3rd hour (`00:00`, `00:01`, `00:02`, ..., `00:59`, `03:00`, `03:01`, ...). Changed this to the intended once every three hours `"0 */3 * * *"`.
Also replaced `*/1` in our cron schedules with `*`, which means the same thing.
> fix: make importer-deleter cron schedule run only once within the hour

- gcp/website/frontend3/src/templates/home.html
Turns out we never updated the website to have v2 install instructions.
> docs: Update osv-scanner install instructions on osv.dev to V2

- osv/models.py
Being able to see downstream vulns is valuable to users who are searching a CVE.  Closes #3348
> feat(search): Added upstream_raw to search indices

- source_test.yaml
Looking into #3353, testing analyzing these on the test instance.
I believe this requires a re-import of all the CURL records.
> fix: analyze git commits from curl on test instance

- gcp/website/frontend_handlers.py
- osv/models.py
When a user searches for a specific vulnerability ID, that should be the first record that shows up, not just the most recently updated record. 
As such we added some extra ordering on record results: the ID given > alias of the ID > in the ID's downstream > related to the ID.
May need to add functionality in the future for also including the ID's upstreams. Unfortunately, this only works 100% as intended with one page of results.
> feat(frontend): Added weighted search results

- gcp/api/server.py
- gcp/website/frontend3/src/templates/list.html
- gcp/website/frontend_handlers.py
There are bad value errors reported for some queries:
```
BadValueError: Indexed value must be at most 1500 bytes
```
To fix this, this PR caps the length of the string value reported to a reasonable length.
> fix: cap the length of string values in query

- vulnfeeds/cmd/download-cves/main.go
Found this oddity in our logs:
```
INFO 2025-04-23T14:10:28.514799134Z Retrieved offset 118000 of 291146 total results
WARNING 2025-04-23T14:10:35.258238369Z Bad response for "https://services.nvd.nist.gov/rest/json/cves/2.0?startIndex=120000": "500 ", retrying
INFO 2025-04-23T14:10:41.302392482Z Retrieved offset 120000 of 770 total results
```
The NVD API returned many missing results, meaning we exit early. This propagates through our jobs and eventually makes us attempt to delete many CVE records.
As a simple fix, just error if the total number of results reduces during the nvd-mirror run, which should make the cron job fail and restart.
> fix: fatally error if NVD API returns less total results

- vulnfeeds/cves/versions_test.go
These vulnfeeds tests have been inconsistently failing. I've temporarily skipped these until June so we don't block other PRs.
I think there's some rate limiting going on with GitHub. but I'm not sure what the long-term fix is for this.
> fix: temporarily disable some flaky tests

- deployment/clouddeploy/gke-workers/base/alias-computation.yaml
The upstream computation was being killed for using too much memory.
(For some reason, GKE does not consider this a failed cron...)
> fix(workers): bump memory limits on alias/upstream cron

- osv/ecosystems/_ecosystems.py
- osv/ecosystems/minimos.py
- osv/ecosystems/minimos_test.py
ref: #3400 
Adding a ecosystem helper for the new `MinimOS` ecosystem, which appears to use standard APK-based versioning.
This is identical to the `Wolfi`/`Chainguard` helpers.
Also updated the osvschema submodule to pick up the `MinimOS` ecosystem.
> feat: add MinimOS ecosystem helper

- gcp/api/integration_tests.py
A vuln appeared in the range for which a test assumed there would be no vulns. This should put it back into the range of non-existence.
> fix(integration-tests): Update integration_tests.py

- .gcloudignore
- cloudbuild.yaml
- gcp/api/cloudbuild.yaml
- gcp/website/cloudbuild.yaml
- gcp/workers/cloudbuild.yaml
- gcp/workers/worker/.gcloudignore
- osv/cloudbuild.yaml
- osv/tests.py
- vulnfeeds/cloudbuild.yaml
#3452 Step 1 for running tests only on relevant PRs.
I've created a different `cloudbuild.yaml` file for a bunch of our components - basically each lockfile has its own file.
After this is merged, I'll split up the PR triggers to only run on the relevant files (that I've listed in the yaml files).
I've also made a slight change to the datastore emulator to allow the worker/importer tests to be run in parallel.
> test: split Cloud Build tests into multiple builds

- gcp/website/frontend_emulator.py
- gcp/website/frontend_handlers.py
Closes https://github.com/google/osv.dev/issues/760
Intended behaviour:
For an ID that we do not have in our datastore, that is part of an alias group with 1 other vuln, using /{vuln-id} will redirect to the other alias vuln. If there are more aliases in the group, or no alias at all, the user will be rerouted to the search query page, with the chance of finding a relevant downstream vuln. 
Current best example is CVE-2024-40120. this may change if we import the record at some point.
Also updated the emulator with some examples to test.
> feat(frontend): Added rerouting for aliases and queries 

- docker/ci/Dockerfile
After spotting a deprecation warning the other day, I tried rebuilding the ci image and got:
```
ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 21+ JRE. The Google Cloud Datastore emulator requires a Java 21+ JRE installed and on your system PATH
```
So I'm bumping the jdk version (will manually push new image)
> ci: bump JDK to version 21 in ci image

- osv/sources.py
Use correct timezone, and write timestamp to avoid ValueError from records with no modified time.
> fix: Use correct timezone, and write timestamp directly

- source.yaml
- source_test.yaml
because of human_link.
E.g. https://osv.dev/vulnerability/ALEA-2021:4152
Tested the fix locally by changing the human_link value in memory while debugging the website locally.
> fix: Fix 500 error where empty records would fail to render 

- bindings/go/osvdevexperimental/paging.go
`dpe` may be nil which could case nil pointer error. 
also the new `errToReturn` should be returned otherwise the nil `dpe` is returned.
> fix(bindings): return the right error in query paging

- source.yaml
- vulnfeeds/cves/cve.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/pypi/pypi.go
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
These changes are done in preparation for CVEList ingestion 
- Refactor description logic to only require the array of descriptions rather than whole CVE, for better reusability
- Made a few functions public to use in other sections of the code.
- Updated tests
> refactor(vulnfeeds): Refactor descriptions for better reusability and make versioning functions public

- bindings/go/osvdev/osvdev.go
If the code timeouts before reaching the http client code, we don't correctly return a timeout exceeded error.
> fix: context error not being correctly returned

- docs/new_source.md
I've seen some usage of our new data source doc, so I'm adding an extra step of linter checking before importing everything into production.
> docs: add checking linter results step into new_source.md

- gcp/api/integration_tests.py
[CVE-2024-40120](https://osv.dev/vulnerability/CVE-2024-40120) is now in OSV so we need to update the test with another CVE.
> test: update integration test case

- Makefile
This PR adds `build-protos` to Makefile so we don't need to go to `osv` folder to run the script.
> chore: add build-protos to Makefile

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
Found an existing vulnfeeds commit compare function, so removing the redundant code.
> refactor(vulnfeeds): Remove redundant ByAffectedCommit code

- deployment/clouddeploy/osv-api/run.yaml
- gcp/api/server.py
Bump the max concurrent requests from 5 to 10 for the API backend, to help with container instance scaling.
This is not for the batch query backend, which still is just 1.
Hopefully this won't have a notable performance impact. I don't really want to change this and #3638 at the same time, since I want to be able to measure the individual impacts of both. We could probably push this out with the release this week, and let #3638 stage until next week.
> fix(api): double backend concurrency

- gcp/api/server.py
- osv/models.py
Change all(?) the ndb calls used throughout the API handlers to use the async versions, and rewrote a few functions to not block on the completion of futures that it doesn't need to (particularly, converting the Bug to a proto, and populating the related/alias/upstream fields of those protos).
Testing on my private instance, this should be a 3-5x speedup for queries with lots of vulnerabilities.
I've also made the batch queries properly set the modified time from the alias/upstream group (which might actually be a tiny performance loss) to ensure the modified time is always the same for the batch query and the get by ID.
I've added `@ndb.synctasklet` to the rpc handlers to let us use `yield` instead of `.result()`, just to discourage usage of it (using `.result()` in a tasklet can cause …
> perf(api): Improve asynchronous behaviour

- gcp/api/integration_tests.py
[CVE-2025-7207](https://osv.dev/vulnerability/CVE-2025-7207) is a new bug on `github.com/mruby/mruby`.
> test: update API integration test

- .github/workflows/osv-scanner-unified.yml
OSV-Scanner hasn't run on OSV.dev successfully in ~ 4 months. It seems to be missing read permissions. Hopefully this fixes it?
> fix(actions): Update osv-scanner-unified.yml with read permissions

- gcp/workers/linter/linter.py
https://github.com/ossf/osv-schema/pull/365 added a new check on JSON schema validation with new error code https://github.com/ossf/osv-schema/blob/b79744b3c60d0ccbd77e46adc1214dda7c547072/tools/osv-linter/internal/checks/schema.go#L18
adding this error code to linter cron job
> feat(linter): add invalid schema error code

- gcp/workers/linter/linter.py
OSV-schema added JSON schema checks which increased the runtime of OSV-linter. To address linter timeout issues, we can either increase the timeout limit or download all.zip files from different ecosystem buckets and run OSV-linter in multiple threads. 
For now, I will simply increase the timeout limit first, as the cron job only runs once a day and JSON schema checks should only increase the runtime slightly. Let's see how long it takes before splitting it into multiple threads.
> chore(linter): bump timeout limit

- osv/impact.py
- osv/repos.py
Since (in most cases), we do not actually need the repo contents to enumerate git commits, changed the impact analysis to not download blobs when cloning (via [`--filter=blob:none`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---filterfilter-spec)) if it can be avoided.
Testing locally on a few random-ish repos in OSV, seems to be a decent improvement:
|repo|full clone|blobless clone|
|:-:|:-:|:-:|
|https://github.com/v8/v8|360s|70s|
|https://github.com/curl/curl.git|12s|5s|
|https://github.com/mysql/mysql-server|430s|120s|
|https://github.com/libexif/exif|**2.5s**|**3.5s**|
|https://github.com/microsoft/chakracore|17s|7s|
|https://github.com/powerdns/pdns|12s|6s|
It seems like on small repos, it actually takes longer (maybe because git has to first check if the repo …
> perf: perform blobless clones in git enumeration

- vulnfeeds/cmd/combine-to-osv/main.go
- vulnfeeds/cmd/nvd-cve-osv/main.go
- vulnfeeds/cmd/pypi/main.go
- vulnfeeds/vulns/vulns.go
- vulnfeeds/vulns/vulns_test.go
Renamed it "FromNVDCVE" to prepare for CVE5 version that will also do a similar thing.
> refactor(vulnfeeds): Change FromCVE function back to taking whole CVE entry

- deployment/terraform/environments/oss-vdb-test/main.tf
- deployment/terraform/environments/oss-vdb/main.tf
- deployment/terraform/modules/osv/gcp_apis.tf
- deployment/terraform/modules/osv/osv_api.tf
- deployment/terraform/modules/osv/scripts/gcloud_build_image
Couple of small changes to our terraform config:
- Added a couple of required GCP APIs that were missing
- Added a `--gcs-log-dir` arg to the Cloud Build command that is run to build the ESPv2 image (required with some internal policies)
- updated ESPv2 version to latest
> fix: minor terraform changes

- docs/api/index.md
- docs/api/post-v1-query.md
- docs/faq.md
Updated the API documentation to warn users of API response limit on HTTP/1.1 and recommend using HTTP/2 for large queries.
Fixes #3119
> docs(api): Warn users about API response size limit

- .gitignore
- gcp/workers/exporter/export_runner.py
- gcp/workers/exporter/exporter.py
Resolves #3671
This outputs a `modified_id.csv` in this format in each ecosystem directory:
```
<iso modified date>,<id>
```
Then a `modified_id.csv` at the top level containing all vulns:
```
<iso modified date>,<ecosystem_dir>/<id>
```
No deduplication is done between ecosystems.
> feat: Export a modified_id.csv

- gcp/workers/alias/alias_computation_test.py
- gcp/workers/alias/upstream_computation_test.py
- osv/gcs.py
- osv/gcs_mock.py
- osv/models_test.py
In #3708, writing both JSON and protos is proving to be fairly expensive.
Just write the `.pb`s - we can make other jobs make the JSON files later.
> fix: only write live proto vulns to bucket

- bindings/go/osvdevexperimental/paging.go
- bindings/go/osvdevexperimental/paging_test.go
Test this implementation a bit more, and also makes it easier for users to mock their own tests as well.
This is to support the work done on moving osvmatcher to osv-scalibr.
> test: osvdevexperimental mock paging interface

- bindings/go/go.mod
- docs/go.mod
- gcp/indexer/go.mod
- tools/datastore-remover/go.mod
- tools/indexer-api-caller/go.mod
- vulnfeeds/go.mod
Should fix the vulnerability osv-scanner is reporting in the docs go.mod file.
> chore(deps): bump go to 1.24.6

- gcp/api/server_new.py
- osv/gcs.py
Calling `logging.exception` causes the error reporting dashboard to flag the log, even though 404s are sometimes expected (by e.g. GetByID for an invalid ID)
> fix(staging): make GCS 404 less noisy

- gcp/website/frontend3/src/linter.scss
- gcp/website/frontend3/src/templates/linter/index.html
The webpack production build removes type="text" from inputs, since it's the default and seen as redundant. This broke the styling for the linter search input, which was using the selector `.search-box input[type="text"]`. 
This PR fixes the issue by updating the selector to `.search-box input`, which works correctly in all environments without needing complex Webpack configuration changes.
> fix(frontend): fix search input style for linter dashboard

- gcp/workers/staging_api_test/perform_api_calls.py
- osv/ecosystems/bioconductor.py
- osv/ecosystems/bioconductor_test.py
- osv/ecosystems/haskell.py
- osv/ecosystems/nuget.py
- osv/ecosystems/semver_ecosystem_helper.py
Two things:
- Fixed some semver ecosystems raising an error on `sort_key`, instead of returning a very large number
- Fixed the staging api test job using `None` as a version if no version was found, instead of the intended placeholder.
> fix(staging): minor API fixes

- vulnfeeds/cmd/cvelist2osv/main_test.go
#3808 broke a test that was created in #3747
This wasn't caught before the merge because the base branch was outdated :/
> fix(tests): Fix failing vulnfeeds test

- gcp/api/Dockerfile
https://github.com/google/osv.dev/pull/3827#pullrequestreview-3149847806
> chore: remove now unnecessary `build-essential`

- .gitmodules
- renovate.json
Trying to get renovate to only use tagged versions of osv-schema [from their docs](https://docs.renovatebot.com/modules/manager/git-submodules/#updating-to-specific-tag-values). We won't really see how this works until we need to release a new osv-schema version.
One thing to keep in mind:
> **Note:** Using this approach will disrupt the native git submodule update experience when using `git submodule update --remote`. You may encounter an error like `fatal: Unable to find refs/remotes/origin/v0.0.1 revision in submodule path...` because Git can only update submodules when tracking a branch. To manually update the submodule, navigate to the submodule directory and run the following commands: `git fetch && git checkout <new tag>`.
Also, we probably need some way to have the schema version …
> chore: enable git submodule updates with renovate

- vulnfeeds/cmd/cvelist2osv/main.go
- vulnfeeds/cmd/cvelist2osv/version_extraction.go
We can make better informed decisions about which parts of which CVE records we can merge with more information about where the version information was converted from. 
This will add a list of strings to the metrics file, based on how versions were converted.
> feat(vulnfeeds): Save where versions were converted from in CVE5 conversion.

- gcp/website/frontend3/src/linter.js
- gcp/website/frontend3/src/linter.scss
- gcp/website/frontend3/src/templates/linter/index.html
The linter web interface was incorrectly representing home databases as ecosystems, this corrects that treatment.
I have tested this locally.
> fix(linter): rename ecosystem to home database

- vulnfeeds/cmd/cvelist2osv/main.go
This was previously adding an empty severity even when empty.
> fix(vulnfeeds): empty severity struct being added to OSV struct

- docker/ci/Dockerfile
There is a warning of [LegacyKeyValueFormat](https://docs.docker.com/reference/build-checks/legacy-key-value-format/) when building the `ci` image so this PR updates the Dockerfile to use `ENV key=value` format.
> fix(ci): use `ENV key=value` format in Dockerfile

- gcp/api/server.py
- gcp/api/server_new.py
- gcp/api/server_test.py
- osv/models.py
- osv/models_test.py
For #3830
Change the new `AffectedVersions` entities to store a normalized Git repository URL so that queries with the new API logic so that queries for tags aren't dependent on the exact repository URL:
- remove the protocol/scheme
-  There are currently only 16 unique repositories in OSV (test instance) that don't use the `https://` scheme, and only 3[^1] of these repos have vulns with both `http://` & `https://`
- remove the `.git` extension
- Mostly, OSS-Fuzz and CURL uses GitHub repos with the `.git` extension, while our CVE's do not.
I will need to do a re-put of all the GIT records in the test instance to repopulate the names in the `AffectedVersions` entities.
This doesn't yet fix the issue on production - it's too complicated to try fix with the current/old querying logic, it'll …
> feat: Normalize git repository URLs for API queries on the new API

- gcp/website/frontend3/src/templates/vulnerability.html
Git doesn't strictly have an ecosystem name, so it caused 500 errors when trying to render.
> fix(frontend): affected.package.ecosystem giving 500 errors

- gcp/website/frontend3/src/styles.scss
- gcp/website/frontend3/src/templates/vulnerability.html
Adds a footer bar so the last ecosystem’s tree ends on a visible horizontal line instead of trailing off.
> fix(ui): Add border to final ecosystem panel

- vulnfeeds/cmd/debian/run_debian_convert.sh
The binary name changed in #3987, but we didn't update the script.
> fix: binary name in run_debian_convert.sh

- gcp/website/frontend3/src/styles.scss
> fix(ui): set vuln packages active tab bottom border to red

- gcp/website/frontend3/src/templates/vulnerability.html
Refactors the Ecosystem Header expand/collapse logic for cases where multi-ecosystem vulnerabilities with large package counts stay collapsed by default. Single-ecosystem vulns behave as before.
This helps avoid endless vertical scrolling for cases like: [RHSA-2025:16669](https://osv.dev/vulnerability/RHSA-2025:16669)
> refactor(frontend): streamline ecosystem auto-expand logic

- osv/ecosystems/alpine.py
- osv/ecosystems/alpine_test.py
- osv/ecosystems/bioconductor_test.py
- osv/ecosystems/cran.py
- osv/ecosystems/cran_test.py
- osv/ecosystems/debian.py
- osv/ecosystems/debian_test.py
- osv/ecosystems/ecosystems_base.py
- osv/ecosystems/haskell.py
- osv/ecosystems/haskell_test.py
- osv/ecosystems/maven.py
- osv/ecosystems/maven_test.py
- osv/ecosystems/nuget.py
- osv/ecosystems/nuget_test.py
- osv/ecosystems/packagist.py
- osv/ecosystems/packagist_test.py
- osv/ecosystems/pub.py
- osv/ecosystems/pub_test.py
- osv/ecosystems/pypi.py
- osv/ecosystems/pypi_test.py
- osv/ecosystems/redhat.py
- osv/ecosystems/redhat_test.py
- osv/ecosystems/rubygems.py
- osv/ecosystems/rubygems_test.py
- osv/ecosystems/semver_ecosystem_helper.py
- osv/ecosystems/semver_ecosystem_helper_test.py
- osv/ecosystems/ubuntu.py
- osv/ecosystems/ubuntu_test.py
Per the osv-schema:
> `introduced` allows a version of the value `"0"` to represent a version that sorts before any other version.
Previously, we were just coercing "0" to be the general 0 value for the ecosystem (e.g. in semver `0.0.0`).
This caused problems when trying to match e.g. `0.0.0-pre`, which sorts before.
Wrapped all the sort_keys in a `VersionKey` type and added a new sentinel `0` value type that always sorts before other versions.
This is technically incorrect for ecosystems where "0" is a valid version and that supports pre-releases (e.g. in Maven `alpha` < `0-alpha` < `0`) but these edge cases are not worth handling.
On an semi unrelated note, also bumped the max version that some invalid versions get mapped to from `999999` to `9999999999` so that they're larger than …
> fix: ensure '0' version is always sorted first

- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
- vulnfeeds/git/versions.go
- vulnfeeds/models/types.go
Part of splitting logic from #3951
> refactor(vulnfeeds): git commit resolution code for better reusability

- docs/_config.yml
- gcp/website/frontend_handlers.py
Fixes the trailing slash problem, so now [`/linter`](https://test.osv.dev/linter) and [`/linter/`](https://test.osv.dev/linter/) both resolve correctly.
> fix(linter): handle page routing with trailing slash

- vulnfeeds/cmd/cvelist2osv/version_extraction.go
- vulnfeeds/cmd/cvelist2osv/version_extraction_test.go
- vulnfeeds/cves/versions.go
- vulnfeeds/cves/versions_test.go
This function will be used by the new combine-to-osv function, so moving it somewhere for better reusability
> refactor: Move buildVersionRange to be more reusable

- gcp/api/cursor.py
- gcp/api/server.py
When package querying was paginated, it was always returning the 'not started' page token, because you cannot have page tokens in 'OR' queries. The exception was being caught and assumed to be the 'There is no cursor currently' error that happens when you ask for a cursor before iterating.
Removed the 'IN' query (so ecosystem-less queries will not match GIT repos), and made the exception handler explicitly check for 'There is no cursor currently' to help catch this in the future.
> fix(api): page_tokens

- deployment/clouddeploy/gke-workers/base/cve5-to-osv.yaml
- deployment/clouddeploy/gke-workers/environments/oss-vdb/cve5-to-osv.yaml
This cron job will only enable the conversion of records into the bucket, not the ingestion into OSV :)
> feat: enable cve5 conversion cron job for prod

- vulnfeeds/cmd/cve-bulk-converter/run-cvelist-converter.sh
- vulnfeeds/cves/versions.go
I think there's a minor bug that it's capturing everything inside the local dir so it's trying to cp everything twice. this should hopefully fix that
> fix: CVEList specify a different output

- renovate.json
Renovate has recently gotten support for updating the `uses-with` for GHA actions i.e. `python-version` with `actions/setup-python`, `node-version` with `actions/setup-node` - unfortunately though for some reason it includes this as part of the general "update workflows" task, so we end up with e.g. #4116 which casually bumps the Python version being used up a minor version.
I assume folks would prefer that wasn't the case, so this disables that - I'm pretty sure we could alternatively have Renovate open a dedicated PR for these updates but I'm not sure we could have seperate PRs per action/type (i.e. Node and Python would probably be included together) and overall I just don't think it's that important to have these on the latest versions 🤷
> ci: disable updating `uses-with` versions in GHA workflows
