docker/worker/Dockerfile, docker/worker/oss_fuzz.py, docker/worker/worker.py, docker/worker/worker_test.py
This is in preparation for a more generalized pipeline.
=> Move oss-fuzz specific worker functions to its own module.

docker/importer/importer.py, docker/importer/importer_test.py, docker/importer/testdata/expected_patch_basic.diff, docker/worker/testdata/BLAH-123.yaml, docker/worker/testdata/expected.diff, docker/worker/worker.py, docker/worker/worker_test.py, lib/osv/sources.py, lib/osv/types.py
- Implement a task to process user updates to a source repo. This task
adds additional commit ranges and versions and commit changes back.
These changes are also pushed into Datastore entities for the API/UI.
- Implement commit retry logic with rebasing.
=> Process user changes from source repository.

gcp/api/integration_tests.py, gcp/api/server.py
=> Fix integration tests after ecosystem migration.

docker/importer/importer.py, docker/worker/worker.py, lib/osv/sources.py
- Take source repo directory_path into account when computing source
paths for OSS-Fuzz.
- Handle parsing and file load errors in worker update gracefully.
=> Various fixes.

docker/importer/importer.py, docker/importer/importer_test.py, lib/osv/types.py
- Record last processed commit hash.
- Reduce frequency of scheduled updates.
=> Importer fixes.

docker/worker/oss_fuzz.py
This lets users manually fill in missing info later.
=> Always set Bug attributes for OSS-Fuzz bugs even on failure.

docker/worker/worker.py, docker/worker/worker_test.py, lib/osv/__init__.py, lib/osv/impact.py, lib/osv/repos.py, lib/osv/sources.py
Also fix worker update dealing with existing source repo checkouts and deal
with repos with changed git URLs
=> Move repo-specific functions to repos module.

gcp/appengine/cron-service.yaml, gcp/appengine/cron.yaml, gcp/appengine/deploy.sh
Use basic scaling to get a longer deadline than 10 minutes.
=> Add a cron-service.

vulnfeeds/.gitignore, vulnfeeds/README.md, vulnfeeds/cmd/pypi/main.go, vulnfeeds/cves/cve.go, vulnfeeds/cves/versions.go, vulnfeeds/go.mod, vulnfeeds/go.sum, vulnfeeds/pypi/pypi.go, vulnfeeds/pypi/pypi.sql, vulnfeeds/vuln/vuln.go, vulnfeeds/vulns/vulns.go
This is something which can find relevant vulnerabilities from existing
feeds such as CVEs and output them in a format compatible with OSV.
=> Add proof of concept vulnfeeds code.

vulnfeeds/pypi/pypi.go, vulnfeeds/pypi/pypi.sql
Try to parse additional URLS for PyPI package descriptions and use that
to cross-reference against CVEs.
=> vulnfeeds: Improve accuracy of PyPI package matching.

vulnfeeds/cmd/pypi/main.go, vulnfeeds/pypi/README.md, vulnfeeds/pypi/pypi_links.sql, vulnfeeds/vulns/vulns.go
- Modify PyPI SQL query to include download_url links.
- Fix bq command line.
- Add a summary field to output
- Generalize ID calculation.
- Trim lines when parsing false positives file.
=> vulnfeeds: Various minor fixes.

docker/importer/importer.py, docker/importer/importer_test.py, lib/osv/tests.py
=> importer: Support opting out of analysis.

gcp/api/integration_tests.py
=> Minor fix to integration tests.

gcp/appengine/cron-service.yaml, gcp/appengine/requirements.txt
- Upgrade deps.
- Use a bigger instance class.
=> App Engine cron fixes.

docker/importer/build.sh, docker/importer/run_tests.sh, docker/worker/Pipfile, docker/worker/Pipfile.lock, docker/worker/build.sh, docker/worker/run_tests.sh, lib/README.md, lib/setup.py
=> Add setup.py for OSV pip package.

docker/importer/importer.py, docker/importer/importer_test.py, docker/worker/worker.py, docker/worker/worker_test.py, lib/osv/models.py, lib/osv/sources.py
In preparation for loading Go vulnerabilities.
- Add a "type" to SourceRepository entity to indicate GIT or BUCKET.
- Add "extension" and "editable" fields to SourceRepository entities
"extension" is the extension used for vulnerabilities, and "editable" indicates whether
or not OSV should write back updates. 
- Update worker/importer to support GCS.
Part of #121.
=> Implementing loading vulnerabilities from GCS.

docker/importer/importer.py, docker/importer/importer_test.py, docker/worker/Dockerfile, docker/worker/build.sh, docker/worker/worker_test.py, gcp/api/requirements.txt, gcp/appengine/index.yaml, gcp/appengine/requirements.txt, lib/osv/models.py, lib/osv/semver_index.py, lib/osv/sources.py
- Store ecosystem_specific and database_specific.
- Write SemVer fixed indexes for querying.
=> Ingestion updates.

docker/worker/worker_test.py, lib/osv/repos.py, lib/osv/sources.py, lib/osv/tests.py
This is much faster than libgit2's clone for large repos.
=> Use "git" CLI for cloning.

docker/importer/importer.py, docker/worker/worker.py, lib/osv/models.py, lib/osv/repos.py
Also clean up some checkout related code while we're here.
=> Support branches for source repositories.

vulnfeeds/pypi/cloudbuild.yaml
This will be used for automated advisory commits.
=> vulnfeeds: Add a cloudbuild for automatically generating pypi JSON files

lib/osv/analyze_tool/__init__.py
- Don't analyze non-existent paths.
- Log error on parsing failures.
=> Minor analyze_tool fixes.

docker/importer/importer.py
- Handle changed files that were later deleted.
- Handle deleted files that were later re-added.
=> Fix change detection in importer.

lib/osv/models.py
First part of removing this from the protobuf definition.
=> Don't read severities from vulnerabilities

lib/osv/models.py
=> Revert "Don't read severities from vulnerabilities"

docker/importer/importer_test.py, docker/worker/worker_test.py, gcp/appengine/frontend/package-lock.json, gcp/appengine/frontend/package.json, gcp/appengine/frontend/src/App.vue, gcp/appengine/frontend/src/components/Home.vue, gcp/appengine/frontend/src/components/List.vue, gcp/appengine/frontend/src/components/Vulnerability.vue, gcp/appengine/frontend/src/main.js, gcp/appengine/frontend_handlers.py, gcp/appengine/index.yaml, lib/osv/models.py
List view changes:
- Improve list view layout.
- Add "ecosystem" filter to list view.
- Sort list view by last modified time instead of ID.
- Improving vulnerability search indexing by tokenizing and including
more fields.
Vulnerability view changes:
- Display source of vulnerabilities.
- Make long version lists scrollable.
Others:
- Override default font with Roboto.
- Tweak home page text.
=> Many UI fixes.

lib/osv/impact.py
Forgot to push this in last PR.
=> Minor code cleanup.

lib/osv/models.py
Otherwise we run into issues with field size limits.
=> Don't index summary, details fields.

lib/osv/impact.py
Preventative measure to avoid future issues.
=> More throttling for Datastore writes.

lib/osv/impact.py
Log a warning instead of exceptioning out.
=> Handle invalid git ranges.

gcp/appengine/app.yaml, gcp/appengine/frontend/public/public_keys/pypa
=> Add public key for pypa integration.

docker/importer/importer.py, docker/importer/importer_test.py
This will be used to support the PyPI vulnerability reporting bridge.
#179
=> Set up an ecosystem Pub/Sub topic push for changed vulnerabilities.

docker/importer/importer.py
Handle parsing failures more gracefully.
=> Fix an exception in importer.

lib/osv/models.py
The original list to be sorted should not be mutated.
=> Fix a bug with sorting events.

lib/osv/models.py
Distinguish between empty "introduced" and unset.
=> Fix a bug with 0.8 to 0.7 conversion.

gcp/appengine/frontend/package-lock.json, gcp/appengine/frontend/src/components/Home.vue, gcp/appengine/frontend/src/components/List.vue, gcp/appengine/frontend/src/components/Vulnerability.vue, gcp/appengine/frontend_handlers.py
The main change here is to support multiple packages per vulnerability.
=> Update frontend to reflect schema changes.

gcp/api/integration_tests.py, gcp/api/server.py
Take the package name and ecosystem into account.
Fixes #224.
=> Fix bug with SEMVER matching and multiple packages.

gcp/functions/pypi/main.py, gcp/functions/pypi/main_test.py, gcp/functions/pypi/requirements.txt, gcp/functions/pypi/testdata/test_vuln.json
Include the `details` field, and the `introduced`/`fixed` ranges for ecosystem versions.
=> Send more data to PyPI

vulnfeeds/cves/versions.go, vulnfeeds/vulns/vulns.go
Fixes #235
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
=> add some basic classification of reference url types

vulnfeeds/pypi/pypi.go
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
=> vulnfeeds: add more links to blocklist for pypi

gcp/api/integration_tests.py, gcp/api/server.py, gcp/appengine/index.yaml
=> Support querying by package URL.

lib/osv/ecosystems.py, lib/osv/ecosystems_test.py, lib/osv/third_party/univers/LICENSE, lib/osv/third_party/univers/README.md, lib/osv/third_party/univers/gem.py, lib/osv/third_party/univers/gem.py.ABOUT, lib/osv/third_party/univers/gem.py.NOTICE, lib/setup.py
This uses the implementation of Ruby version parsing from https://github.com/nexB/univers
Fixes #228.
=> Add RubyGems version expansion support.

lib/osv/ecosystems.py, lib/osv/ecosystems_test.py, lib/osv/nuget.py, lib/osv/nuget_test.py, lib/osv/semver_index.py, lib/run_tests.sh
=> Support NuGet versions and expansion

gcp/functions/pypi/requirements.txt, lib/osv/third_party/__init__.py, lib/osv/third_party/univers/__init__.py, lib/setup.py
- Add missing __init__.py
- Also update osv package for the PyPI bridge.
=> Fix OSV package

lib/osv/ecosystems.py, lib/setup.py
The "registration3" endpoint returns outdated data. Use
"registration5-semver1" instead.
=> Update NuGet API endpoint.

gcp/api/integration_tests.py, gcp/api/requirements.txt, gcp/api/server.py
=> Allow querying by PURLs that have version numbers.

docker/worker/worker.py
When handling invalid messages.
=> Mark all Bugs with the same source_id as invalid.

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/templates/list.html
=> Fix v2 UI broken page references

gcp/appengine/frontend3/src/templates/home.html, gcp/appengine/frontend3/src/templates/list.html, gcp/appengine/frontend_handlers.py
=> Fix more v2 UI breakages.

docker/worker/testdata/ImpactTest_basic.txt, docker/worker/testdata/ImpactTest_fixed_range_too_long.txt, docker/worker/testdata/ImpactTest_not_fixed.txt, docker/worker/testdata/ImpactTest_range.txt, docker/worker/testdata/ImpactTest_simplify_range.txt, docker/worker/testdata/ImpactTest_zero_regression_range.txt, docker/worker/testdata/UpdateTest_update.txt, docker/worker/testdata/UpdateTest_update_add_fix.txt, docker/worker/testdata/UpdateTest_update_new.txt, docker/worker/testdata/UpdateTest_update_no_introduced.txt, docker/worker/worker.py, lib/osv/models.py
=> Reduce duplicates in indexes.

README.md
=> Add license information to all data sources.

docker/worker/worker.py, lib/osv/ecosystems.py, lib/osv/ecosystems_test.py
The existing API used has strict rate limits.
=> Support deps.dev for version expansion in Maven.

gcp/api/integration_tests.py
Also get the expected vulnerability contents dynamically in most cases.
=> Fix integration tests.

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/about.html, gcp/appengine/frontend_handlers.py
=> Add initial about page for V2

gcp/appengine/frontend3/package-lock.json, gcp/appengine/frontend3/package.json, gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/index.js, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/home.html
- Fix scaling.
- Make ecosystems section wrap.
- Make other text sections wrap nicely as well.
- Also make the code snippet highlighted.
=> V2: Improvements to home page for mobile.

gcp/appengine/frontend3/src/index.js, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/list.html
- Make ecosystems list expandable on mobile (collapsed by default).
- Only show ID, Packages columns.
Fixes #380.
=> Make vulnerability list page render better on mobile.

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/about.html, gcp/appengine/frontend3/src/templates/home.html, gcp/appengine/frontend3/src/templates/vulnerability.html, gcp/appengine/frontend_handlers.py
- Remove WIP notice.
- Fix some styling on about page.
- Minor documentation changes.
- Sort ecosystems case insensitively.
=> Some final tweaks for V2 MVP.

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/templates/home.html
=> Clarify some text on home page.

gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/vulnerability.html, gcp/appengine/frontend_handlers.py
- Format the JSON.
- Allow overflow.
=> Improve rendering of database_specific and ecosystem_specific.

docker/worker/testdata/UpdateTest_update_limit.txt, gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/home.html, gcp/appengine/frontend3/src/templates/list.html, lib/osv/models.py
- Button hover states
- Tooltips/links for ecosystems bubbles on home page
- Take "limit" events into account for considering if a vulnerability has a fix available.
- Tweak line heights.
=> Various UI fixes.

README.md
=> Add list of third party tools

gcp/appengine/deploy.sh
- Set -ex in bash script.
- Use pipenv through python module instead of the system default.
=> Improve App Engine deployment script.

lib/osv/ecosystems.py
(up to 320 seconds wait for last attempt)
=> Increase backoff and number of retries 

docker/importer/importer.py
Remove limitation of once a day imports
=> Much more frequent imports

actions/analyze/Dockerfile, actions/analyze/analyze.py
Context: https://github.com/pypa/advisory-database/issues/86
=> Fix analyze github action.

gcp/api/Dockerfile, gcp/api/deploy_backend
=> Fix API deployment again.

CONTRIBUTING.md, Makefile, Pipfile, Pipfile.lock, README.md
Also add a Makefile to make things easier.
=> Add local development instructions.

docs/architecture.md
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
=> Fix link in arch doc

.gitmodules, CONTRIBUTING.md
=> Fix some local development issues.

gcp/appengine/dist/public_keys/pypa
=> Add missing public key.

docker/importer/importer.py, docker/importer/importer_test.py, osv/models.py
Not 100% sure this will work the way I think it will.
=> Ignore import time once, if column is set to True in SourceRepository

docker/worker/worker.py, osv/cache.py, osv/ecosystems.py
The RedisCache did not work with the cache.Cached decorator. Serialize
all keys and values using JSON.
=> Fix cache serialization issues.

.gitignore, Makefile
- Add .egg-info to .gitignore.
- Add git submodule update command to worker-test target.
=> Minor changes to improve local development.

README.md
Worth periodically reviewing the results from
https://cs.github.com/?q=%22api.osv.dev%22 to see what else pops up.
Also ran through mdformat
Fixes: #464
=> Embellish third-party section with other discovered usage

docker/importer/importer.py, docker/worker/worker.py, gcp/api/integration_tests.py, gcp/api/server.py, gcp/api/test_server.py, gcp/appengine/frontend_handlers_test.py, osv/cache.py, osv/debian_version_cache.py, osv/ecosystems.py, osv/ecosystems_test.py, osv/request_helper.py, osv/request_helper_test.py
This fixes the vast majority of the outstanding lint findings. 
I need to discuss/get some assistance with the outstanding ones.
```
************* Module importer
docker/importer/importer.py:213:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
************* Module osv.cache
osv/cache.py:87:14: W1505: Using deprecated method getcallargs() (deprecated-method)
osv/cache.py:70:0: C0103: Function name "Cached" doesn't conform to the `snake_case` group in the '^(?:(?P<exempt>setUp|tearDown|setUpModule|tearDownModule)|(?P<camel_case>_?[A-Z][a-zA-Z0-9]*)|(?P<snake_case>_?[a-z][a-z0-9_]*))$' pattern (invalid-name)
------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 9.99/10, +0.00)
```
=> Fix lint findings

tools/lint_and_format.sh
=> Fix lint_and_format action so lint findings are not ignored

tools/scanner/cmd/scanner.go
Correcting this while we're at it.
=> Update module paths for renamed repo

gcp/appengine/frontend3/src/templates/home.html
To account for new module/repo path.
=> Update Go install command on home page.

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/templates/about.html, gcp/appengine/frontend3/src/templates/home.html, gcp/appengine/frontend3/src/templates/list.html, gcp/appengine/frontend3/src/templates/vulnerability.html
=> Various frontend fixes

.github/workflows/lint.yaml
=> Ensure an appropriate version of Go for test environment

osv/ecosystems.py
Hex enforces semver according to
https://hex.pm/docs/publish#adding-metadata-to-code-classinlinemixexscode
=> Add Hex to SEMVER_ECOSYSTEMS

tools/lint_and_format.sh
=> I missed a variable rename in https://github.com/google/osv.dev/pull/659

tools/osv-scanner/internal/output/purl_to_package.go
Fix casing issue missed in #727
=> fix casing issue missed in previous PR

renovate.json
I believe the old wording is actually incorrect
=> Slight change to schedule wording in renovate.json

gcp/appengine/dist/public_keys/pypa
=> Restore PyPA key.

gcp/api/README.md
Make a little more copy-paste friendly, call out a trap for young players.
=> Clarify and improve API release documentation

gcp/api/deploy_backend, vulnfeeds/vulns/vulns.go
Reviewer feedback on https://github.com/google/osv.dev/pull/738 indicated this is the preferred format.
=> Add support for reading and writing JSON

vulnfeeds/cves/versions_test.go
I was warming up to work on ExtractVersionInfo and wrote a quick test...
=> Extend tests

README.md
- Use a better outlink for the OSV schema
- Add some more sources OSV uses, and sort the list
- General reformatting
=> A few documentation updates

docker/importer/importer.py
Change logging default severity back to INFO to reduce noise
=> Change logging default severity back to INFO to reduce noise

vulnfeeds/cmd/download-cves/main.go, vulnfeeds/cves/cve.go
Also fixed a few initialisms consistently with existing code
=> Add pagination support

gcp/appengine/frontend_handlers.py
=> Fix frontend linking and performance

docker/exporter/exporter.py
This way we've got an obvious thing to look for in the logs
=> Add a log entry for the ecosystems.txt export

tools/osv-scanner/README.md
=> Correct OSV Scanner installation instructions

docker/importer/importer.py
Fix importer error because of missing continue upon catching exception
=> Fix importer error

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yaml, .github/workflows/osv-scanner.yml, .github/workflows/publish-to-pypi.yaml
Fixes 4/5 high issues in scorecard
=> Add read-all default permissions

vulnfeeds/cmd/cperepos/main.go
Full overhaul to make this generally accessible and useful
=> Produce reusable output from cperepo tool

vulnfeeds/cmd/cperepos/main.go
This is mostly compensating for the removal of the allowlist of reference descriptions ("Advisory" in particular)
=> Improve invalid repo exclusion based on eyeballing the results

gcp/appengine/frontend3/src/styles.scss
Follow up to #860 to make this match the rest of the UI.
=> Make filled triangle white.

vulnfeeds/cpp/main.go
Also pave the way for refactoring out some of the repository determination over to the CPE Dictionary parser.
=> Add some basic metrics capture

gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/home.html
Some more instructions, and add a ID to allow links to specific section of page. Also adds the term OSV-Scanner to the main page.
=> Some more instructions, and add a ID to allow links to specific section of page

gcp/appengine/frontend3/src/base.html, gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/about.html, gcp/appengine/frontend3/src/templates/home.html
- Fix blog page (fixes #868).
- Fix home page after #870.
- Fix about page.
- Delete some unused CSS.
Also implement a responsive hamburger menu for the top bar on mobile sized screens.
This is done using HTML/CSS only, and includes various animations/transitions.
=> Various mobile UI fixes.

gcp/api/README.md
I was able to successfully deploy yesterday without using sudo
=> Using sudo here seems to make things worse

vulnfeeds/cmd/cperepos/main.go
Also add a few more known-bad repos to ignore
=> Only consult Debian as a last resort

renovate.json
This gives us something to filter on
@michaelkedar had this idea while we were walking through the release process this week.
https://docs.renovatebot.com/configuration-options/#labels
=> Label the PRs created by Renovate

docker/worker-base/Dockerfile, docker/worker-base/build.sh
=> Make Python building use multiple cores

deployment/terraform/modules/osv/main.tf
Fixes issues with dead lettering not working
=> Add pubsub service account permissions to terraform config

README.md
Surfaced via https://news.ycombinator.com/item?id=34016188
=> Add a couple more integrations

README.md
Betterscan CE is a Code Scanning/SAST/Static Analysis/Linting using many tools/Scanners with One Report (Code, IaC). Supports major programming and Cloud stacks.
Now with added OSV Scanner it will scan SBOM and dependencies vulnerabilities.
Great work!
More in the project repo and website.
Feel free to contact me in case of any questions.
Thanks,
P.S Maybe you can sort the list alphabetically
=> Adding Betterscan CE to "Third party tools and integrations" section

vulnfeeds/cmd/cperepos/README.md
Realised this command doesn't copy-paste correctly.
=> Fix copy pastability of example command

.github/workflows/lint.yaml, deployment/terraform/environments/oss-vdb-test/main.tf, tools/lint_and_format.sh
Add terraform linting to the linting test.
=> Add terraform format linting

deployment/terraform/environments/oss-vdb-test/main.tf, deployment/terraform/modules/osv/osv_api.tf, deployment/terraform/modules/osv/variables.tf, gcp/api/README.md
In preparation for moving to Cloud Deploy.
=> Remove API backend image from Terraform

vulnfeeds/tools/debian/debian_converter/Pipfile.lock
Regenerate pipfile.lock in debian, which has a lot of unnecessary packages in it.
=> Regenerate pipfile.lock in debian, which has a lot of unnecessary packages in it.

docker/worker-base/Dockerfile
This is the previous version at time of writing.
This is part of addressing #1019.
=> Downgrade Docker to older 20.x version.

README.md
They added support in
https://github.com/renovatebot/renovate/releases/tag/34.129.0
=> Add Renovate to the third-party integrations

vulnfeeds/git/repository.go, vulnfeeds/git/repository_test.go, vulnfeeds/go.mod, vulnfeeds/go.sum
Queries tags and supports optional cacheing
The tests need to be fully mocked out so they're hermetic
=> Preliminary remote repository tag querying code

vulnfeeds/cves/versions.go, vulnfeeds/cves/versions_test.go, vulnfeeds/git/repository.go, vulnfeeds/git/repository_test.go
Put all the remote repo code in the dedicated package
=> Consolidate git stuff

README.md, docker/worker/worker_test.py, osv/impact.py, osv/impact_test.py, osv/models.py, run_tests.sh
=> Add a new batched AffectedCommits index.

osv/impact.py
There is a limit on the total size of a Datastore put() request (10 MiB) that we were hitting when batch writing large AffectedCommits entities.
=> Fix request size limit exceptions with AffectedCommits.

.github/workflows/publish-to-pypi.yaml, setup.py
- Checkout submodules in the PyPI builder to make sure the OSV schema is included in the built package.
- Make sure the JSON schema is included as a data file. 
- Add missing PyPI package dependencies. This should align with our root Pipfile.
Part of #1060
=> PyPI fixes.

gcp/functions/pypi/Pipfile, gcp/functions/pypi/Pipfile.lock
=> Update OSV package version in gcp/functions/pypi.

CONTRIBUTING.md
I noticed this was messed up, so fixed it.
=> Fix formatting of prerequisites list

gcp/appengine/blog/content/posts/renovate_announcement.md
Setting draft to false and adjusting timestamp.
=> Renovate announcement no longer draft

docs/sections.md
=> Add rate limit question to documentation

vulnfeeds/cmd/cperepos/main.go, vulnfeeds/git/repository.go, vulnfeeds/git/repository_test.go
Validate that repositories actually exist
Add some additional progress indicators to the logging output
Minor docstring improvements
=> Add validation to CPE Dictionary pre-processor

CONTRIBUTING.md, README.md
Addresses #1073. 
It probably makes sense to include this information somewhere on the website as well, but this is a start. 
Open to critique on wording, etc.
=> Adding data contribution guidelines.

gcp/appengine/frontend3/src/templates/about.html
=> Added FAQ about data contribution.

gcp/appengine/frontend_handlers.py
Fixes image output for the blog. Might still be too strict if we want to allow blog to have images in directories.
Also updates blog to use safe_join to add another layer to preventing escapes.
=> Modified frontend to safely output static images under blog

gcp/appengine/blog/content/posts/automating-and-scaling-vex-generation/index.md, gcp/appengine/frontend3/src/styles.scss
Closes #1100 
> ### New:
> ![image](https://user-images.githubusercontent.com/106129829/223283655-26c85078-892b-4dcc-a66c-bfa26dbad4d6.png)
> 
> ### Old:
> ![image](https://user-images.githubusercontent.com/106129829/223283724-512d0dec-1a07-4d6a-9f3d-77b801249b5b.png)
=> Add margins to blog post titles and code blocks

README.md, gcp/appengine/frontend3/src/templates/faq.html
=> Added FAQ about data downloads. 

docker/worker/worker.py
I removed this line when I changed it. oops.
=> Fix worker logging `threading.local()` AttributeError

gcp/appengine/frontend3/src/templates/faq.html
@andrewpollock please confirm that I represented the SLOs correctly. Please feel free to suggest changes if you want to adjust the wording slightly.
=> FAQ updated to include SLOs

deployment/build-and-stage.yaml, vulnfeeds/build_and_deploy.sh, vulnfeeds/cmd/mirror-debian-copyright/Dockerfile, vulnfeeds/cmd/mirror-debian-copyright/build.sh, vulnfeeds/cmd/mirror-debian-copyright/mirror-debian-copyright
First step in running on GKE regularly as a cron job.
=> Dockerize debian copyright mirroring

deployment/build-and-stage.yaml, vulnfeeds/build_and_deploy.sh, vulnfeeds/cmd/cperepos/Dockerfile, vulnfeeds/cmd/cperepos/build.sh, vulnfeeds/cmd/cperepos/gen_cperepos_map
First step in running on GKE regularly as a cron job.
=> Dockerize cperepo generation

deployment/build-and-stage.yaml
My turn to make a mistake in this file :slightly_smiling_face:
=> Fix `build-and-stage.yaml` again

deployment/build-and-stage.yaml
I left out a comma and that seems to be making something not quite right...
=> Add missing comma

vulnfeeds/cmd/cperepos/gen_cperepos_map
Fix the handling of the decompressed output from gzip
=> Redirect gzip decompressed output

deployment/clouddeploy/gke-workers/base/gen-cperepos-map.yaml
This way everything will generate as intended.
=> Make the container name match everywhere

deployment/build-and-stage.yaml
I keep missing things when reviewing :disappointed:
=> Add entrypoint to Cloud Build AppEngine delete

gcp/appengine/frontend3/src/templates/home.html
When I was updating the docs, I saw another spot to adjust the API calls to bring them in line with the docs.
=> Bringing homepage in line with docs

deployment/terraform/modules/osv/workers_gke.tf
This will allow importer to run on the importer-pool again.
=> Fix importer pool label

deployment/clouddeploy/gke-workers/environments/oss-vdb-test/gen-cperepos-map.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb/gen-cperepos-map.yaml, vulnfeeds/cmd/cperepos/main.go
Adjust logging behaviour to reflect changes from #1241
=> Fix logging behaviour

renovate.json
Enable the experimental osvVulnerabilityAlerts feature for renovate bot
=> Enable osvVulnerabilityAlerts

vulnfeeds/cpp/main.go
=> Include successful conversions in the per-CVE outcomes

docs/data.md
Adding the two new distros to the docs. 
Changes can be viewed [here](https://hayleycd.github.io/osv.dev/data/#covered-ecosystems)
=> Add AlmaLinux and Rocky Linux

docs/index.md
Preview available [here](https://hayleycd.github.io/osv.dev/)
=> Add link to architecture page

deployment/clouddeploy/gke-workers/base/kustomization.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb-test/base_nvd-cve-osv.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb-test/kustomization.yaml
Temporarily copied the base resource into the oss-vdb-test environment folder.
=> Fix nvd-cve-osv kustomize issue

vulnfeeds/cmd/cperepos/main.go
I'm contemplating discarding repo inference from Debian copyright data due to false positives, and I want to make an (easier) data driven decision.
The current log format was not conveying enough context in the lines that match searches to help with that.
=> Uplevel the logging for ease of single-line analysis

docker/deployment/Dockerfile, docker/worker-base/Dockerfile, vulnfeeds/tools/debian/Dockerfile
=> Remove apt-key usage in dockerfiles

vulnfeeds/cves/versions.go, vulnfeeds/cves/versions_test.go, vulnfeeds/git/repository_test.go
Observed being discarded in log analysis.
=> Add support for more genuinely valid repositories

deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb-test/base_nvd-cve-osv.yaml
The first attempt with just 2022 works, let's try going all the way back
=> Expand coverage scope to all desired years

vulnfeeds/cves/versions.go, vulnfeeds/cves/versions_test.go
These exist and were being excluded unecessarily
=> Add a few more legitimate repo scenarios

deployment/README.md, deployment/build-and-stage.yaml, deployment/clouddeploy/gke-indexer/base/indexer-controller.yaml, deployment/clouddeploy/gke-indexer/base/indexer-scaler.yaml, deployment/clouddeploy/gke-indexer/base/indexer-worker.yaml, deployment/clouddeploy/gke-indexer/base/kustomization.yaml, deployment/clouddeploy/gke-indexer/clouddeploy.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb-test/indexer-controller.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb-test/indexer-worker.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb-test/kustomization.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb/indexer-controller.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb/indexer-worker.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb/kustomization.yaml, deployment/clouddeploy/gke-indexer/skaffold.yaml, deployment/clouddeploy/gke-workers/setup.md, deployment/deploy-prod.yaml, deployment/terraform/environments/oss-vdb/.terraform.lock.hcl
Adds indexer kubernetes's deployment to the automated deployment pipeline
=> Add indexer to deployment pipeline

docs/api/api-quickstart.md
[Preview](https://hayleycd.github.io/osv.dev/)
=> Fixed link

deployment/clouddeploy/gke-indexer/environments/oss-vdb-test/kustomization.yaml, deployment/clouddeploy/gke-indexer/environments/oss-vdb/kustomization.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb-test/kustomization.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb/kustomization.yaml
Explicitly specify path in patches. Not 100% sure this will fix, but seems to work on my computer.
Haven't made failing Cloud Deploy trigger alerts yet.
=> Fix Cloud Deploy Kustomize errors

CONTRIBUTING.md, docs/contributing/architecture.md, docs/index.md
Also ran `mdformat` on these files (my vim does this on save).
=> Fix up a few links that the new link checker was picking up on

.github/workflows/link-checker-on-push.yml, .github/workflows/link-checker.yml
Update link checkers. 
Addresses #1389
=> Add explicit read permission

docker/importer/importer.py
This facilitates the creation of a log-based metric to allow measuring it for SLO adherence monitoring.
=> Log the execution time of the importer

deployment/build-and-stage.yaml
Fixes #1399 
combine-to-osv image was pretending to be the alpine image instead.
=> Fix combine to osv deployment

docs/api/post-v1-determineversion.md
- Make the side panel heading consistent with other methods.
- Clarify that this identifies hashes
- Fix an incorrect link.
- Some more clear wording for the current set of libraries that we can identify.
=> Minor determineversions docs changes.

docker/worker/worker.py
PR #1416 auto-merged before I could act on reviewer feedback.
=> Fix another instance of the source/source_id disparity

docker/worker/worker.py
This takes a less invasive approach to PR #1419, with the tradeoffs of:
- less comprehensive coverage (only going to be applicable to the code path triggered by the "update" pubsub message due to this attribute only currently being present on that message type
- not going to be immediately visible to a human reader of the log line as it's in the JSON payload, but hopefully this can be addressed by the Log Explorer
Also address a final instance of the source/source_id attribute disparity, ensuring source_id is logged more consistently with a relevant value.
=> Plumb the bug ID into more of the worker logs

gcp/api/integration_tests.py, gcp/api/server.py
Fix bug where we are getting two bugs per iteration.
Added another test with an odd number of results to catch these types of errors.
=> Fix api query by package bug

osv/ecosystems/_ecosystems.py, osv/purl_helpers.py
=> Add Hackage and GHC ecosystems.

README.md
=> Added explicit API doc link

docker/worker/oss_fuzz.py
Eliminates https://pantheon.corp.google.com/errors/detail/CI7SxJD5p77aiAE;time=P7D?project=oss-vdb
=> Check for result before checking its repo_url

vulnfeeds/vulns/vulns.go
Only add last_affected when there are no fixed
=> Output schema-compliant records

.github/workflows/link-checker-on-push.yml, .github/workflows/link-checker.yml
This PR does the following:
- Pins the action to a commit.
- Changes scheduled scanning to twice a week.
=> Adjusting github actions

gcp/appengine/frontend3/src/templates/list.html, gcp/appengine/frontend_handlers.py
* Handle records without a package
* Handle summary-less records
* Miscellaneous readability improvements
Also put the page on a white space diet
=> frontend: add support to search result page for CVEs converted

gcp/appengine/blog/content/posts/using-the-determineversion-api.md, gcp/appengine/blog/hugo.toml, gcp/appengine/frontend3/package-lock.json, gcp/appengine/frontend3/package.json, gcp/appengine/frontend3/src/styles.scss
Hi team!
I have added some CSS that is only specific to blog posts. I am hoping that it will clean things up a lot. 
I tried running this locally, but our current instructions are not great. I would appreciate being able to see a dev/stage version if that is possible. What would you guys recommend?
=> CSS Changes to clean up blog

docker/ci/Dockerfile, docker/ci/build.sh, docker/deployment/build.sh, gcp/appengine/blog/content/posts/using-the-determineversion-api.md, gcp/appengine/frontend3/package.json
Attempt to update hugo and see if that helps it build.
=> Update hugo and remove ^ from version

.github/workflows/lint.yaml, docker/worker-base/Dockerfile, docker/worker/Dockerfile, vulnfeeds/tools/debian/Dockerfile
Pin the pipenv version to prevent new updates introducing unknown bugs when building new images.
=> pin pipenv version

Makefile
Make the Makefile do more of the initial setup if needed.
=> Add pipenv sync to makefile

vulnfeeds/git/repository.go, vulnfeeds/go.mod, vulnfeeds/go.sum
This will help for transient failures.
=> Add retries to remote git repo tag listing

vulnfeeds/cpp/main.go
Emit an array so it doesn't crash on the non-array input
=> combine-to-osv expects an array of PackageInfo not a single struct

vulnfeeds/git/repository_test.go
This way the test won't spuriously break.
=> Switch to a fork so the tags stay stable

vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh
All of the flags need to be at the end of the command by the looks of it.
=> Correctly silence the rsync operations

docs/data.md
I saw this while examining another issue in the docs.
=> Fix the format name.

vulnfeeds/cpp/run_cve_to_osv_generation
=> Apply same output suppression from PR #1597 here too

vulnfeeds/cves/versions.go
omitempty was missing the "empty" for yaml
=> Fix a typo in a tag

gcp/appengine/frontend3/src/styles.scss
Issue: https://github.com/google/osv.dev/issues/797
Before:
After:
=> Improve layout of vulnerability subsection.

vulnfeeds/cmd/combine-to-osv/main.go
Added additional context to log messages to help with local execution for manual behaviour testing
=> Minor usability improvements to logging

tools/datafix/delete_bugs_with_source.py, tools/datafix/delete_invalid.py, vulnfeeds/cmd/combine-to-osv/main.go
For CVE unlaunching purposes.
Also update existing scripts to filter in non-warning inducing ways
=> Variation of existing tool to delete all Bugs for a given source

CONTRIBUTING.md
Update contribution guide to include Docker as one of the pre-requisites.
=> Update contribution guide to add Docker

docs/data.md, go.work.sum
Also update the go.work.sum file, which I think renovatebot doesn't support, or is misconfigured for.
=> Fix debian link in documentation

gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/vulnerability.html
https://github.com/google/osv.dev/issues/1102
=> Add a withdrawn field for web interface.

.github/workflows/osv-scanner-scheduled.yml
Update osv-scanner scheduled scan to the new file path. (Changed here: https://github.com/google/osv-scanner/pull/561)
=> Update scheduled scan file

.github/ISSUE_TEMPLATE/converted-nvd-cve-data-quality-report.md
Create an issue template for reporting CVE conversion feedback
=> Update issue templates

gcp/appengine/frontend3/src/templates/vulnerability.html, gcp/appengine/frontend_handlers.py
Fix issue https://github.com/google/osv.dev/issues/1734
=> Add `related` field to web UI.

gcp/appengine/Pipfile.lock
Dependabot broke the Pipfile.lock in #1748 - it doesn't reference to the osv package correctly.
=> fix sanitized-package error

gcp/appengine/frontend3/src/templates/home.html
=> make "create issue" link to the issue template chooser on github

gcp/appengine/frontend3/src/templates/list.html, gcp/appengine/frontend_handlers.py
Fix issues https://github.com/google/osv.dev/issues/1694
Before:
After:
=> Remove duplicated package names on the list page.

.github/workflows/osv-scanner-pr.yml
This is required to get this to work correctly
=> Explicitly specify security-events: write

README.md, docs/third-party.md
Add {rosv}, an R package, to the third-party content lists in .md files.
=> Add {rosv} package to third-party lists

gcp/api/server.py
https://github.com/google/osv.dev/issues/1759
=> dedupe bugs returned in API response

gcp/appengine/blog/content/posts/introducing-broad-c-c++-support/index.md
We've validated the post in staging.
=> Restore intended publication date

docker/indexer/stages/processing/processing.go, docker/indexer/storage/storage.go
Fix indexer by adding in the version field that was missing.
=> Fix indexer missing version field

vulnfeeds/cmd/cperepos/main.go
GitHub repos and usernames are not case sensitive.
Also address a few go-staticcheck findings
=> Treat GitHub repo URLs case-insensitively

docker/exporter/exporter.py
Fix https://github.com/google/osv.dev/pull/1791
Replace query with https://cloud.google.com/appengine/docs/legacy/standard/python/ndb/queries#map
=> Improve exporter performance

docker/exporter/exporter.py, gcp/api/server.py, osv/models.py
Add a to_vulnerability_async() function to convert vulnerabilities and retrieve aliases asynchronously.
=> Add an asynchronous datastore-to-vulnerability conversion function.

gcp/api/server.py
Addressing comment here https://github.com/google/osv.dev/pull/1783#discussion_r1387363131
=> gcp/api: return next page token if query by generic version

gcp/appengine/frontend_handlers.py
`urllib.parse.parse_qs()` throws an exception on bytes containing unicode characters (even if %-encoded).
We were calling it to remove `page` parameters coming from outside of the turbo frame.
Changed this to work with `request.args` directly, and pass the filtered query params into [`url_for()`](https://flask.palletsprojects.com/en/3.0.x/api/#flask.url_for) as keyword arguments, which are treated as query parameters for the redirect.
Had to make a list of accepted query parameters to sanitize the call to `url_for()`
=> Fix query parsing error on Unicode characters

README.md
We still want to clean up the repo per #1714, but document the current information to help contributors in the meantime.
=> Update README with current repository structure

deployment/clouddeploy/gke-workers/base/kustomization.yaml
fix https://github.com/google/osv.dev/pull/1836
=> Add backup.yaml to base kustomization

gcp/appengine/blog/content/posts/license-scanning-support/index.md
Bring it earlier so it'll show on staging.
=> Update date for license scanning blog

gcp/appengine/blog/content/posts/2023-in-review/index.md
So we can release this sooner.
=> Move forward time of retrospective blog post.

gcp/appengine/blog/content/posts/2023-in-review/index.md
- Add more links
- Add line on aliases work.
=> Minor blog post fixes

vulnfeeds/cves/cve.go
Failed to push this before merging the last PR.
=> Fix another timestamp parsing case.

tools/datastore-remover/main.go
Rather than fetching all keys up front, do this by iterating through keys and deleting in batches.
This is for deleting our old AffectedCommit entities.
=> Make Datastore deleter work better with huge collections of entities.

gcp/api/server.py, gcp/api/server_test.py
=> Ignore nested vendored directories in determineversions.

docker/importer/importer.py, docker/importer/importer_test.py, docker/worker/testdata/RESTUpdateTest_update_no_introduced.txt, docker/worker/worker.py, docker/worker/worker_test.py
=> Fix Source Id causing issue on frontend

docs/api/post-v1-querybatch.md
ref: https://github.com/google/osv.dev/issues/321#issuecomment-1129453918
=> Add information on querybatch response ordering

tools/datafix/reput_bugs.py
It took me 3 reads to notice the comment buried in the guts of this.
=> Surface the intention of this script earlier for faster comprehension

vulnfeeds/cves/versions.go
PR #1949 added this repo in error, so remove it again.
Thanks to @another-rex for picking up on it.
=> Remove erroneously added repo

source_test.yaml
Added a 'test' entry to source_test.yaml to make sure the cloud build trigger works as intended
=> Test source repo sync update trigger

source_test.yaml
=> Revert "Test source repo sync update trigger"

docs/faq.md
Based on user feedback from @jimshowalter, add an FAQ entry to discuss how and when version enumeration happens in OSV.dev, and how the API matches versions for non-SemVer ecosystems.
Address some markdownlint complaints about whitespace around headers.
Closes: #1960
=> Document the nuances of version enumeration and matching

cloudbuild.yaml
Fix w.r.t: https://github.com/google/osv.dev/pull/1978#discussion_r1485746544
=> Fix cloudbuild race condition issue.

deployment/clouddeploy/gke-workers/base/exporter.yaml
Already did this on the GUI, seeing if it helps with exporter problems we've been seeing
=> Double exporter memory

docker/indexer/stages/preparation/preparation.go, docker/indexer/stages/processing/processing.go
To make future debugging easier!
=> Add better indexer logging

.gitignore, gcp/appengine/blog/content/posts/announcing-curl-via-rest.md
Fix blog code block css for the latest CURL update post
=> Fix blog code block formatting

osv/repos.py
Don't know how I managed to do this :upside_down_face:
=> Fix pygit2.enums mistake

docs/data.md
Add a description of the : sub ecosystems and how we export all sub ecosystems in one grouped ecosystem. Feel free to reword because I'm not sure I described this very well.
=> Describe colon ecosystems

docker/exporter/exporter.py, tools/datafix/reimport_gcs_record.py
As per suggestion here https://github.com/googleapis/python-storage/issues/1232#issuecomment-1967844331
=> adjust retry strategy for `blob.upload_from_filename`

gcp/api/server.py
Log the type of query the API gets (`git`, `commit`, `ecosystem`, `invalid`) so we can better debug long-running queries.
Trying out [structured json logging](https://cloud.google.com/python/docs/reference/logging/latest/std-lib-integration#logging-json-payloads) in GCP to maybe make it more easily searchable.
=> Add some logging to API queries

deployment/clouddeploy/osv-api/run.yaml
Increase the max instance count, default is 100.
We are currently running into the max instance count (or almost running into it, there is 97 instances running at the moment).
=> Increase max instances

source.yaml
When #2031 is released to Production, the human-friendly links will need to be updated in short order afterwards to avoid disappointment.
Do not merge until after the release for the week of 2024/03/11
=> Stage templated human links for production

gcp/api/server.py
#2055 didn't seem to work, experimenting with putting the trace fields in the base `extra` dict, rather than in `json_fields`
=> Maybe fix api log trace

gcp/api/server.py
=> Another attempt to fix logging traces

gcp/api/server.py
Added a new class/decorator to automatically insert traces into logs in API.
Re: https://github.com/google/osv.dev/pull/2055#pullrequestreview-1941604353
=> Add traces to logs through `logging.Filter`

gcp/appengine/frontend3/src/base.html
Closes #2042 
May need to be tested by someone with access to appengine :)
=> Added 'Docs' link to osv.dev documentation

gcp/appengine/frontend3/package-lock.json
Should fix the vulnerability we've been seeing on express.
Used guided remediation to do this :slightly_smiling_face:
=> Relock package-lock.json

docker/importer/importer.py
- Handle when Last-Modified is not returned by the server.
- Handle first time runs when there is no last import date.
=> Handle some edge cases in REST importer.

deployment/clouddeploy/osv-api/run.yaml
Seeing if this fixes the deployment issues we're encountering.
=> Try setting startup probe delay + timeout

deployment/build-and-stage.yaml, vulnfeeds/cmd/debian/main.go, vulnfeeds/cmd/debian/run_debian_convert.sh
Fix `debian-cve-convert` docker image and add some logs
=> Fix Debian CVE conversion.

docker/alias/alias_computation.py
Fixing issues with the `!=` operator, see #2093
=> Use `< OR >` query in aliases to fix issue

vulnfeeds/cmd/debian/main.go
Add introduce versions "0" to Debian CVE conversion entries.
=> Add introduced version to Debian CVE entries

gcp/appengine/Pipfile, gcp/appengine/Pipfile.lock
This should resolve https://github.com/google/osv.dev/security/dependabot/170
=> gcp/appengine: update gunicorn to 22.0.0

osv/ecosystems/bioconductor.py
I even confirmed that list.remove() is an in-place operation, then must of gotten distracted making the actual change :-(
I feel great shame.
=> Correct late breaking change

gcp/api/integration_tests.py
60e572dbf7b4ded66b488f54773f66aaf6184321 now also matches CVE-2024-31745
=> Fix querying by commit integration test

gcp/appengine/frontend3/package-lock.json
Repeat of #2014 and #1909
It'd be nice if we could work out how to stop this from happening...
=> Revert spicy-sections integrity again

deployment/clouddeploy/osv-website/skaffold.yaml
=> Fix missed website Cloud Deploy change

docker/importer/importer.py
Discovered these were normal default `action='store'` flags while trying to test deletion.
=> Make the boolean flags be boolean

vulnfeeds/cmd/combine-to-osv/main.go, vulnfeeds/cmd/combine-to-osv/main_test.go, vulnfeeds/cmd/debian/main.go, vulnfeeds/cmd/debian/main_test.go
=> Revert "Update last modified time of combine-to-osv entries"

tools/datafix/Pipfile.lock
Resolves https://osv.dev/vulnerability/GHSA-jjg7-2v4v-x38h
=> tools/datafix: update idna in Pipfile.lock

docker/importer/importer.py, docker/worker/worker.py
In the same spirit of what was done in #2046 and #2049
Recently saw a transient 502 error in Production from the importer that would have benefited from this, and decided to look more broadly for any other situations where this could crop up in the future...
=> Retry all remaining GCS operations that may intermittently fail

renovate.json
Hopefully should let renovate pick up updates to our terraform providers
=> Add terraform path to renovate config

docs/Gemfile.lock
I messed up the patch that was supposed to go in #2204 (I think I accidentally used my system's ruby).
=> Relock Gemfile.lock

deployment/terraform/modules/osv/website.tf
Stage 1: 90% to App Engine, 10% to Cloud Run
=> Start forwarding web traffic to cloud run

deployment/clouddeploy/gke-workers/environments/oss-vdb/importer-deleter.yaml
This has been run manually successfully.
=> Enable GCS deletion job in Production

docs/data.md, vulnfeeds/cmd/nvd-cve-osv/README.md
Reference in list of home-grown data sources.
=> Update instructions for a self-demo

tools/datafix/list_ids_for_source.py
Helpful for large-scale data operations and comparing between staging and production.
Borrowed heavily from reimport_gcs_record.py
=> Utility for listing the Bug IDs for a source in Datastore

setup.py
This was requested by a user of the package.
=> Bump PyPI setup.py version.

gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend3/src/templates/vulnerability.html
=> Add suggest improvement button to vulnerability page

gcp/appengine/frontend3/src/templates/vulnerability.html
Remove duplicate closing tag introduced in #2227
=> Remove the duplicate closing tag

CONTRIBUTING.md
Moved it to end of list because external contributors shouldn't actually need Terraform anyway.
=> Add Terraform version to CONTRIBUTING.md

.github/workflows/lint.yaml, docker/ci/install_go.sh, docker/indexer/Dockerfile, docker/indexer/go.mod, docker/terraform/Dockerfile, docs/go.mod, go.work, tools/datastore-remover/go.mod, tools/indexer-api-caller/go.mod, vulnfeeds/cmd/alpine/Dockerfile, vulnfeeds/cmd/combine-to-osv/Dockerfile, vulnfeeds/cmd/cpe-repo-gen/Dockerfile, vulnfeeds/cmd/debian/Dockerfile, vulnfeeds/cmd/download-cves/Dockerfile, vulnfeeds/cmd/nvd-cve-osv/Dockerfile, vulnfeeds/go.mod
Upgrade go version to `1.22.4` and docker base image to [golang:1.22.4-alpine](https://hub.docker.com/layers/library/golang/1.22.4-alpine/images/sha256-9d8429ee88687b18c0f681ce2ad60446c7a1a3472d455f031e2317802ca9fbc4?context=explore)
=> Upgrade go version to 1.22.4

source_test.yaml
This contains both Chainguard and wolfi.
=> Update Chainguard source

source.yaml
=> Add Chainguard source to prod.

docs/data.md
Provide a durable breadcrumb to try and head off questions like https://github.com/google/osv.dev/discussions/2290#discussioncomment-9698370
=> Link to the export CronJob spec

osv/sources.py
Looked more comprehensively to get more of what could have been in #2306
=> Fix more instances of pygit2 incompatibility

deployment/clouddeploy/gke-workers/base/generate-sitemap.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb-test/generate-sitemap.yaml, deployment/clouddeploy/gke-workers/environments/oss-vdb/generate-sitemap.yaml, docker/cron/generate_sitemap/generate_and_upload.sh, docker/cron/generate_sitemap/generate_sitemap.py, gcp/appengine/frontend_handlers.py
Turns out, the original code wasn't doing any uploading 🤦
=> Actually upload the generated sitemaps (and perform logging)

docker/cron/generate_sitemap/generate_and_upload.sh
The CWD is not in the same directory as the script. Use the script from the global PATH.
=> Fix sitemap generate and upload script

gcp/appengine/blog/content/posts/supporting-debian-security-tracker-data/index.md
Add two spaces at the end of the image line to [create a new line](https://www.markdownguide.org/basic-syntax/#line-breaks)
=> Fix Debian blog post format

docs/third-party.md
Previous PR:
https://github.com/google/osv.dev/pull/2317
=> Introducing 'x osv' to third-party.md

osv/impact.py
https://github.com/google/osv.dev/pull/2359 added some ecosystems that support ordering but do not have an enumeration method implemented (expected behavior).
=> Fix enumeration method not implemented error

.github/workflows/staleness.yml, tools/source-sync/source_sync.py
To aid with running OSV record lint checks against all of a source's records, pre-import
=> Utility to download OSV.dev source records

deployment/terraform/environments/oss-vdb-test/main.tf, deployment/terraform/environments/oss-vdb/main.tf
I'm only really doing this to check if there's any issues with the migration to artifact registry (for the test instance).
=> Update espv2 image to 2.49.0

docker/importer/importer_test.py, source_test.yaml
=> Test ignoring unexpected records

docker/importer/importer_test.py, source_test.yaml
This wasn't working as intended as multiple
https://xkcd.com/1171/
=> Merge Android ignore pattern into a single

source.yaml
=> Promote Android ignore pattern consolidation to Production

.github/workflows/staleness.yml
Address https://github.com/google/osv.dev/security/code-scanning/468
=> ci: add explicit permissions to stale workflow

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yaml, .github/workflows/osv-scanner-unified.yml
`branches` is invalid for `on.merge-group`
=> ci(workflow): address github.com/rhysd/actionlint findings

gcp/api/server.py, gcp/api/test_server.py
Do dynamic page sizing for when the query starts to exceed 30 seconds. 
Turns out past me already thought of this, just needed to uncomment the relevant lines.
=> feat: API Dynamic page sizing when query exceeds 30 seconds

gcp/api/server.py
Brackets to the rescue! Turns out in python you can add brackets to make line breaks where-ever you want.
=> chore: make function line break prettier

gcp/api/server.py
Temporarily revert API query to original method on test instance for A/B performance testing
=> feat(api-perf-test): revert API query to original method on test instance for A/B performance testing

README.md
Much nicer to look at than a wall of JSON
=> docs: link to Scorecard report viewer

tools/datafix/delete_bugs.py, tools/datafix/list_ids_for_source.py
- Allow saving queried bug IDs to a file.
- Allow deleting bugs from a specified file. 
This is useful when we don't want to delete all bugs from a `source` at once and need to filter the bugs before deleting them.
=> feat(tools): allow deleting bugs from file

osv/ecosystems/debian_test.py
https://bugs.debian.org/1079320 has been resolved
=> test: reenable Debian ecosystem tests

osv/ecosystems/_ecosystems.py, osv/ecosystems/opensuse.py, osv/ecosystems/opensuse_test.py, osv/ecosystems/suse.py, osv/ecosystems/suse_test.py
=> feat: add SUSE/openSUSE ecosystem

.github/workflows/publish-to-pypi.yaml, .github/workflows/scorecards.yml
Reverts google/osv.dev#2552
This commit causes [scorecards github action failure](https://github.com/google/osv.dev/actions/runs/10714700617/job/29708828829). Reverts this PR first to do some investigation.
=> chore: revert "chore(deps): update workflows"

source_test.yaml
Update `db_prefix` to match with https://ossf.github.io/osv-schema/#id-modified-fields
=> fix: update SUSE db prefix

source_test.yaml
Add [`UBUNTU-CVE-` records](https://github.com/canonical/ubuntu-security-notices/tree/main/osv/cve) into test instance
=> feat: re-enable UBUNTU-CVE- into test instance

gcp/appengine/frontend3/package-lock.json
This PR updates the lockfile to remediate GHSA-m6fv-jmcg-4jfg.
=> chore: update package-lock.json to remediate GHSA-m6fv-jmcg-4jfg

gcp/functions/pypi/deploy.sh
=> chore: Update gcp/functions/pypi to Python 3.11

setup.py
=> chore: Bump OSV pypi package version.

pyproject.toml
=> chore: bump version in pyproject.toml also

gcp/functions/pypi/poetry.lock, gcp/functions/pypi/pyproject.toml
=> chore: Update osv dependency for gcp/functions/pypi.

docker/worker/oss_fuzz.py, osv/ecosystems/_ecosystems.py, osv/ecosystems/redhat.py, osv/ecosystems/redhat_test.py, osv/ecosystems/rocky_linux.py
Red Hat records are not importing as intended, I believe this will correct that.
=> feat(ecosystems): support Red Hat fully

CONTRIBUTING.md
Submodules seem to be mildly gnarly (at least to me). Add some helpful pointers in the contributor documentation for future reference.
=> docs: add some pointers around submodule management

docker/importer/importer.py, docker/importer/importer_test.py
This reverts commit 447a30c5165ee783ecb0b48f7c7e2ed58d72b210.
There is a suspected unknown performance regression 😭
=> refactor(importer): revert #2644

source_test.yaml
Testing of Red Hat RPM security data.
See https://github.com/google/osv.dev/issues/1404
=> feat(source): update redhat-stage temp source to production source

gcp/appengine/frontend3/src/styles.scss, gcp/appengine/frontend_handlers.py
Looks something like this:
Fixes the "AttributeError'NoneType' object has no attribute 'lower'" error
=> fix: CVSS severity rating on vulnerability.html

docs/data.md
Docs changes made in https://github.com/google/osv.dev/pull/2725
=> docs(data): add sub-ecosystem export deprecation note

tools/datafix/reput_bugs.py
Add a `--bugs` flag to the `reput_bug` script to allow reputing only specific bugs.
=> feat(datafix): Allow reputing for each bug ID

vulnfeeds/cmd/cpe-repo-gen/README.md
Allow interested parties to be able to reason about the end result by way of example
=> docs: link to generated output

docker/importer/importer.py
I noticed some errors getting logged by the GCS deletion code because the blob disappeared in between the bucket getting listed and the blobs being retrieved (this can happen, but led me to also find the fix in #2678
Also give validation failure the same exception-raising treatment as the refactor in #2644 did for import-time validation failure.
=> fix(importer): tolerate blobs disappearing

docs/data.md
Docs support for https://github.com/google/osv.dev/issues/2423
=> docs(data dumps): update docs to reflect the all.zip changes

osv/purl_helpers.py, osv/purl_helpers_test.py
=> feat(osv): Add a purl converter for SwiftURL

source.yaml
Propagate #2888 to Production
Part of #2191
=> feat(sources): add human_link for chainguard to production

docker/importer/importer.py, docker/importer/importer_test.py
This commit adds source to ImportFindings in areas overlooked in #2891
=> fix(importer): fully plumb source into record quality findings

renovate.json
Not sure if this will work, but it will be quite nice if all the lockfile maintenance can be done in 1 PR to reduce weekly chore.
=> fix: Attempt at grouping lockfile maintenance

.github/workflows/lint.yaml, .github/workflows/publish-to-pypi.yaml, docker/worker-base/Dockerfile, gcp/api/Dockerfile, gcp/website/Dockerfile
- Poetry version
- Python version for workflows
=> chore: Bump up versions for dependencies we have to manually update

gcp/website/frontend3/src/templates/vulnerability.html
Resolve https://github.com/google/osv.dev/pull/2132
Surface the top-level database-specific field, using the same style as the package-level database-specific field.
=> feat(frontend): surface top level database specific field

osv/purl_helpers.py, osv/purl_helpers_test.py
Implement additional namespace handling to align with the [PURL spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst) for various language ecosystems
Thanks @michaelkedar for pointing this out!
=> fix(purl): add more purl special handling

docs/api/post-v1-query.md, docs/api/post-v1-querybatch.md
Fix page token on the query page, and add page_token to the sample payloads on querybatch page
=> docs: Fix page token text

gcp/website/frontend_handlers.py
=> fix: packages now show in list when there isn't an affected version.

tools/datafix/request_worker_update_record.py
This only works for github sources for now.
Did in response to #3061.
=> feat(datafix): Add ability to request GIT record updates.

gcp/api/server.py
- Handle cases where version parsing fails.
- Show a more descriptive error message for invalid PURL.
=> fix: add error handling for invalid version query

docker/ci/Dockerfile
=> fix(deps): Dockerfile missing go install location in path

cloudbuild.yaml
=> chore(deps): Revert temporary cloudbuild change back

deployment/clouddeploy/gke-workers/base/nvd-cve-osv.yaml
This PR corrects the value for minutes, not seconds
=> fix: use the correct unit of measure

source.yaml
Successfully importing into Staging and available for inspection at https://test.osv.dev/list?ecosystem=Mageia
=> feat(sources): add Mageia to Production

gcp/workers/exporter/exporter.py, osv/models.py
logging.exception can give us more information for debugging
=> fix: change to logging.exception for exporter 

osv/models.py
Now yields the async upstream properly.
=> fix: upstream group async not being yielded correctly

source.yaml
Closes https://github.com/google/osv.dev/issues/3204
=> feat: add Ubuntu LSN to prod instance

docker/worker-base/Dockerfile, gcp/api/Dockerfile, gcp/website/Dockerfile, source.yaml
This updates the Python version to be in line with what is currently available in gLinux.
=> feat: upgrade to Python 3.12.8

gcp/workers/alias/alias_computation.py, gcp/workers/alias/upstream_computation.py
Kudos to @michaelkedar and @hogo6002 for this fix :)
Upstream cron job was taking way too long to run, so reduced querying by using the proper get/fetch method. Will observe in staging.
=> fix(upstream): Improve upstream performance with improved query strategy

vulnfeeds/cves/versions_test.go, vulnfeeds/git/versions_test.go
In the case of a known outage, we can enable a time for the tests to be ignored until.
=> feat(vulnfeeds): Add test expiry date to vulnfeeds

vulnfeeds/git/repository_test.go
This utilises the awesomeness of #3306 in a few more places
=> test(vulnfeeds): parallelize more tests

vulnfeeds/tools/debian/debian_converter/convert_debian.py
=> feat(upstream): Update Debian conversion to use upstream instead of related

gcp/api/integration_tests.py
Something updated one of our live data testcases so have to update the testcase as well
=> fix(tests): Update integration tests due to breakage

source.yaml
Test instance worked as intended so pushing change to prod as well. 
Closes: #3353
=> fix: analyze git commits from curl on prod

source_test.yaml
ref: https://github.com/google/osv.dev/issues/3400
=> Add MinimOS feed to test instance

gcp/workers/linter/Dockerfile, gcp/workers/linter/linter.py
fixes issues on android source name parsing.
=> fix(linter): handle android source correctly

gcp/workers/linter/linter.py
Updates the cron job to also delete stale findings. 
It first queries all existing findings from the database, then updates/creates entries based on new finding results, and finally removes findings no longer reported.
=> feat(linter): remove finding entries when the linter no longer reports the issues.

gcp/workers/staging_api_test/perform_api_calls.py
The staging-api-test throws connection errors due to a race condition where if a connection is closed prematurely, the client pool may reuse it before the closure is recognized. 
Changes it to wait for the full server response to fix this issue, and also adds return_exceptions=True to the gather call to disable noise from any other transient errors. We already log individual failures and some are expected during a load test.
=> fix(staging-api-test): make load test resilient to connection errors

docs/api/post-v1-query.md, docs/api/post-v1-querybatch.md
Also get rid of the weird non breaking space characters and replace them with normal spaces.
=> docs: Add documentation about git tag queries

gcp/website/frontend3/src/styles.scss
Update the blog so that it looks nicer and is easier to read.
New:
Existing:
=> feat(css): Update blogpost styles

gcp/workers/linter/linter.py
Replaces the hardcoded PREFIX_TO_SOURCE with the dynamic construct_prefix_to_source_map() function
=> feat(linter): replace hardcoded source prefix mapping with a db query

deployment/README.md, docs/api/post-v1-determineversion.md
=> fix(docs): correct typos in deployment and post-v1-determineversion docs

source.yaml
@i-bs FYI, let me know if you are happy to merge this.
=> feat: Add bellsoft source to prod

gcp/workers/exporter/export_runner.py, gcp/workers/exporter/exporter.py
safe_upload_single was not actually uploading new files.
=> fix: safe upload to actually upload a file

gcp/workers/linter/linter.py
construct_prefix_to_source_map() should only be called after setting the ndb context
=> fix(linter): query source repository after setting ndb context

gcp/website/frontend_handlers.py
Fixes ecosystem filtering for Git vulnerabilities.
=> fix(frontend): fix Git ecosystem filtering

docker/worker-base/Dockerfile, gcp/api/Dockerfile, gcp/website/Dockerfile
I think I found all the instances of python in dockerfiles.
Not sure if there's any other files that need to be updated
=> chore: Upgrade to 3.13

gcp/workers/linter/Dockerfile
=> fix(linter): update osv-schema version

source.yaml
=> feat: add openEuler to production environment

vulnfeeds/cves/nvd2.go
https://github.com/google/osv.dev/pull/1833#discussion_r1406711609 - it's me, I'm the fool. And I gave up so we're doing this instead.
=> fix(NVD): increase max length of url to align with schema

source.yaml
https://github.com/google/osv.dev/issues/3780
=> feat: Add echo to the prod source yaml file

source_test.yaml
=> feat(datasources): Enable Debian-CVE ingestion in test

deployment/build-and-stage.yaml
would help to actually give it the Dockerfile
=> fix(build): record checker builder

vulnfeeds/cves/versions.go
if len(pathParts) == 2, pathParts[2] is out of range
=> fix: length error

vulnfeeds/vulns/vulns.go
This is also nice for local development to not have to wait as long to load in all the CVEs
=> feat: Make NVD data load faster by running in separate goroutines.

gcp/workers/importer/importer.py
21 minutes to 2 seconds. By skipping jsonschema validate for parsing just (modified, id)
=> feat: Much faster REST API import

vulnfeeds/cmd/alpine/Dockerfile, vulnfeeds/cmd/alpine/main.go, vulnfeeds/cmd/alpine/run_alpine_convert.sh, vulnfeeds/cmd/debian/main.go, vulnfeeds/cmd/debian/main_test.go
=> fix: add severity score to Alpine vulns

Makefile
=> fix(make): run lint via poetry

deployment/clouddeploy/gke-workers/base/debian-cve-convert.yaml
Doesn't actually use that much cpu.
=> fix(cron): lower cpu limit for debian cve convert

gcp/workers/worker/worker.py
https://github.com/google/osv.dev/issues/3849
=> feat: Enable Vanir signature generation in prod
